//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PullToRefreshView, UINoDataLoadingView, UIRefreshControl, UITableView;

@interface AbstractTableDataSource : NSObject <UITableViewDataSource, UITableViewDelegate>
{
    _Bool searching;
    _Bool _simplify;
    UITableView *_thisSourceTable;
    NSString *_searchString;
    NSString *_guid;
    UIRefreshControl *_refreshControl;
    PullToRefreshView *_pullToRefresh;
    UINoDataLoadingView *_noDataView;
}

@property(nonatomic) _Bool simplify; // @synthesize simplify=_simplify;
@property(nonatomic) __weak UINoDataLoadingView *noDataView; // @synthesize noDataView=_noDataView;
@property(nonatomic) __weak PullToRefreshView *pullToRefresh; // @synthesize pullToRefresh=_pullToRefresh;
@property __weak UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(copy, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(nonatomic) __weak UITableView *thisSourceTable; // @synthesize thisSourceTable=_thisSourceTable;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)finishLoading;
- (void)reloadTable;
- (void)reloadAll;
- (void)endSearch;
- (void)startSearch;
@property(readonly, nonatomic) _Bool canSearch;
@property(readonly, nonatomic) NSArray *searchSections;
@property(readonly, nonatomic) NSArray *currentSections;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

