//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKUsers;

@interface account_lookupContacts_res : VKResponse
{
    VKUsers *_found;
    VKUsers *_other;
}

@property(retain, nonatomic) VKUsers *other; // @synthesize other=_other;
@property(retain, nonatomic) VKUsers *found; // @synthesize found=_found;
- (void).cxx_destruct;

@end

