//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface account_setInfo_req : VKRequest
{
    NSNumber *_intro;
}

@property(retain, nonatomic) NSNumber *intro; // @synthesize intro=_intro;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

