//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSString;

@interface account_validateAction_req : VKRequest
{
    NSString *_confirm_hash;
}

@property(copy, nonatomic) NSString *confirm_hash; // @synthesize confirm_hash=_confirm_hash;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

