//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, NSString;

@interface account_getInfo_res : VKResponse
{
    NSString *_country;
    NSNumber *_https_required;
    NSNumber *_intro;
    NSNumber *_lang;
    NSString *_support_url;
}

@property(copy, nonatomic) NSString *support_url; // @synthesize support_url=_support_url;
@property(retain, nonatomic) NSNumber *lang; // @synthesize lang=_lang;
@property(retain, nonatomic) NSNumber *intro; // @synthesize intro=_intro;
@property(retain, nonatomic) NSNumber *https_required; // @synthesize https_required=_https_required;
@property(copy, nonatomic) NSString *country; // @synthesize country=_country;
- (void).cxx_destruct;

@end

