//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSString;

@interface account_changePassword_req : VKRequest
{
    NSString *_restore_sid;
    NSString *_change_password_hash;
    NSString *_old_password;
    NSString *_new_password;
}

@property(copy, nonatomic, getter=get_new_password) NSString *new_password; // @synthesize new_password=_new_password;
@property(copy, nonatomic) NSString *old_password; // @synthesize old_password=_old_password;
@property(copy, nonatomic) NSString *change_password_hash; // @synthesize change_password_hash=_change_password_hash;
@property(copy, nonatomic) NSString *restore_sid; // @synthesize restore_sid=_restore_sid;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

