//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIButton, UILabel;

@interface AdsBottomPanel : UIView
{
    NSArray *stars;
    UILabel *friendsLabel;
    UIButton *_playButton;
}

@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
- (void).cxx_destruct;
- (void)setAdRating:(double)arg1 friendsText:(id)arg2 buttonText:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

