//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewControllerStyled.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSIndexPath, NSMutableArray, NSMutableDictionary, NSNumber, NSString;

@interface AlbumsViewController : UITableViewControllerStyled <UITableViewDelegate, UITableViewDataSource>
{
    NSString *guid;
    NSMutableArray *getAlbumsArray;
    NSNumber *ownerId;
    _Bool loading;
    _Bool endReached;
    long long totalAlbumsCount;
    NSNumber *albumsUpdateTime;
    NSMutableDictionary *getAlbumsDict;
    NSIndexPath *selectedRow;
    _Bool isAdmin;
    id <AudioViewDelegate> delegate;
}

@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin;
@property(nonatomic) id <AudioViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)albumsDidFinishLoadingWithStatus:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (void)checkData:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (struct CGSize)preferredContentSize;
- (id)initWithUid:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

