//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface AnimatedGifFrame : NSObject
{
    int _disposalMethod;
    int _frameNumber;
    NSData *_header;
    NSData *_data;
    double _delay;
    struct CGRect _area;
}

@property(nonatomic) struct CGRect area; // @synthesize area=_area;
@property(nonatomic) int frameNumber; // @synthesize frameNumber=_frameNumber;
@property(nonatomic) int disposalMethod; // @synthesize disposalMethod=_disposalMethod;
@property(nonatomic) double delay; // @synthesize delay=_delay;
@property(copy, nonatomic) NSData *data; // @synthesize data=_data;
@property(copy, nonatomic) NSData *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)dealloc;

@end

