//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"

@class NSData, NSFileHandle, NSObject<OS_dispatch_queue>, NSString, NSURL, NSURLConnection, NSURLRequest;

@interface AnimatedGifQueueObject : NSObject <NSURLConnectionDataDelegate>
{
    NSURLConnection *_connection;
    NSFileHandle *_fileHandle;
    unsigned long long bytesLoaded;
    NSURLRequest *_originalRequest;
    NSString *_originalFilePath;
    NSObject<OS_dispatch_queue> *_diskOperationQueue;
    _Bool _canceled;
    _Bool _isLoading;
    NSURL *_url;
    NSData *_data;
    double _loadingProgress;
    long long _expectedGifSize;
    CDUnknownBlockType _loadingProgressChangedBlock;
    CDUnknownBlockType _didLoadBlock;
}

+ (id)gifObjectForUrl:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType didLoadBlock; // @synthesize didLoadBlock=_didLoadBlock;
@property(copy, nonatomic) CDUnknownBlockType loadingProgressChangedBlock; // @synthesize loadingProgressChangedBlock=_loadingProgressChangedBlock;
@property(nonatomic) long long expectedGifSize; // @synthesize expectedGifSize=_expectedGifSize;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool canceled; // @synthesize canceled=_canceled;
@property(nonatomic) double loadingProgress; // @synthesize loadingProgress=_loadingProgress;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)finishCurrentDownload;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (_Bool)downloadGif;
- (long long)downloadedFileSize;
- (void)clearPath;
- (id)pathToFile;
- (void)cancel;
- (void)stopDownload;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

