//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "BITCrashManagerDelegate.h"
#import "BITHockeyManagerDelegate.h"
#import "BITUpdateManagerDelegate.h"
#import "UIApplicationDelegate.h"

@class FastAttributedStringCustomLink, MPMoviePlayerController, NSDate, NSDictionary, NSString, UIImageView, UIWindowMy;

@interface AppDelegate : UIResponder <BITHockeyManagerDelegate, BITUpdateManagerDelegate, BITCrashManagerDelegate, UIApplicationDelegate>
{
    MPMoviePlayerController *_moviePlayerController;
    FastAttributedStringCustomLink *pendingUrlToOpen;
    _Bool _inBackground;
    UIWindowMy *_window;
    NSDictionary *_authorizeAppDictionary;
    NSDate *_backgroundTime;
    UIImageView *_snapshotView;
}

+ (id)sharedInstance;
@property(retain, nonatomic) UIImageView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(retain, nonatomic) NSDate *backgroundTime; // @synthesize backgroundTime=_backgroundTime;
@property(retain, nonatomic) NSDictionary *authorizeAppDictionary; // @synthesize authorizeAppDictionary=_authorizeAppDictionary;
@property(nonatomic) _Bool inBackground; // @synthesize inBackground=_inBackground;
@property(retain, nonatomic) UIWindowMy *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)showUnknownUserWindow;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)application:(id)arg1 didChangeStatusBarOrientation:(long long)arg2;
- (void)application:(id)arg1 willChangeStatusBarOrientation:(long long)arg2 duration:(double)arg3;
- (void)registerDefaultsFromSettingsBundle;
- (void)authorizeAppNow;
- (void)facebookSessionChanged:(id)arg1 state:(unsigned long long)arg2 error:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)remoteControlReceivedWithEvent:(id)arg1;
- (void)showModalViewController:(id)arg1;
- (_Bool)needValidationPresented;
- (void)switchToViewController:(id)arg1;
- (void)processPush:(id)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)checkPendingUrl;
- (void)simulateMemoryWarning;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

