//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber, NSString;

@interface attachment_posted_photo : VKObject
{
    NSNumber *_id;
    NSNumber *_owner_id;
    NSString *_src;
    NSString *_photo_130;
}

@property(copy, nonatomic) NSString *photo_130; // @synthesize photo_130=_photo_130;
@property(copy, nonatomic) NSString *src; // @synthesize src=_src;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

