//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class AttachTextViewInternal, NSString, UIColor, UIFont;

@interface AttachTextViewGrowing : UIView <UITextViewDelegate>
{
    long long minHeight;
    long long maxHeight;
    _Bool _animateHeightChange;
    _Bool _lockFromBecomeFirstResponder;
    float _extraHeight;
    long long _maxNumberOfLines;
    long long _minNumberOfLines;
    AttachTextViewInternal *_internalTextView;
    id <AttachTextViewDelegate> _delegate;
    struct UIEdgeInsets _contentInset;
}

@property(nonatomic) _Bool lockFromBecomeFirstResponder; // @synthesize lockFromBecomeFirstResponder=_lockFromBecomeFirstResponder;
@property(nonatomic) float extraHeight; // @synthesize extraHeight=_extraHeight;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) id <AttachTextViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AttachTextViewInternal *internalTextView; // @synthesize internalTextView=_internalTextView;
@property(nonatomic) _Bool animateHeightChange; // @synthesize animateHeightChange=_animateHeightChange;
@property(nonatomic) long long minNumberOfLines; // @synthesize minNumberOfLines=_minNumberOfLines;
@property(nonatomic) long long maxNumberOfLines; // @synthesize maxNumberOfLines=_maxNumberOfLines;
- (void).cxx_destruct;
- (_Bool)endEditing:(_Bool)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)scrollRangeToVisible:(struct _NSRange)arg1;
- (_Bool)hasText;
@property(nonatomic) unsigned long long dataDetectorTypes;
@property(nonatomic) long long returnKeyType;
@property(nonatomic, getter=isEditable) _Bool editable;
@property(nonatomic) struct _NSRange selectedRange;
@property(nonatomic) long long textAlignment;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
@property(nonatomic) UIColor *textColor;
@property(nonatomic) UIFont *font;
@property(nonatomic) NSString *text;
- (_Bool)resignFirstResponder;
- (_Bool)isFirstResponder;
- (_Bool)becomeFirstResponder;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)growDidStop;
- (void)resizeTextView:(long long)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)measureMaxHeight;
- (void)layoutSubviews;
- (void)sizeToFit;
- (void)keyboardChange:(id)arg1;
- (void)commonInitializer;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

