//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKAudios;

@interface audio_getById_res : VKResponse
{
    VKAudios *_audios;
}

@property(retain, nonatomic) VKAudios *audios; // @synthesize audios=_audios;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

