//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSString;

@interface audio_getById_req : VKRequest
{
    NSString *_audios;
}

@property(copy, nonatomic) NSString *audios; // @synthesize audios=_audios;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

