//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber;

@interface audio_addAlbum_res : VKResponse
{
    NSNumber *_album_id;
}

@property(retain, nonatomic) NSNumber *album_id; // @synthesize album_id=_album_id;
- (void).cxx_destruct;

@end

