//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, iPadAudioViewSlider;

@interface AudioProgressView : UIView
{
    id <AudioProgressViewDelegate> _delegate;
    UILabel *_timeLabel;
    UILabel *_timeLabelBack;
    iPadAudioViewSlider *_songSlider;
}

@property(retain, nonatomic) iPadAudioViewSlider *songSlider; // @synthesize songSlider=_songSlider;
@property(retain, nonatomic) UILabel *timeLabelBack; // @synthesize timeLabelBack=_timeLabelBack;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak id <AudioProgressViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setTime:(int)arg1 to:(id)arg2 negative:(_Bool)arg3;
- (void)updateProgress;
- (id)initWithFrame:(struct CGRect)arg1 andDelegate:(id)arg2;

@end

