//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewControllerStyled.h"

#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, NSString, UIButton, UISearchBar, UISearchDisplayControllerNoHide, UITableView, VKAlbum;

@interface AudioView : UITableViewControllerStyled <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate>
{
    NSString *guid;
    NSMutableArray *getAudiosArray;
    NSNumber *getAudiosUpdateTime;
    _Bool loading;
    _Bool endReached;
    unsigned long long totalAudioCount;
    NSMutableDictionary *getAudioDict;
    NSMutableArray *searchResults;
    _Bool needAlbums;
    _Bool isRecomendation;
    _Bool isAdmin;
    UITableView *table;
    UISearchBar *searchBar;
    NSNumber *ownerId;
    VKAlbum *albumId;
    id <AudioViewDelegate> delegate;
    UIButton *backButton;
}

@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton;
@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin;
@property(nonatomic) _Bool isRecomendation; // @synthesize isRecomendation;
@property(nonatomic) id <AudioViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool needAlbums; // @synthesize needAlbums;
@property(retain, nonatomic) VKAlbum *albumId; // @synthesize albumId;
@property(retain, nonatomic) NSNumber *ownerId; // @synthesize ownerId;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar;
@property(retain, nonatomic) UITableView *table; // @synthesize table;
- (void).cxx_destruct;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(long long)arg2;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (void)updateSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)audioSearchResultsUpdated:(id)arg1;
- (void)audiosDidFinishLoadingWithStatus:(id)arg1;
- (void)audioRecomendationDidFinishLoadingWithStatus:(id)arg1;
- (void)audioDidRemoveFromList:(id)arg1;
- (void)audioDidStartPlaying:(id)arg1;
- (void)audioDidStopPlaying:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)setOwnerId:(id)arg1 andAlbumId:(id)arg2;
- (void)checkData:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UISearchDisplayControllerNoHide *searchController; // @dynamic searchController;
@property(readonly) Class superclass;

@end

