//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface audio_getRecommendations_req : VKRequest
{
    NSNumber *_target_audio;
    NSNumber *_user_id;
    NSNumber *_offset;
    NSNumber *_count;
    NSNumber *_shuffle;
}

@property(retain, nonatomic) NSNumber *shuffle; // @synthesize shuffle=_shuffle;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSNumber *target_audio; // @synthesize target_audio=_target_audio;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

