//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface audio_getPopular_req : VKRequest
{
    NSNumber *_only_eng;
    NSNumber *_genre_id;
    NSNumber *_offset;
    NSNumber *_count;
}

@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSNumber *genre_id; // @synthesize genre_id=_genre_id;
@property(retain, nonatomic) NSNumber *only_eng; // @synthesize only_eng=_only_eng;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

