//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class CAShapeLayer, UIColor;

@interface AUISelectiveBordersLayer : CALayer
{
    CAShapeLayer *borderLayer;
    float selectiveBordersWidth;
    UIColor *selectiveBordersColor;
    unsigned long long selectiveBorderFlag;
    unsigned long long selectiveBorderDrawLocation;
}

@property(nonatomic) unsigned long long selectiveBorderDrawLocation; // @synthesize selectiveBorderDrawLocation;
@property(nonatomic) unsigned long long selectiveBorderFlag; // @synthesize selectiveBorderFlag;
@property(nonatomic) float selectiveBordersWidth; // @synthesize selectiveBordersWidth;
@property(retain, nonatomic) UIColor *selectiveBordersColor; // @synthesize selectiveBordersColor;
- (void).cxx_destruct;
- (void)reloadBorders;
- (void)setCornerRadius:(double)arg1;
- (void)layoutSublayers;
- (void)commonInit;
- (id)initWithLayer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

