//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, NSString;

@interface auth_login_res : VKResponse
{
    NSString *_access_token;
    NSString *_secret;
    NSString *_redirect_uri;
    NSNumber *_expires_in;
    NSNumber *_user_id;
    NSNumber *_https_required;
    NSString *_trusted_hash;
    NSNumber *_processing;
    NSNumber *_timeout;
}

@property(retain, nonatomic) NSNumber *timeout; // @synthesize timeout=_timeout;
@property(retain, nonatomic) NSNumber *processing; // @synthesize processing=_processing;
@property(copy, nonatomic) NSString *trusted_hash; // @synthesize trusted_hash=_trusted_hash;
@property(retain, nonatomic) NSNumber *https_required; // @synthesize https_required=_https_required;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSNumber *expires_in; // @synthesize expires_in=_expires_in;
@property(copy, nonatomic) NSString *redirect_uri; // @synthesize redirect_uri=_redirect_uri;
@property(copy, nonatomic) NSString *secret; // @synthesize secret=_secret;
@property(copy, nonatomic) NSString *access_token; // @synthesize access_token=_access_token;
- (void).cxx_destruct;

@end

