//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CacheLayerConnectionDelegate.h"

@class CacheFileInfo, NSMutableArray, NSString, NSThread;

@interface AVPlayerCacheLayer : NSObject <CacheLayerConnectionDelegate>
{
    struct _opaque_pthread_mutex_t cacheConnectionsMutex;
    struct __CFSocket *listenSocket;
    NSThread *workingThread;
    NSMutableArray *connections;
    NSMutableArray *connectionsProxy;
    int port;
    NSString *cachePath;
    NSString *tempPath;
    NSString *currentAid;
    NSString *currentOid;
    long long lastAudioNum;
    CacheFileInfo *lastFileInfo;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CacheFileInfo *lastFileInfo; // @synthesize lastFileInfo;
@property(nonatomic) long long lastAudioNum; // @synthesize lastAudioNum;
@property(copy, nonatomic) NSString *currentOid; // @synthesize currentOid;
@property(copy, nonatomic) NSString *currentAid; // @synthesize currentAid;
@property(copy, nonatomic) NSString *tempPath; // @synthesize tempPath;
@property(copy, nonatomic) NSString *cachePath; // @synthesize cachePath;
@property(nonatomic) int port; // @synthesize port;
- (void).cxx_destruct;
- (void)cancelConnectionsForAid:(id)arg1 Oid:(id)arg2;
- (void)layerConnectionProxyDidClose:(id)arg1;
- (void)layerConnectionProxyDidOpen:(id)arg1;
- (void)layerConnectionDidClose:(id)arg1;
- (void)setNeedCacheCurrentAudio;
- (void)clearConnections;
- (void)performClear;
- (void)stopProxyLayer;
- (void)handleNewNativeSocket:(int)arg1;
- (int)startProxyLayer;
- (void)threadProc;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

