//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BITFeedbackUserDataDelegate.h"
#import "BITImageAnnotationDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextViewDelegate.h"

@class BITFeedbackManager, NSMutableArray, NSString, UIScrollView, UITapGestureRecognizer, UITextView, UIView;

@interface BITFeedbackComposeViewController : UIViewController <BITFeedbackUserDataDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIActionSheetDelegate, BITImageAnnotationDelegate, UITextViewDelegate>
{
    long long _statusBarStyle;
    _Bool _blockUserDataScreen;
    _Bool _actionSheetVisible;
    id <BITFeedbackComposeViewControllerDelegate> _delegate;
    BITFeedbackManager *_manager;
    UITextView *_textView;
    UIView *_contentViewContainer;
    UIScrollView *_attachmentScrollView;
    NSMutableArray *_attachmentScrollViewImageViews;
    NSString *_text;
    NSMutableArray *_attachments;
    NSMutableArray *_imageAttachments;
    UIView *_textAccessoryView;
    long long _selectedAttachmentIndex;
    UITapGestureRecognizer *_tapRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(nonatomic) long long selectedAttachmentIndex; // @synthesize selectedAttachmentIndex=_selectedAttachmentIndex;
@property(retain, nonatomic) UIView *textAccessoryView; // @synthesize textAccessoryView=_textAccessoryView;
@property(retain, nonatomic) NSMutableArray *imageAttachments; // @synthesize imageAttachments=_imageAttachments;
@property(retain, nonatomic) NSMutableArray *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSMutableArray *attachmentScrollViewImageViews; // @synthesize attachmentScrollViewImageViews=_attachmentScrollViewImageViews;
@property(retain, nonatomic) UIScrollView *attachmentScrollView; // @synthesize attachmentScrollView=_attachmentScrollView;
@property(retain, nonatomic) UIView *contentViewContainer; // @synthesize contentViewContainer=_contentViewContainer;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak BITFeedbackManager *manager; // @synthesize manager=_manager;
@property(nonatomic) __weak id <BITFeedbackComposeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)annotationControllerDidCancel:(id)arg1;
- (void)annotationController:(id)arg1 didFinishWithImage:(id)arg2;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)userDataUpdateFinished;
- (void)userDataUpdateCancelled;
- (void)imageButtonAction:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)paste:(id)arg1;
- (void)scrollViewTapped:(id)arg1;
- (void)addPhotoAction:(id)arg1;
- (void)dismissWithResult:(unsigned long long)arg1;
- (void)sendAction:(id)arg1;
- (void)dismissAction:(id)arg1;
- (void)setUserDataAction;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)updateBarButtonState;
- (void)refreshAttachmentScrollview;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)prepareWithItems:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

