//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iPadStandardCell.h"

@class UIImageView;

@interface BlockFeedbackCell : iPadStandardCell
{
    UIImageView *_blockView;
    int _position;
}

@property(readonly, nonatomic) UIImageView *blockView; // @synthesize blockView=_blockView;
@property(nonatomic) int position; // @synthesize position=_position;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

