//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class auth_login_req, auth_login_res;

@protocol CodeValidationControllerDelegate
- (void)processAuthorizationResponse:(auth_login_req *)arg1;
- (void)codeValidationSucceedWithResult:(auth_login_res *)arg1;
@end

