//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AttachTextViewDelegate.h"

@class CommentFieldView, UIButton;

@protocol CommentFieldDelegate <AttachTextViewDelegate>
- (void)sendButtonPressed:(UIButton *)arg1;
- (void)attachButtonPressed:(UIButton *)arg1;

@optional
- (_Bool)canShowSettingsButton;
- (void)settingsButtonPressed:(CommentFieldView *)arg1;
- (void)smileButtonPressed:(CommentFieldView *)arg1;
@end

