//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISelectiveBorderView.h"

@class AttachTextViewGrowing, UIActivityIndicatorView, UIButton, UIImageView, UIToolbar, UIView;

@interface CommentFieldView : UISelectiveBorderView
{
    _Bool _saveInputViewState;
    _Bool _enabled;
    UIButton *_attachButton;
    UIButton *_sendButton;
    UIButton *_settingsButton;
    UIButton *_smileysButton;
    UIImageView *_messageFieldBackground;
    UIActivityIndicatorView *_messageFieldLoadingIndicator;
    UIView *_messageFieldTextViewClipView;
    UIToolbar *_blurToolbar;
    AttachTextViewGrowing *_messageFieldTextView;
    id <CommentFieldDelegate> _delegate;
}

@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool saveInputViewState; // @synthesize saveInputViewState=_saveInputViewState;
@property(nonatomic) __weak id <CommentFieldDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AttachTextViewGrowing *messageFieldTextView; // @synthesize messageFieldTextView=_messageFieldTextView;
@property(retain, nonatomic) UIToolbar *blurToolbar; // @synthesize blurToolbar=_blurToolbar;
@property(retain, nonatomic) UIView *messageFieldTextViewClipView; // @synthesize messageFieldTextViewClipView=_messageFieldTextViewClipView;
@property(retain, nonatomic) UIActivityIndicatorView *messageFieldLoadingIndicator; // @synthesize messageFieldLoadingIndicator=_messageFieldLoadingIndicator;
@property(retain, nonatomic) UIImageView *messageFieldBackground; // @synthesize messageFieldBackground=_messageFieldBackground;
@property(retain, nonatomic) UIButton *smileysButton; // @synthesize smileysButton=_smileysButton;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UIButton *attachButton; // @synthesize attachButton=_attachButton;
- (void).cxx_destruct;
- (void)destroySmiles;
- (_Bool)canBecomeFirstResponder;
- (void)setSmileysButtonIsKeyboard:(_Bool)arg1;
- (void)dealloc;
- (void)removeAllAnimations:(id)arg1;
- (void)removeAllAnimations;
- (_Bool)becomeFirstResponder;
- (_Bool)resignFirstResponder;
- (_Bool)isFirstResponder;
- (void)settingsButtonPressed:(id)arg1;
- (void)smileButtonPressed:(id)arg1;
- (void)setSettingsButtonActive:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

@end

