//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BackupImageView, UIImageView, UILabel, UIView;

@interface ContactsListCell : UITableViewCell
{
    _Bool withIndex;
    UIImageView *onlineImage;
    BackupImageView *avatarImage;
    UILabel *firstNameLabel;
    UILabel *secondNameLabel;
    UIImageView *checkMarkImage;
    UIView *background;
}

@property(retain, nonatomic) UIView *background; // @synthesize background;
@property(retain, nonatomic) UIImageView *checkMarkImage; // @synthesize checkMarkImage;
@property(retain, nonatomic) UILabel *secondNameLabel; // @synthesize secondNameLabel;
@property(retain, nonatomic) UILabel *firstNameLabel; // @synthesize firstNameLabel;
@property(retain, nonatomic) BackupImageView *avatarImage; // @synthesize avatarImage;
@property(retain, nonatomic) UIImageView *onlineImage; // @synthesize onlineImage;
- (void).cxx_destruct;
- (void)setFirstName:(id)arg1 andSecondName:(id)arg2 withIndex:(_Bool)arg3;
- (void)layoutSubviews;
- (id)reuseIdentifier;

@end

