//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, NSString, account_getInfo_res;

@interface ContactsController : NSObject
{
    NSString *uploadingImage;
    double lastSearchTimeUsers;
    NSMutableDictionary *searchUsersUids;
    CDUnknownBlockType contactsSearch;
    _Bool searching;
    _Bool searchingEndReached;
    NSMutableArray *currentUserFriends;
    NSMutableArray *searchUsersArray;
    long long totalUsersSearchCount;
    NSMutableDictionary *currentUserFriendsUids;
    NSNumber *currentUserUpdateTime;
    account_getInfo_res *_userInfo;
}

+ (id)sharedInstance;
@property(retain, nonatomic) account_getInfo_res *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) _Bool searchingEndReached; // @synthesize searchingEndReached;
@property(retain, nonatomic) NSNumber *currentUserUpdateTime; // @synthesize currentUserUpdateTime;
@property(retain, nonatomic) NSMutableDictionary *currentUserFriendsUids; // @synthesize currentUserFriendsUids;
@property(nonatomic) long long totalUsersSearchCount; // @synthesize totalUsersSearchCount;
@property(nonatomic) _Bool searching; // @synthesize searching;
@property(retain, nonatomic) NSMutableArray *searchUsersArray; // @synthesize searchUsersArray;
@property(retain, nonatomic) NSMutableArray *currentUserFriends; // @synthesize currentUserFriends;
- (void).cxx_destruct;
- (void)loadPollInfoWithId:(id)arg1 andOwnerId:(id)arg2;
- (id)loadFollowersForUid:(id)arg1 withOffset:(id)arg2 andCount:(id)arg3 onMe:(_Bool)arg4;
- (id)loadMutualFriendsForUid:(id)arg1;
- (void)setStatus:(id)arg1;
- (id)searchUsers:(id)arg1 withOffset:(unsigned long long)arg2 andCount:(unsigned long long)arg3;
- (id)loadFeedBackWithStartTime:(id)arg1 andEndTime:(id)arg2 andCount:(id)arg3 andFrom:(id)arg4;
- (id)loadWallRepostsCommentsWithStartTime:(id)arg1 andEndTime:(id)arg2 withPostId:(id)arg3 andCount:(id)arg4 andFrom:(id)arg5;
- (id)loadNewsCommentsWithStartTime:(id)arg1 andEndTime:(id)arg2 andCount:(id)arg3 andFrom:(id)arg4;
- (void)setNotificationsAsViewed;
- (id)loadNewsForFrom:(id)arg1 andCount:(id)arg2 photos:(_Bool)arg3;
- (id)addWallPost:(id)arg1 withAttachments:(id)arg2 withServices:(id)arg3 sign:(_Bool)arg4;
- (void)addWallCommentForPid:(id)arg1 andOwner:(id)arg2 withComment:(id)arg3 andAttachments:(id)arg4 fromGroup:(_Bool)arg5;
- (id)loadWallCommentsForPid:(id)arg1 andOwner:(id)arg2 withOffset:(long long)arg3 andCount:(long long)arg4;
- (void)deleteWallCommentForCid:(id)arg1 andOwner:(id)arg2;
- (void)deleteWallForPost:(id)arg1 onComplete:(CDUnknownBlockType)arg2;
- (id)loadWallForUid:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3 filter:(long long)arg4;
- (void)setProfileImage:(id)arg1;
- (void)importContacts:(id)arg1 service:(id)arg2;
- (id)loadSuggestionsWithOffset:(long long)arg1 andCount:(long long)arg2;
- (void)loadFriendsByPhones:(id)arg1;
- (void)addFriend:(id)arg1 isRequest:(_Bool)arg2;
- (void)deleteFriend:(id)arg1;
- (id)loadUser:(id)arg1;
- (id)loadRequestsWithOffset:(long long)arg1 andCount:(long long)arg2 suggested:(_Bool)arg3;
- (id)loadFriendsForUid:(id)arg1 withOrder:(id)arg2;
- (void)cleanUp;
- (id)init;

@end

