//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CountryInfo, CountryListSelector;

@protocol CountryListSelectorDelegate
- (void)countryList:(CountryListSelector *)arg1 didSelectCountry:(CountryInfo *)arg2;
@end

