//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IVKRequest.h"

@class NSNumber, NSString;

@protocol CreateAlbumRequest <IVKRequest>
@property(retain, nonatomic) NSNumber *group_id;
@property(retain, nonatomic) NSNumber *comment_privacy;
@property(copy, nonatomic) NSString *title;
@property(retain, nonatomic) NSNumber *privacy;

@optional
@property(copy, nonatomic) NSString *Mdescription;
@end

