//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKDocuments;

@interface docs_save_res : VKResponse
{
    VKDocuments *_response;
}

@property(retain, nonatomic) VKDocuments *response; // @synthesize response=_response;
- (void).cxx_destruct;

@end

