//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DTAsyncFileDeleter : NSObject
{
}

+ (id)sharedInstance;
- (_Bool)_supportsTaskCompletion;
- (void)removeItemAtURL:(id)arg1;
- (void)removeItemAtPath:(id)arg1;
- (void)waitUntilFinished;
- (id)init;

@end

