//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GroupsContentDataSource.h"

@interface EventsContentDataSource : GroupsContentDataSource
{
    _Bool _pastEvents;
}

@property(nonatomic) _Bool pastEvents; // @synthesize pastEvents=_pastEvents;
- (id)titleForSection;

@end

