//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIOverlayWindow, UIPanGestureRecognizer;

@interface ExpandableView : UIView <UIGestureRecognizerDelegate>
{
    UIPanGestureRecognizer *_panGesture;
    _Bool _isExpanded;
    _Bool _crossDissolve;
    _Bool _inTransition;
    CDUnknownBlockType _willBeHiddenBlock;
    CDUnknownBlockType _didDidHiddenBlock;
    UIView *_originalParentView;
    UIView *_parentControllerView;
    UIView *_parentRootView;
    UIOverlayWindow *_presentationWindow;
    UIView *_darkView;
    struct UIEdgeInsets _maskLayerInsets;
    struct CGRect _originalPosition;
    struct CGRect _originalFrame;
    struct CGRect _originalPanPosition;
}

@property(nonatomic) struct CGRect originalPanPosition; // @synthesize originalPanPosition=_originalPanPosition;
@property(nonatomic) struct CGRect originalFrame; // @synthesize originalFrame=_originalFrame;
@property(nonatomic) struct CGRect originalPosition; // @synthesize originalPosition=_originalPosition;
@property(nonatomic) _Bool inTransition; // @synthesize inTransition=_inTransition;
@property(retain, nonatomic) UIView *darkView; // @synthesize darkView=_darkView;
@property(retain, nonatomic) UIOverlayWindow *presentationWindow; // @synthesize presentationWindow=_presentationWindow;
@property(nonatomic) __weak UIView *parentRootView; // @synthesize parentRootView=_parentRootView;
@property(nonatomic) __weak UIView *parentControllerView; // @synthesize parentControllerView=_parentControllerView;
@property(nonatomic) __weak UIView *originalParentView; // @synthesize originalParentView=_originalParentView;
@property(nonatomic) _Bool crossDissolve; // @synthesize crossDissolve=_crossDissolve;
@property(copy, nonatomic) CDUnknownBlockType didDidHiddenBlock; // @synthesize didDidHiddenBlock=_didDidHiddenBlock;
@property(copy, nonatomic) CDUnknownBlockType willBeHiddenBlock; // @synthesize willBeHiddenBlock=_willBeHiddenBlock;
@property(nonatomic) struct UIEdgeInsets maskLayerInsets; // @synthesize maskLayerInsets=_maskLayerInsets;
@property(nonatomic, setter=setExpanded:) _Bool isExpanded; // @synthesize isExpanded=_isExpanded;
- (void).cxx_destruct;
- (void)finishTransition;
- (void)makeLayout:(struct CGSize)arg1;
- (void)animateTransition;
- (void)beginTransition;
- (void)animateBlock:(CDUnknownBlockType)arg1;
- (void)closeExpanding;
- (void)panView:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (struct CGSize)expandedSize;
- (void)dealloc;
- (void)updateViewPosition;
- (void)updateViewSize;
- (void)expandFromCurrentPositionInView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

