//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, VKGroups, VKUsers, VKVideos;

@interface fave_getVideos_res : VKResponse
{
    VKVideos *_items;
    NSNumber *_count;
    VKUsers *_profiles;
    VKGroups *_groups;
}

@property(retain, nonatomic) VKGroups *groups; // @synthesize groups=_groups;
@property(retain, nonatomic) VKUsers *profiles; // @synthesize profiles=_profiles;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) VKVideos *items; // @synthesize items=_items;
- (void).cxx_destruct;

@end

