//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface fave_getUsers_req : VKRequest
{
    NSString *_fields;
    NSNumber *_offset;
    NSNumber *_count;
}

@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(copy, nonatomic) NSString *fields; // @synthesize fields=_fields;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

