//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBDynamicFrameworkLoader : NSObject
{
}

+ (void)setSqlitePath:(id)arg1;
+ (id)sqlitePath;
+ (void)setFrameworkPathTemplate:(id)arg1;
+ (id)frameworkPathTemplate;
+ (void *)loadSymbol:(id)arg1 withFramework:(id)arg2;
+ (void *)loadkSecClass;
+ (void *)loadkSecReturnData;
+ (void *)loadkSecMatchLimit;
+ (void *)loadkSecMatchLimitOne;
+ (void *)loadkSecAttrAccessGroup;
+ (void *)loadkSecClassGenericPassword;
+ (void *)loadkSecValueData;
+ (void *)loadkSecAttrGeneric;
+ (void *)loadkSecAttrService;
+ (void *)loadkSecAttrAccount;
+ (void *)loadkSecAttrAccessibleAfterFirstUnlockThisDeviceOnly;
+ (void *)loadkSecAttrAccessible;
+ (struct __SecRandom *)loadkSecRandomDefault;
+ (void *)loadTypeRefConstantFromSecurityFramework:(id)arg1;
+ (id)loadStringConstant:(id)arg1 withFramework:(id)arg2;
+ (Class)loadClass:(id)arg1 withFramework:(id)arg2;

@end

