//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FBFetchedAppSettings : NSObject
{
    _Bool _supportsAttribution;
    _Bool _supportsImplicitSdkLogging;
    _Bool _enableLoginTooltip;
    NSString *_serverAppName;
    NSString *_appID;
    NSString *_loginTooltipContent;
}

@property(copy, nonatomic) NSString *loginTooltipContent; // @synthesize loginTooltipContent=_loginTooltipContent;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property _Bool enableLoginTooltip; // @synthesize enableLoginTooltip=_enableLoginTooltip;
@property _Bool supportsImplicitSdkLogging; // @synthesize supportsImplicitSdkLogging=_supportsImplicitSdkLogging;
@property _Bool supportsAttribution; // @synthesize supportsAttribution=_supportsAttribution;
@property(copy, nonatomic) NSString *serverAppName; // @synthesize serverAppName=_serverAppName;
- (void)dealloc;
- (id)initWithAppID:(id)arg1;
- (id)init;

@end

