//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBImageResourceLoader : NSObject
{
}

+ (id)imageNamed:(id)arg1 fromBytes:(const char *)arg2 length:(unsigned long long)arg3 fromRetinaBytes:(const char *)arg4 retinaLength:(unsigned long long)arg5;
+ (id)imageFromBytes:(const char *)arg1 length:(unsigned long long)arg2 fromRetinaBytes:(const char *)arg3 retinaLength:(unsigned long long)arg4;
+ (id)loadImageFromBytes:(const char *)arg1 length:(unsigned long long)arg2 scale:(double)arg3;

@end

