//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIActionSheetDelegate.h"

@class FBRequestConnection, FBSession, NSArray, NSNumber, UIButton, UILabel;

@interface FBLoginView : UIView <UIActionSheetDelegate>
{
    _Bool _hasShownTooltipBubble;
    NSArray *_permissions;
    NSArray *_readPermissions;
    NSArray *_publishPermissions;
    unsigned long long _defaultAudience;
    unsigned long long _loginBehavior;
    unsigned long long _tooltipBehavior;
    unsigned long long _tooltipColorStyle;
    id <FBLoginViewDelegate> _delegate;
    UILabel *_label;
    UIButton *_button;
    FBSession *_session;
    FBRequestConnection *_requestConnection;
    id <FBGraphUser> _user;
    CDUnknownBlockType _sessionStateHandler;
    CDUnknownBlockType _requestHandler;
    NSNumber *_lastObservedStateWasOpen;
}

@property(nonatomic) _Bool hasShownTooltipBubble; // @synthesize hasShownTooltipBubble=_hasShownTooltipBubble;
@property(copy) NSNumber *lastObservedStateWasOpen; // @synthesize lastObservedStateWasOpen=_lastObservedStateWasOpen;
@property(copy, nonatomic) CDUnknownBlockType requestHandler; // @synthesize requestHandler=_requestHandler;
@property(copy, nonatomic) CDUnknownBlockType sessionStateHandler; // @synthesize sessionStateHandler=_sessionStateHandler;
@property(retain, nonatomic) id <FBGraphUser> user; // @synthesize user=_user;
@property(retain, nonatomic) FBRequestConnection *requestConnection; // @synthesize requestConnection=_requestConnection;
@property(retain, nonatomic) FBSession *session; // @synthesize session=_session;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) id <FBLoginViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long tooltipColorStyle; // @synthesize tooltipColorStyle=_tooltipColorStyle;
@property(nonatomic) unsigned long long tooltipBehavior; // @synthesize tooltipBehavior=_tooltipBehavior;
@property(nonatomic) unsigned long long loginBehavior; // @synthesize loginBehavior=_loginBehavior;
@property(nonatomic) unsigned long long defaultAudience; // @synthesize defaultAudience=_defaultAudience;
@property(copy, nonatomic) NSArray *publishPermissions; // @synthesize publishPermissions=_publishPermissions;
@property(copy, nonatomic) NSArray *readPermissions; // @synthesize readPermissions=_readPermissions;
@property(copy) NSArray *permissions; // @synthesize permissions=_permissions;
- (void)buttonPressed:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)handleActiveSessionUnsetNotifications:(id)arg1;
- (void)handleActiveSessionSetNotifications:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unwireViewForSession;
- (void)wireViewForSession:(id)arg1 userInfo:(id)arg2;
- (void)wireViewForSessionWithoutOpening:(id)arg1;
- (void)informDelegateOfError:(id)arg1;
- (void)informDelegate:(_Bool)arg1;
- (void)didMoveToWindow;
- (void)showTooltipIfNeeded;
- (void)fetchMeInfo;
- (void)configureViewForStateLoggedIn:(_Bool)arg1;
- (id)logOutText;
- (id)logInText;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)initialize;
- (void)initializeBlocks;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithPublishPermissions:(id)arg1 defaultAudience:(unsigned long long)arg2;
- (id)initWithReadPermissions:(id)arg1;
- (id)initWithPermissions:(id)arg1;
- (id)init;

@end

