//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBRequest.h"

@class NSError, NSMutableData, NSMutableDictionary, NSString, NSURLConnection;

@interface FBRequest (Deprecated)
+ (id)serializeURL:(id)arg1 params:(id)arg2 httpMethod:(id)arg3;
+ (id)serializeURL:(id)arg1 params:(id)arg2;
- (id)description;
- (_Bool)loading;
@property(nonatomic) _Bool sessionDidExpire;
@property(nonatomic) unsigned long long state;
@property(retain, nonatomic) NSError *error;
@property(retain, nonatomic) NSMutableData *responseText;
@property(retain, nonatomic) NSURLConnection *connection;
@property(retain, nonatomic) NSMutableDictionary *params;
@property(copy, nonatomic) NSString *httpMethod;
@property(copy, nonatomic) NSString *url;
@property(nonatomic) id <FBRequestDelegate> delegate;
@end

