//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSession.h"

@class NSString;

@interface FBTestSession : FBSession
{
    _Bool _forceAccessTokenRefresh;
    _Bool _disableReauthorize;
    NSString *_appAccessToken;
    NSString *_testUserID;
    NSString *_testUserName;
    NSString *_testAppID;
    NSString *_testAppSecret;
    NSString *_machineUniqueUserTag;
    NSString *_sessionUniqueUserTag;
    unsigned long long _mode;
    NSString *_testAppClientToken;
}

+ (void)deleteUnitTestUser:(id)arg1 accessToken:(id)arg2;
+ (id)sessionForUnitTestingWithPermissions:(id)arg1 mode:(unsigned long long)arg2 sessionUniqueUserTag:(id)arg3;
+ (id)sessionWithPrivateUserWithPermissions:(id)arg1;
+ (id)sessionWithSharedUserWithPermissions:(id)arg1;
+ (id)sessionWithSharedUserWithPermissions:(id)arg1 uniqueUserTag:(id)arg2;
@property(copy) NSString *testAppClientToken; // @synthesize testAppClientToken=_testAppClientToken;
@property unsigned long long mode; // @synthesize mode=_mode;
@property(copy) NSString *sessionUniqueUserTag; // @synthesize sessionUniqueUserTag=_sessionUniqueUserTag;
@property(copy) NSString *machineUniqueUserTag; // @synthesize machineUniqueUserTag=_machineUniqueUserTag;
@property _Bool disableReauthorize; // @synthesize disableReauthorize=_disableReauthorize;
@property(copy) NSString *testAppSecret; // @synthesize testAppSecret=_testAppSecret;
@property(copy) NSString *testAppID; // @synthesize testAppID=_testAppID;
@property(copy) NSString *testUserName; // @synthesize testUserName=_testUserName;
@property(copy) NSString *testUserID; // @synthesize testUserID=_testUserID;
@property(copy) NSString *appAccessToken; // @synthesize appAccessToken=_appAccessToken;
- (_Bool)shouldExtendAccessToken;
- (void)authorizeWithPermissions:(id)arg1 behavior:(unsigned long long)arg2 defaultAudience:(unsigned long long)arg3 isReauthorize:(_Bool)arg4;
- (_Bool)transitionToState:(unsigned long long)arg1 withAccessTokenData:(id)arg2 shouldCache:(_Bool)arg3;
@property _Bool forceAccessTokenRefresh;
- (void)findOrCreateSharedUser;
@property(readonly, copy) NSString *sharedTestUserIdentifier;
- (id)validNameStringFromInteger:(unsigned long long)arg1;
- (void)retrieveTestUsersForApp;
- (void)populateTestUsers:(id)arg1 testAccounts:(id)arg2;
- (void)raiseException:(id)arg1;
- (void)transitionToOpenWithToken:(id)arg1;
- (void)createNewTestUser;
@property(readonly, copy) NSString *permissionsString;
- (void)dealloc;
- (id)initWithAppID:(id)arg1 appSecret:(id)arg2 clientToken:(id)arg3 machineUniqueUserTag:(id)arg4 sessionUniqueUserTag:(id)arg5 mode:(unsigned long long)arg6 permissions:(id)arg7 tokenCachingStrategy:(id)arg8;

@end

