//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface friends_getRequests_req : VKRequest
{
    NSNumber *_offset;
    NSNumber *_count;
    NSNumber *_extended;
    NSNumber *_need_mutual;
    NSNumber *_out;
    NSNumber *_sort;
    NSNumber *_suggested;
}

@property(retain, nonatomic) NSNumber *suggested; // @synthesize suggested=_suggested;
@property(retain, nonatomic) NSNumber *sort; // @synthesize sort=_sort;
@property(retain, nonatomic) NSNumber *out; // @synthesize out=_out;
@property(retain, nonatomic) NSNumber *need_mutual; // @synthesize need_mutual=_need_mutual;
@property(retain, nonatomic) NSNumber *extended; // @synthesize extended=_extended;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

