//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKFriendLists;

@interface friends_getLists_res : VKResponse
{
    VKFriendLists *_response;
}

@property(retain, nonatomic) VKFriendLists *response; // @synthesize response=_response;
- (void).cxx_destruct;

@end

