//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, NSString;

@interface FriendsLogicViewController : UIViewControllerStyled
{
    NSString *guid;
    NSMutableArray *searchResults;
    NSMutableArray *sectionsArray;
    NSMutableDictionary *sectionsDict;
    NSMutableDictionary *friendsArrayUids;
    NSMutableArray *friendsArray;
    NSNumber *friendsArrayUpdateTime;
    NSMutableArray *friendsArrayOnline;
    _Bool needImportant;
    _Bool loadingFriends;
    _Bool disableReloadData;
    _Bool _loadMutual;
    _Bool _disableGlobalSearch;
    NSNumber *_owner;
}

@property(nonatomic) _Bool disableGlobalSearch; // @synthesize disableGlobalSearch=_disableGlobalSearch;
@property(nonatomic) _Bool loadMutual; // @synthesize loadMutual=_loadMutual;
@property(retain, nonatomic) NSNumber *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)userOnlineStatusChanged:(id)arg1;
- (void)friendsDidDeleted:(id)arg1;
- (void)friendsDidLoaded:(id)arg1;
- (void)mutualFriendsDidLoaded:(id)arg1;
- (void)usersDidSearch:(id)arg1;
- (void)didFinishLoadingData;
- (void)reloadData;
- (void)updateSearchInArray:(id)arg1 withString:(id)arg2;
- (void)reloadOnlineFriends;
- (void)updateArrays;
- (void)checkData:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)initialize;

@end

