//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber;

@interface friends_delete_res : VKResponse
{
    NSNumber *_success;
    NSNumber *_friend_deleted;
    NSNumber *_out_request_deleted;
    NSNumber *_in_request_deleted;
    NSNumber *_suggestion_deleted;
}

@property(retain, nonatomic) NSNumber *suggestion_deleted; // @synthesize suggestion_deleted=_suggestion_deleted;
@property(retain, nonatomic) NSNumber *in_request_deleted; // @synthesize in_request_deleted=_in_request_deleted;
@property(retain, nonatomic) NSNumber *out_request_deleted; // @synthesize out_request_deleted=_out_request_deleted;
@property(retain, nonatomic) NSNumber *friend_deleted; // @synthesize friend_deleted=_friend_deleted;
@property(retain, nonatomic) NSNumber *success; // @synthesize success=_success;
- (void).cxx_destruct;

@end

