//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface friends_edit_req : VKRequest
{
    NSNumber *_user_id;
    NSString *_list_ids;
}

@property(copy, nonatomic) NSString *list_ids; // @synthesize list_ids=_list_ids;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

