//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BackupImageView, UIButton, UILabel, VKUser;

@interface FriendSuggestionCell : UITableViewCell
{
    BackupImageView *avatarImage;
    UIButton *addButton;
    UILabel *firstNameLabel;
    UILabel *secondNameLabel;
    VKUser *record;
}

@property(retain, nonatomic) VKUser *record; // @synthesize record;
@property(retain, nonatomic) UILabel *secondNameLabel; // @synthesize secondNameLabel;
@property(retain, nonatomic) UILabel *firstNameLabel; // @synthesize firstNameLabel;
@property(retain, nonatomic) UIButton *addButton; // @synthesize addButton;
@property(retain, nonatomic) BackupImageView *avatarImage; // @synthesize avatarImage;
- (void).cxx_destruct;
- (void)setFirstName:(id)arg1 andSecondName:(id)arg2;
- (id)reuseIdentifier;

@end

