//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationControllerStyled.h"

@class UIWindow;

@interface FullScreenNavController : UINavigationControllerStyled
{
    UIWindow *_parentWindow;
    double _returnWindowLevel;
}

@property(nonatomic) double returnWindowLevel; // @synthesize returnWindowLevel=_returnWindowLevel;
@property(nonatomic) __weak UIWindow *parentWindow; // @synthesize parentWindow=_parentWindow;
- (void).cxx_destruct;
- (void)dealloc;
- (void)willMoveToParentViewController:(id)arg1;
- (void)destroy:(_Bool)arg1;
- (void)destroy;
- (void)viewDidLoad;

@end

