//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface GraySeparatorView : UIView
{
    _Bool _vertical;
    _Bool _highlighted;
    UIColor *_drawColor;
    long long _offsetX;
    long long _offsetY;
    long long _offsetRight;
    long long _offsetBottom;
    long long _width;
}

@property(nonatomic, setter=setHighlighted:) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) long long width; // @synthesize width=_width;
@property(nonatomic) _Bool vertical; // @synthesize vertical=_vertical;
@property(nonatomic) long long offsetBottom; // @synthesize offsetBottom=_offsetBottom;
@property(nonatomic) long long offsetRight; // @synthesize offsetRight=_offsetRight;
@property(nonatomic) long long offsetY; // @synthesize offsetY=_offsetY;
@property(nonatomic) long long offsetX; // @synthesize offsetX=_offsetX;
@property(retain, nonatomic) UIColor *drawColor; // @synthesize drawColor=_drawColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setColor:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)prepare;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

