//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewControllerStyled.h"

#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSPredicate, NSString, UISearchBar, UISearchDisplayController;

@interface GroupsViewController : UITableViewControllerStyled <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate>
{
    NSString *guid;
    NSMutableArray *getGroupsArray;
    _Bool loading;
    _Bool endReached;
    NSMutableDictionary *getGroupDict;
    NSMutableArray *searchResults;
    _Bool _manageNavigationState;
    NSPredicate *_displayPredicate;
    id <GroupsViewControllerDelegate> _delegate;
    UISearchBar *_searchBar;
}

@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) id <GroupsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool manageNavigationState; // @synthesize manageNavigationState=_manageNavigationState;
@property(retain, nonatomic) NSPredicate *displayPredicate; // @synthesize displayPredicate=_displayPredicate;
- (void).cxx_destruct;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(long long)arg2;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (void)updateSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)refreshControlFiredEvent:(id)arg1;
- (void)groupsSearchResultsUpdated:(id)arg1;
- (void)groupsDidFinishLoading:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UISearchDisplayController *searchController; // @dynamic searchController;
@property(readonly) Class superclass;

@end

