//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iPadStandardCell.h"

@class BackupImageView, UILabel;

@interface GroupsViewCell : iPadStandardCell
{
    BackupImageView *_avatarImage;
    UILabel *_nameLabel;
}

@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) BackupImageView *avatarImage; // @synthesize avatarImage=_avatarImage;
- (void).cxx_destruct;
- (void)setGroup:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

