//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BackupImageView, UIImageView, UILabel, UIView;

@interface GroupListCell : UITableViewCell
{
    UIImageView *onlineImage;
    BackupImageView *avatarImage;
    UILabel *nameLabel;
    UIView *background;
}

@property(retain, nonatomic) UIView *background; // @synthesize background;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel;
@property(retain, nonatomic) BackupImageView *avatarImage; // @synthesize avatarImage;
@property(retain, nonatomic) UIImageView *onlineImage; // @synthesize onlineImage;
- (void).cxx_destruct;
- (void)setName:(id)arg1;
- (void)layoutSubviews;
- (id)reuseIdentifier;

@end

