//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, groups_search_req;

@interface GroupsController : NSObject
{
    double lastSearchTimeGroups;
    NSMutableDictionary *searchGroupsUids;
    CDUnknownBlockType groupsSearch;
    groups_search_req *search_req;
    _Bool searchingGroups;
    NSMutableArray *searchGroupsArray;
    long long totalGroupsSearchCount;
}

+ (id)sharedInstance;
@property(nonatomic) long long totalGroupsSearchCount; // @synthesize totalGroupsSearchCount;
@property(nonatomic) _Bool searchingGroups; // @synthesize searchingGroups;
@property(retain, nonatomic) NSMutableArray *searchGroupsArray; // @synthesize searchGroupsArray;
- (void).cxx_destruct;
- (void)addTopicCommentForTid:(id)arg1 andgroup_id:(id)arg2 withComment:(id)arg3 attachments:(id)arg4 fromGroup:(_Bool)arg5;
- (void)deleteTopicCommentForTid:(id)arg1 withCid:(id)arg2 andgroup_id:(id)arg3;
- (void)deleteGroupTopicFromgroup_id:(id)arg1 withTid:(id)arg2;
- (id)loadTopicCommentsForTid:(id)arg1 andGroupId:(id)arg2 withOffset:(id)arg3 andCount:(id)arg4 sort:(id)arg5;
- (id)addGroupTopicToGroupId:(id)arg1 withTopic:(id)arg2 andMessage:(id)arg3 fromGroup:(_Bool)arg4;
- (id)loadGroupTopicsForgroup_id:(id)arg1 withOffset:(id)arg2 andCount:(id)arg3;
- (id)loadGroupMemebersForgroup_id:(id)arg1 withOffset:(id)arg2 andCount:(id)arg3;
- (id)joinToGroupWithgroup_id:(id)arg1 notSure:(id)arg2;
- (id)leaveGroupWithgroup_id:(id)arg1;
- (id)loadGroupsForUid:(id)arg1 filter:(id)arg2;
- (id)searchGroups:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3 completeBlock:(CDUnknownBlockType)arg4;
- (void)cleanUp;
- (id)init;
- (void)dealloc;

@end

