//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface groups_isMember_req : VKRequest
{
    NSNumber *_user_id;
    NSString *_group_id;
    NSNumber *_extended;
}

@property(retain, nonatomic) NSNumber *extended; // @synthesize extended=_extended;
@property(copy, nonatomic) NSString *group_id; // @synthesize group_id=_group_id;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

