//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface HNKCache : NSObject
{
    NSMutableDictionary *_memoryCaches;
    NSMutableDictionary *_formats;
    NSString *_rootDirectory;
}

+ (id)sharedCache;
@property(readonly, nonatomic) NSString *rootDirectory; // @synthesize rootDirectory=_rootDirectory;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)updateAccessDateOfImage:(id)arg1 key:(id)arg2 format:(id)arg3;
- (id)outputStreamForKey:(id)arg1 formatName:(id)arg2;
- (void)saveData:(id)arg1 key:(id)arg2 formatName:(id)arg3;
- (id)pathForKey:(id)arg1 formatName:(id)arg2;
- (void)saveImage:(id)arg1 key:(id)arg2 format:(id)arg3;
- (void)removeFileAtPath:(id)arg1 format:(id)arg2;
- (void)preloadImagesOfFormat:(id)arg1;
- (void)controlDiskCapacityOfFormat:(id)arg1;
- (_Bool)planCapacityControl:(id)arg1;
- (void)calculateDiskSizeOfFormat:(id)arg1;
- (void)setMemoryImage:(id)arg1 forKey:(id)arg2 format:(id)arg3;
- (id)memoryImageForKey:(id)arg1 format:(id)arg2;
- (id)imageFromOriginal:(id)arg1 key:(id)arg2 format:(id)arg3;
- (id)imageFromEntity:(id)arg1 error:(id *)arg2;
- (id)pathForKey:(id)arg1 format:(id)arg2;
- (id)keyFromPath:(id)arg1;
- (void)removeImagesOfEntity:(id)arg1;
- (void)clearFormatNamed:(id)arg1;
- (void)setImage:(id)arg1 forKey:(id)arg2 formatName:(id)arg3 memoryOnly:(_Bool)arg4 diskOnly:(_Bool)arg5;
- (void)setImage:(id)arg1 forKey:(id)arg2 formatName:(id)arg3 memoryOnly:(_Bool)arg4;
- (void)setImage:(id)arg1 forKey:(id)arg2 formatName:(id)arg3;
- (id)retrieveImageForKey:(id)arg1 formatName:(id)arg2 completionBlock:(CDUnknownBlockType)arg3 diskLoadBlock:(CDUnknownBlockType)arg4;
- (id)diskDataForKey:(id)arg1 formatName:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)memoryImageForKey:(id)arg1 formatName:(id)arg2;
@property(readonly, nonatomic) NSDictionary *formats;
- (void)registerFormat:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

