//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AbstractSectionDataSourceWithTitle.h"

@class NSArray, groups_getInvites_res;

@interface InvitesContentDataSource : AbstractSectionDataSourceWithTitle
{
    groups_getInvites_res *_invites;
    groups_getInvites_res *_allInvites;
    NSArray *_groupsArray;
}

@property(retain, nonatomic) NSArray *groupsArray; // @synthesize groupsArray=_groupsArray;
@property(retain, nonatomic) groups_getInvites_res *allInvites; // @synthesize allInvites=_allInvites;
@property(retain, nonatomic) groups_getInvites_res *invites; // @synthesize invites=_invites;
- (void).cxx_destruct;
- (void)collapseExpand:(id)arg1;
- (id)cellForRow:(long long)arg1;
- (double)heightForRow:(long long)arg1;
- (unsigned long long)numberOfRowsInSection;
- (id)collapseText;
- (_Bool)expandable;
- (id)titleForSection;
- (id)init;

@end

