//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "AttachManagerDelegate.h"
#import "AudioViewDelegate.h"
#import "CLLocationManagerDelegate.h"
#import "DocsViewControllerDelegate.h"
#import "MKMapViewDelegate.h"
#import "ModalContainerDelegate.h"
#import "PhotosViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"
#import "VideoViewDelegate.h"

@class AttachManager, CLLocationManager, MKMapView, ModalContainerViewController, NSString, UIActionSheet, UIActivityIndicatorView, UIAlertView, UIBarButtonItem, UIButton, UIImageView, UIPopoverController, UISwitch, UITableView, UITextViewAttach, UIViewController, VKGeo, VKGroup, VKPost, VKPostSettings, VKUser;

@interface iPadNewWallPostViewController : UIViewControllerStyled <UINavigationControllerDelegate, PhotosViewDelegate, AudioViewDelegate, VideoViewDelegate, UIActionSheetDelegate, MKMapViewDelegate, UITextViewDelegate, UIAlertViewDelegate, UIPopoverControllerDelegate, DocsViewControllerDelegate, AttachManagerDelegate, UITableViewDataSource, UITableViewDelegate, ModalContainerDelegate, CLLocationManagerDelegate, UIImagePickerControllerDelegate>
{
    VKGeo *postGeolocation;
    UIActionSheet *photoSheet;
    UIActionSheet *plusSheet;
    _Bool sendAfterUpload;
    UIAlertView *cancelAlert;
    _Bool ignoreKeyboard;
    _Bool preventReopenOnAppear;
    AttachManager *attachManager;
    VKPost *parentPost;
    CLLocationManager *_locationManager;
    _Bool shouldRestoreKeyboard;
    UIPopoverController *popover;
    VKUser *_ownerUser;
    VKGroup *_ownerGroup;
    UIButton *_closeButton;
    UIBarButtonItem *_sendButton;
    UITextViewAttach *_textView;
    UIImageView *_bottomView;
    UIButton *_photoButton;
    UIButton *_attachButton;
    UIButton *_locationButton;
    UIButton *_settingsButton;
    MKMapView *_locationMap;
    UISwitch *_locationSwitch;
    UIViewController *_locationController;
    UITableView *_settingsTable;
    UIViewController *_settingsController;
    UIActivityIndicatorView *_messageFieldLoadingIndicator;
    VKPostSettings *_postSettings;
}

@property(retain, nonatomic) VKPostSettings *postSettings; // @synthesize postSettings=_postSettings;
@property(retain, nonatomic) UIActivityIndicatorView *messageFieldLoadingIndicator; // @synthesize messageFieldLoadingIndicator=_messageFieldLoadingIndicator;
@property(retain, nonatomic) UIViewController *settingsController; // @synthesize settingsController=_settingsController;
@property(retain, nonatomic) UITableView *settingsTable; // @synthesize settingsTable=_settingsTable;
@property(retain, nonatomic) UIViewController *locationController; // @synthesize locationController=_locationController;
@property(retain, nonatomic) UISwitch *locationSwitch; // @synthesize locationSwitch=_locationSwitch;
@property(retain, nonatomic) MKMapView *locationMap; // @synthesize locationMap=_locationMap;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *locationButton; // @synthesize locationButton=_locationButton;
@property(retain, nonatomic) UIButton *attachButton; // @synthesize attachButton=_attachButton;
@property(retain, nonatomic) UIButton *photoButton; // @synthesize photoButton=_photoButton;
@property(retain, nonatomic) UIImageView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UITextViewAttach *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIBarButtonItem *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) VKGroup *ownerGroup; // @synthesize ownerGroup=_ownerGroup;
@property(retain, nonatomic) VKUser *ownerUser; // @synthesize ownerUser=_ownerUser;
- (void).cxx_destruct;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardDidHidden:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)willResignFirstResponder;
- (void)didSelectDoc:(id)arg1;
- (void)didSelectPhoto:(id)arg1;
- (void)videoView:(id)arg1 didSelectVideo:(id)arg2;
- (void)didSelectAudio:(id)arg1 controlPopover:(_Bool)arg2;
- (void)attachmentsWillDeleteAttach:(id)arg1;
- (void)attachmentsWillUpdateAttachScroll;
- (void)attachmentsDidUploaded;
- (void)attachmentsCountDidChanged;
- (void)attachmentsWillCloseAlert;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)mapButtonClick:(id)arg1;
- (void)switchPostLocation:(id)arg1;
- (void)settingsButtonClick:(id)arg1;
- (void)plusButtonClick:(id)arg1;
- (void)photoButtonClick:(id)arg1;
- (void)sendButtonPressed:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
- (void)switchChange:(id)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)mapSwitcherChanged:(id)arg1;
- (void)configLocationButton:(_Bool)arg1;
- (void)willPresentActionSheet:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)sendMessage;
- (void)doOnAppear;
- (void)viewWillAppear:(_Bool)arg1;
- (void)finishRotation;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (_Bool)resignFirstResponder;
- (void)willChangeOrientation:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (_Bool)sendButtonDisabled;
- (void)loadView;
- (struct CGSize)preferredContentSize;
- (void)modalContainerCloseTapPerformed:(id)arg1;
- (void)closeWindow;
- (void)showSelfInWindow;
- (id)initWithPost:(id)arg1;
- (id)init;

// Remaining properties
@property(nonatomic) __weak ModalContainerViewController *container; // @dynamic container;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

