//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "AttachManagerDelegate.h"
#import "AttachTextViewDelegate.h"
#import "AudioViewDelegate.h"
#import "CommentFieldDelegate.h"
#import "DocsViewControllerDelegate.h"
#import "PhotosViewDelegate.h"
#import "SmilesViewDelegate.h"
#import "StickersShopControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "VideoViewDelegate.h"

@class AttachManager, CommentFieldView, NSIndexPath, NSMutableArray, NSMutableDictionary, NSNumber, NSString, ObservingInputAccessoryView, PullToRefreshView, SmilesViewController, UIActionSheet, UIBarButtonItem, UIButton, UINoDataLoadingView, UIPopoverController, UITableView, UIViewController, VKComment, VKGroup, VKTopic;

@interface iPadTopicCommentsViewController : UIViewControllerStyled <UITableViewDataSource, UITableViewDelegate, AttachManagerDelegate, UIActionSheetDelegate, AttachTextViewDelegate, AudioViewDelegate, VideoViewDelegate, PhotosViewDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, DocsViewControllerDelegate, UIAlertViewDelegate, CommentFieldDelegate, SmilesViewDelegate, StickersShopControllerDelegate>
{
    NSString *guid;
    _Bool ignoreKeyboard;
    _Bool restoreKeyboard;
    _Bool ignoreAllExceptAnimation;
    float currentHeight;
    _Bool loading;
    _Bool endReached;
    NSMutableDictionary *commentCids;
    NSMutableArray *comments;
    long long totalCommentsCount;
    NSNumber *replyTyUid;
    NSNumber *replyToCid;
    NSNumber *replyToOwnerUid;
    VKComment *selectedComment;
    float keyboardH;
    NSIndexPath *selectedRow;
    _Bool sendAfterUpload;
    UIActionSheet *attachSheet;
    _Bool representAttachSheet;
    _Bool representExportSheet;
    UIActionSheet *commentActionSheet;
    UIActionSheet *exportSheet;
    AttachManager *attachManager;
    _Bool postFromGroup;
    UIPopoverController *popover;
    id <TopicCommentsViewControllerDelegate> _delegate;
    PullToRefreshView *_pullToRefreshView;
    VKTopic *_topic;
    UITableView *_table;
    VKGroup *_group;
    UIButton *_backButton;
    UIBarButtonItem *_exportButton;
    UINoDataLoadingView *_noDataView;
    UITableView *_settingsTable;
    UIViewController *_settingsController;
    CommentFieldView *_commentField;
    SmilesViewController *_smilesViewController;
    ObservingInputAccessoryView *_observer;
}

@property(retain, nonatomic) ObservingInputAccessoryView *observer; // @synthesize observer=_observer;
@property(retain, nonatomic) SmilesViewController *smilesViewController; // @synthesize smilesViewController=_smilesViewController;
@property(retain, nonatomic) CommentFieldView *commentField; // @synthesize commentField=_commentField;
@property(retain, nonatomic) UIViewController *settingsController; // @synthesize settingsController=_settingsController;
@property(retain, nonatomic) UITableView *settingsTable; // @synthesize settingsTable=_settingsTable;
@property(retain, nonatomic) UINoDataLoadingView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UIBarButtonItem *exportButton; // @synthesize exportButton=_exportButton;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) VKGroup *group; // @synthesize group=_group;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) VKTopic *topic; // @synthesize topic=_topic;
@property(retain, nonatomic) PullToRefreshView *pullToRefreshView; // @synthesize pullToRefreshView=_pullToRefreshView;
@property(nonatomic) id <TopicCommentsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)disablesAutomaticKeyboardDismissal;
- (id)collectionControllerRootWindow:(id)arg1;
- (void)collectionControllerShouldBecomeFirstResponder:(id)arg1;
- (void)stickersShopDidHide:(id)arg1;
- (void)collectionControllerShouldOpenStickersShop:(id)arg1;
- (void)collectionControllerShowSystemKeyboard:(id)arg1;
- (void)collectionControllerBackspace:(id)arg1;
- (_Bool)collectionControllerShouldHide:(id)arg1;
- (void)smileButtonPressed:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)willResignFirstResponder;
- (void)didSelectDoc:(id)arg1;
- (void)didSelectPhoto:(id)arg1;
- (void)videoView:(id)arg1 didSelectVideo:(id)arg2;
- (void)didSelectAudio:(id)arg1 controlPopover:(_Bool)arg2;
- (void)keyboardDidHidden:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)didResignFirstResponder;
- (void)updateKeyboardWithNotification:(id)arg1;
- (void)attachTextViewDidBeginEditing:(id)arg1;
- (void)attachTextView:(id)arg1 willChangeHeight:(float)arg2;
- (void)attachTextViewDidChange:(id)arg1;
- (_Bool)attachTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)attachmentsWillUpdateAttachScroll;
- (void)attachmentsDidUploaded;
- (void)attachmentsCountDidChanged;
- (_Bool)sendButtonEnabled;
- (void)processButton:(id)arg1;
- (void)exportButtonPressed:(id)arg1;
- (void)attachButtonPressed:(id)arg1;
- (void)sendButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)switchChange:(id)arg1;
- (_Bool)canShowSettingsButton;
- (void)settingsButtonPressed:(id)arg1;
- (void)openLikesForComment:(id)arg1;
- (void)likeTapComment:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)processCommentActionSheet:(id)arg1 resultWithActions:(id)arg2 forButtonIndex:(long long)arg3;
- (void)finishMenu;
- (void)destroyCommentsActionSheet;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (_Bool)scrollViewCanPerformRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)didEditComment:(id)arg1;
- (void)topicCommentsDidLoaded:(id)arg1;
- (void)topicCommentDidAdded:(id)arg1;
- (void)processAttachButton:(id)arg1;
- (void)presentAttachSheet;
- (void)insertComment:(id)arg1;
- (void)sendMessage;
- (void)collectionController:(id)arg1 didSelectObject:(id)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)doOnAppear;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)updateInterfaceForKeyboardSize:(double)arg1 keepContentOffset:(_Bool)arg2;
- (void)updateInterfaceForOrientation:(long long)arg1;
- (void)collapseInputView:(id)arg1;
- (void)tap:(id)arg1;
- (void)dealloc;
- (void)configClosed;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithTopic:(id)arg1 group:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

