//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iPadWallViewCell2.h"

@interface iPadNewsfeedCommentsCell : iPadWallViewCell2
{
}

- (struct UIEdgeInsets)layoutMargins;
- (_Bool)callPostReuse;
- (void)setPost:(id)arg1;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

