//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "NewStatusViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "iPadCommentsViewControllerDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, NSString, UIActionSheet, UIButton, UIImage, UINoDataLoadingView, UITableView, UITableViewCell, UITableViewFixed, UIView, VKAudios, VKGroup, VKMixedUsersGroups, VKPhotoAlbums, VKPhotos, VKPost, VKTopics, VKUser, VKUsers, VKVideos, WallPostButtonsCell;

@interface iPadWallViewController : UIViewControllerStyled <UITableViewDataSource, UITableViewDelegate, UIActionSheetDelegate, iPadCommentsViewControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, NewStatusViewControllerDelegate>
{
    NSString *guid;
    UIActionSheet *photoSheet;
    WallPostButtonsCell *buttonsCell;
    long long avatarSection;
    long long buttonsSections;
    long long menuSection;
    long long mutualSection;
    long long friendsSection;
    long long pagesSection;
    long long albumsSection;
    long long videosSection;
    long long audiosSection;
    long long topicsSection;
    long long linksSection;
    long long contactsSection;
    long long totalSections;
    VKPost *pinnedPost;
    long long menuPhotoRow;
    long long menuVideoRow;
    long long menuFollowersRow;
    long long menuGroupsRow;
    long long menuDocumentsRow;
    long long menuTotalRowCount;
    _Bool infoExpanded;
    long long photosRow;
    long long wallPostRow;
    long long wallTypeRow;
    long long wallFixedPostRow;
    long long wallBanInfoRow;
    long long profileRowCount;
    long long infoRowCount;
    long long familyRow;
    long long educationRow;
    long long lifePositionRow;
    long long privateRow;
    long long userContactsRow;
    _Bool updating;
    _Bool loaded;
    _Bool updated;
    _Bool banned;
    _Bool ignoreScroll;
    UIActionSheet *shareSheet;
    UIActionSheet *friendSheet;
    VKUsers *friendsArray;
    VKUsers *mutualFriendsArray;
    VKMixedUsersGroups *pages;
    VKTopics *topics;
    VKPhotoAlbums *albums;
    VKVideos *videos;
    VKAudios *audios;
    NSMutableArray *schools;
    NSMutableArray *universities;
    NSMutableArray *profileFields;
    NSMutableArray *familyFields;
    NSMutableArray *educationFields;
    NSMutableArray *lifePositionFields;
    NSMutableArray *privateFields;
    NSMutableArray *contactsFields;
    _Bool loading;
    _Bool endReached;
    NSMutableDictionary *wallPostsPids;
    NSMutableArray *wallPosts;
    NSNumber *wallPostsUpdateTime;
    long long totalWallPostsCount;
    _Bool loadingOnly;
    _Bool endReachedOnly;
    NSMutableDictionary *wallPostsPidsOnly;
    NSMutableArray *wallPostsOnly;
    long long totalWallPostsOnlyCount;
    VKPhotos *getPhotosArray;
    NSMutableDictionary *getPhotosDict;
    _Bool loadingPhotos;
    long long totalPhotosCount;
    _Bool endReachedPhotos;
    _Bool ignoreHeight;
    float height1;
    float height2;
    long long currentWallType;
    double defaultTopInset;
    _Bool newsTableIsExpanded;
    _Bool foundAvatarHeight;
    _Bool viewIsDissappear;
    UITableViewCell *pagesCell;
    UITableViewCell *topicsCell;
    UITableViewCell *albumsCell;
    UITableViewCell *videosCell;
    UITableViewCell *audiosCell;
    NSMutableArray *postCells;
    NSMutableArray *linksCells;
    UIImage *wallTypeSelectorImage;
    _Bool draggedNow;
    _Bool representShareSheet;
    _Bool representPhotoSheet;
    _Bool representFriendSheet;
    VKUser *_ownerUser;
    VKGroup *_ownerGroup;
    UITableViewFixed *_leftTable;
    UITableViewFixed *_rightTable;
    UIButton *_backButton;
    UIButton *_shareButton;
    UITableView *_photosScroll;
    UIView *_photosScrollParent;
    UINoDataLoadingView *_noDataView;
    double _realAvatarHeight;
}

@property(nonatomic) double realAvatarHeight; // @synthesize realAvatarHeight=_realAvatarHeight;
@property(retain, nonatomic) UINoDataLoadingView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UIView *photosScrollParent; // @synthesize photosScrollParent=_photosScrollParent;
@property(retain, nonatomic) UITableView *photosScroll; // @synthesize photosScroll=_photosScroll;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UITableViewFixed *rightTable; // @synthesize rightTable=_rightTable;
@property(retain, nonatomic) UITableViewFixed *leftTable; // @synthesize leftTable=_leftTable;
@property(retain, nonatomic) VKGroup *ownerGroup; // @synthesize ownerGroup=_ownerGroup;
@property(retain, nonatomic) VKUser *ownerUser; // @synthesize ownerUser=_ownerUser;
- (void).cxx_destruct;
- (void)checkIfUserUpdatedPhoto:(id)arg1;
- (void)wallCommentsCountChanged:(id)arg1;
- (void)wallPostPerformDeleteFromWall:(id)arg1;
- (void)shouldUnpinPostNotification:(id)arg1;
- (void)shouldPinPostNotification:(id)arg1;
- (void)makePinRequest:(id)arg1 withPost:(id)arg2;
- (void)doPostUnpining;
- (void)clearWall;
- (void)newStatusEntered:(id)arg1;
- (void)wallPostWillDismiss;
- (void)postDidSended:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)postCommentCountDidChanged:(id)arg1;
- (void)postLikeCountDidChanged:(id)arg1;
- (void)imageSelectClick:(id)arg1;
- (void)avatarTap:(id)arg1;
- (void)bigAvatarTap:(id)arg1;
- (void)statusTap:(id)arg1;
- (void)newMessageButtonPressed:(id)arg1;
- (void)newMessagePhotoButtonPressed:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)menuButtonPressed:(id)arg1;
- (void)shareButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)videoTap:(id)arg1;
- (void)albumTap:(id)arg1;
- (void)expandButtonPressed:(id)arg1;
- (void)topicButtonPressed:(id)arg1;
- (void)linkButtonPressed:(id)arg1;
- (void)wallTypeSelectPressed:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)startLoadingWall;
- (void)rebuildMainAvatarImage:(id)arg1 placeholder:(id)arg2;
- (id)createHeaderCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)emptyContentCell:(id)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)getFreeLinksCell;
- (id)getFreePostCell;
- (id)createNewLinkCell;
- (void)prepareTableCells;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)checkTableState;
- (void)refreshControlFiredEvent:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)userBecomeOffline:(id)arg1;
- (void)userBecomeOnline:(id)arg1;
- (void)didReportPost:(id)arg1;
- (void)didEditPost:(id)arg1;
- (void)wallDidLoaded:(id)arg1;
- (void)photosAllDidFinishLoadingWithStatus:(id)arg1;
- (void)mainAlbumLoaded:(id)arg1;
- (void)processMainWallPhotos:(id)arg1 offset:(long long)arg2;
- (void)buildRightWallTopSections;
- (void)wallPostAdded:(id)arg1;
- (void)wallPostPerformAdd:(id)arg1;
- (void)fillEmptyAlbumCell:(id)arg1 tableView:(id)arg2 indexPath:(id)arg3 headerTitle:(id)arg4 cellImage:(id)arg5 labelText:(id)arg6 action:(SEL)arg7;
- (id)titleUserCell:(id)arg1;
- (void)reloadTables;
- (void)loadUser:(id)arg1;
- (void)endRefreshing;
- (void)loadGroup:(id)arg1;
- (void)setGroup:(id)arg1;
- (void)clearSections;
- (void)setUser:(id)arg1;
- (void)resetOwner;
- (void)showFriendSheet;
- (void)cleanupViewsArray:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)destroySheets;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dropInsets;
- (void)setTablesScrollInset;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

