//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UIView;

@interface iPadCacheSwitch : UIControl
{
    _Bool _isOn;
    UIImageView *_onImage;
    UIImageView *_offImage;
    UIImageView *_slideImage;
    UIImageView *_borderImage;
    UIView *_clipView;
}

@property(retain, nonatomic) UIView *clipView; // @synthesize clipView=_clipView;
@property(retain, nonatomic) UIImageView *borderImage; // @synthesize borderImage=_borderImage;
@property(retain, nonatomic) UIImageView *slideImage; // @synthesize slideImage=_slideImage;
@property(retain, nonatomic) UIImageView *offImage; // @synthesize offImage=_offImage;
@property(retain, nonatomic) UIImageView *onImage; // @synthesize onImage=_onImage;
@property(nonatomic) _Bool isOn; // @synthesize isOn=_isOn;
- (void).cxx_destruct;
- (struct CGPath *)newMaskPathWithFrame:(struct CGRect)arg1;
- (void)updateImagesPosition;
- (void)swipeHandle:(id)arg1;
- (void)tapHandle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

