//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

@class UISegmentedControl, UIToolbar, iPadFriendRequestsController;

@interface iPadFriendRequestsSelector : UIViewControllerStyled
{
    iPadFriendRequestsController *requests;
    iPadFriendRequestsController *suggested;
    UIToolbar *bottomToolbar;
    UISegmentedControl *segmented;
}

- (void).cxx_destruct;
- (void)segmentedChanged:(id)arg1;
- (void)loadView;

@end

