//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iPadWallViewCell2.h"

#import "PostMenuControllerDelegate.h"

@class NSString;

@interface iPadFullPostViewCell : iPadWallViewCell2 <PostMenuControllerDelegate>
{
}

- (id)menuControllerPopoverOwner:(id)arg1;
- (void)closeDetailPost:(id)arg1;
- (void)menuController:(id)arg1 editPost:(id)arg2;
- (void)menuController:(id)arg1 shouldDeletePost:(id)arg2;
- (void)menuController:(id)arg1 shouldClosePost:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <iPadFullPostViewCellDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

