//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "GroupsContentDataSourceDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GlobalSearchDataSource, NSMutableArray, NSMutableDictionary, NSNumber, NSString, UIButton, UIImageView, UILabel, UINoDataLoadingView, UISearchBar, UISearchDisplayControllerNoHide, UISegmentedControl, UITableView, UIView, groups_getInvites_res;

@interface iPadGroupsViewController : UIViewControllerStyled <UITableViewDelegate, UITableViewDataSource, UISearchDisplayDelegate, UISearchBarDelegate, GroupsContentDataSourceDelegate, UIActionSheetDelegate>
{
    NSString *guid;
    NSMutableArray *tableDataSources;
    NSMutableArray *searchDataSources;
    GlobalSearchDataSource *globalSearchSection;
    NSMutableArray *getGroupsArray;
    groups_getInvites_res *invitesResponse;
    NSMutableArray *getEventsArray;
    NSMutableArray *getEventsPastArray;
    NSMutableArray *getAdminGroupsArray;
    NSMutableDictionary *adminSuggestions;
    _Bool loading;
    _Bool loadingAdmin;
    _Bool endReached;
    NSMutableDictionary *getGroupDict;
    NSMutableArray *searchResults;
    NSNumber *ownerId;
    unsigned long long currentSection;
    UITableView *_table;
    UISearchBar *_searchBar;
    UIButton *_backButton;
    UISegmentedControl *_adminSegmeng;
    UIView *_adminSegmengView;
    UIImageView *_notifyImage;
    UILabel *_notifyCountLabel;
    UINoDataLoadingView *_noDataView;
}

@property(retain, nonatomic) UINoDataLoadingView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UILabel *notifyCountLabel; // @synthesize notifyCountLabel=_notifyCountLabel;
@property(retain, nonatomic) UIImageView *notifyImage; // @synthesize notifyImage=_notifyImage;
@property(retain, nonatomic) UIView *adminSegmengView; // @synthesize adminSegmengView=_adminSegmengView;
@property(retain, nonatomic) UISegmentedControl *adminSegmeng; // @synthesize adminSegmeng=_adminSegmeng;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
- (void).cxx_destruct;
- (_Bool)updateSearchDataSources;
- (void)updateDataSources;
- (id)groupsSectionsSuggestionsForId:(id)arg1;
- (void)tableSection:(id)arg1 selectorClicked:(id)arg2;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(long long)arg2;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)updateSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)userLeftGroup:(id)arg1;
- (void)groupsSearchResultsUpdated:(id)arg1;
- (void)groupsDidFinishLoading:(id)arg1;
- (void)refreshControlFiredEvent:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)updateNotifyCount;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)resignFirstResponder;
- (_Bool)searchActive;
- (void)loadView;
- (void)dealloc;
- (id)initWithOwnerId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UISearchDisplayControllerNoHide *searchController; // @dynamic searchController;
@property(readonly) Class superclass;

@end

