//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iPadStandardCell.h"

@class BackupImageView, UIButtonHL, UIImageView, UILabel;

@interface iPadTopicViewCell : iPadStandardCell
{
    UIImageView *_backgroundImage;
    UILabel *_titleLabel;
    UILabel *_countLabel;
    UILabel *_countTitleLabel;
    UIButtonHL *_avatarButton;
    BackupImageView *_avatarImage;
    UILabel *_nameLabel;
    UIImageView *_lockImage;
    UIImageView *_pinImage;
    UILabel *_timeLabel;
    long long _position;
}

@property(nonatomic) long long position; // @synthesize position=_position;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *pinImage; // @synthesize pinImage=_pinImage;
@property(retain, nonatomic) UIImageView *lockImage; // @synthesize lockImage=_lockImage;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) BackupImageView *avatarImage; // @synthesize avatarImage=_avatarImage;
@property(retain, nonatomic) UIButtonHL *avatarButton; // @synthesize avatarButton=_avatarButton;
@property(retain, nonatomic) UILabel *countTitleLabel; // @synthesize countTitleLabel=_countTitleLabel;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
- (void).cxx_destruct;
- (void)avatarButtonPressed:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)setTopic:(id)arg1 atPos:(long long)arg2 inGroup:(id)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

