//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ProfilePhotoVideoView, VKAlbum;

@interface iPadAlbumViewCell : UITableViewCell
{
    ProfilePhotoVideoView *videoButtons[3];
    VKAlbum *videos[3];
    _Bool _isAdmin;
}

@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
- (void).cxx_destruct;
- (void)removePress:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)videoButtonPressed:(id)arg1;
- (void)setVideoAlbum:(id)arg1 atIndex:(long long)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

