//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UITouch;

@interface iPadAudioViewSlider : UIControl
{
    UITouch *movingTouch;
    float movingDX;
    _Bool _continuous;
    float _value;
    UIImageView *_background;
    UIImageView *_progressBackground;
    UIImageView *_knobProgressBackground;
    UIImageView *_knobImage;
}

@property(nonatomic) _Bool continuous; // @synthesize continuous=_continuous;
@property(nonatomic) float value; // @synthesize value=_value;
@property(retain, nonatomic) UIImageView *knobImage; // @synthesize knobImage=_knobImage;
@property(retain, nonatomic) UIImageView *knobProgressBackground; // @synthesize knobProgressBackground=_knobProgressBackground;
@property(retain, nonatomic) UIImageView *progressBackground; // @synthesize progressBackground=_progressBackground;
@property(retain, nonatomic) UIImageView *background; // @synthesize background=_background;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isDragging;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateForX:(double)arg1;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateKnobPosition;
- (void)layoutSubviews;
- (void)prepare:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

