//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iPadBaseNewsViewController.h"

#import "NewsfeedListsControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "iPadCommentsViewControllerDelegate.h"

@class NSArray, NSMutableArray, NSString, TimerListener, UIActivityIndicatorView, UIButton, UIButtonSelfHL, VKRequest;

@interface iPadNewsViewController : iPadBaseNewsViewController <UITableViewDataSource, UITableViewDelegate, iPadCommentsViewControllerDelegate, UIActionSheetDelegate, NewsfeedListsControllerDelegate>
{
    long long currentNewsfeed;
    NSMutableArray *newsfeedInfos;
    NSArray *preparedNewsCells;
    VKRequest *initialLoadRequest;
    UIButton *_messageButton;
    UIButtonSelfHL *_updateNewsButton;
    UIActivityIndicatorView *_updateIndicator;
    TimerListener *_timerListener;
}

@property(retain, nonatomic) TimerListener *timerListener; // @synthesize timerListener=_timerListener;
@property(retain, nonatomic) UIActivityIndicatorView *updateIndicator; // @synthesize updateIndicator=_updateIndicator;
@property(retain, nonatomic) UIButtonSelfHL *updateNewsButton; // @synthesize updateNewsButton=_updateNewsButton;
@property(retain, nonatomic) UIButton *messageButton; // @synthesize messageButton=_messageButton;
- (void).cxx_destruct;
- (id)newsfeedsItems;
- (void)sourcesWereBanned:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)wallCommentsCountChanged:(id)arg1;
- (void)setCurrentFeed:(long long)arg1;
- (void)setCurrentFeedTitle;
- (void)newsfeedListsControllerDidSelectFeedIndex:(long long)arg1;
- (void)showListsPicker:(id)arg1;
- (void)postCommentCountDidChanged:(id)arg1;
- (void)postLikeCountDidChanged:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)getPostFreeCell;
- (void)prepareNewsCells;
- (id)createNewCell;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)newMessageButtonPressed:(id)arg1;
- (id)findExistingPostFor:(id)arg1;
- (void)didReportPost:(id)arg1;
- (void)didEditPost:(id)arg1;
- (void)wallPostPerformAdd:(id)arg1;
- (void)wallPostPerformDeleteFromWall:(id)arg1;
- (void)refreshControlFiredEvent:(id)arg1;
- (void)updateButtonFired:(_Bool)arg1;
- (void)updateButtonFired;
- (void)updateTable:(id)arg1;
- (void)processNewsfeed:(id)arg1 loadedRequest:(id)arg2 newItems:(id)arg3;
- (id)loadCountWithFeed:(id)arg1 startTime:(id)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (id)loadNewsFeed:(id)arg1 from:(id)arg2 count:(id)arg3 startTime:(id)arg4;
- (id)loadNewsFeed:(id)arg1 from:(id)arg2 count:(id)arg3;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)scrollToTopAndStartRefresh;
- (void)updateNewPostsButton;
- (id)freshNewsAttributedTitle:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)checkNoDataView;
- (void)checkData:(id)arg1;
- (void)updateNews:(_Bool)arg1;
- (void)updateNews;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)loadUserLists;
- (void)removePostAnimated:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

