//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "CodeValidationControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class GraySeparatorView, NSString, UIButton, UIImageView, UITextField, UIView;

@interface iPadLoginViewController : UIViewControllerStyled <UITextFieldDelegate, CodeValidationControllerDelegate>
{
    _Bool keyboardShowed;
    _Bool ignoreKeyboard;
    double keyboardH;
    long long _openChat;
    UIButton *_LoginButton;
    UIButton *_facebookButton;
    UIButton *_RegisterButton;
    UIButton *_ForgotButton;
    UIButton *_RulesButton;
    UITextField *_LoginField;
    UITextField *_PasswordField;
    UIImageView *_LogoImage;
    UIImageView *_LoginFields;
    UIView *_LoginView;
    GraySeparatorView *_graySeparator;
}

@property(retain, nonatomic) GraySeparatorView *graySeparator; // @synthesize graySeparator=_graySeparator;
@property(retain, nonatomic) UIView *LoginView; // @synthesize LoginView=_LoginView;
@property(retain, nonatomic) UIImageView *LoginFields; // @synthesize LoginFields=_LoginFields;
@property(retain, nonatomic) UIImageView *LogoImage; // @synthesize LogoImage=_LogoImage;
@property(retain, nonatomic) UITextField *PasswordField; // @synthesize PasswordField=_PasswordField;
@property(retain, nonatomic) UITextField *LoginField; // @synthesize LoginField=_LoginField;
@property(retain, nonatomic) UIButton *RulesButton; // @synthesize RulesButton=_RulesButton;
@property(retain, nonatomic) UIButton *ForgotButton; // @synthesize ForgotButton=_ForgotButton;
@property(retain, nonatomic) UIButton *RegisterButton; // @synthesize RegisterButton=_RegisterButton;
@property(retain, nonatomic) UIButton *facebookButton; // @synthesize facebookButton=_facebookButton;
@property(retain, nonatomic) UIButton *LoginButton; // @synthesize LoginButton=_LoginButton;
@property(nonatomic) long long openChat; // @synthesize openChat=_openChat;
- (void).cxx_destruct;
- (void)keyboardChangeFrame:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)presentCodeValidationController:(id)arg1;
- (void)processAuthorizationResponse:(id)arg1;
- (void)facebookSessionOpened:(id)arg1;
- (void)facebookLogin:(id)arg1;
- (void)codeValidationSucceedWithResult:(id)arg1;
- (void)LoginButtonPressed:(id)arg1;
- (void)TermsOfService:(id)arg1;
- (void)RegisterButtonPressed:(id)arg1;
- (void)ForgotButtonPressed:(id)arg1;
- (void)processLoginParams:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)centerViewInSize:(struct CGSize)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

