//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "TopicCommentsViewControllerDelegate.h"
#import "TopicCreateViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSIndexPath, NSMutableArray, NSMutableDictionary, NSString, UIBarButtonItem, UIButton, UINoDataLoadingView, UITableView, VKGroup;

@interface iPadGroupTopicsViewController : UIViewControllerStyled <UITableViewDelegate, UITableViewDataSource, TopicCreateViewControllerDelegate, TopicCommentsViewControllerDelegate>
{
    NSString *guid;
    NSMutableArray *getGroupsArray;
    _Bool loading;
    _Bool endReached;
    long long totalGroupCount;
    NSMutableDictionary *getGroupDict;
    NSIndexPath *selectedRow;
    _Bool createTopic;
    VKGroup *_group;
    UIBarButtonItem *_plusButton;
    UITableView *_table;
    UIButton *_backButton;
    UINoDataLoadingView *_noDataView;
}

@property(retain, nonatomic) UINoDataLoadingView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) UIBarButtonItem *plusButton; // @synthesize plusButton=_plusButton;
@property(retain, nonatomic) VKGroup *group; // @synthesize group=_group;
- (void).cxx_destruct;
- (void)plusButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)topicDidCreated:(id)arg1;
- (void)topicNeedDelete:(id)arg1;
- (void)topicCommentCountDidChanged:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)refreshControlFiredEvent:(id)arg1;
- (void)groupTopicsDidFinishLoading:(id)arg1;
- (void)deleteTopic:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithGroup:(id)arg1 createTopic:(_Bool)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

