//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "BufferedNavigationControllerDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "SettingsViewDelegate.h"
#import "UIBarPositioningDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIPopoverControllerDelegate.h"

@class AnyCounter, BufferedNavigationController, DirectionPanGestureRecognizer, MessagesContainerViewController, NSMutableArray, NSString, PhotofeedViewController, SidebarMenuController, UIBarButtonItem, UIButton, UILabel, UIPopoverController, UIView, VKAdsTracker, VKEventsTracker, VideoViewController, iPadAudioViewController, iPadContactsView, iPadFavoritesViewController, iPadFeedbackViewController, iPadGroupsViewController, iPadNewsViewController, iPadWallViewController;

@interface iPadMainViewController : UIViewControllerStyled <UIGestureRecognizerDelegate, SettingsViewDelegate, SKStoreProductViewControllerDelegate, UIPopoverControllerDelegate, BufferedNavigationControllerDelegate, UIBarPositioningDelegate>
{
    UIView *rightSlideView;
    UIView *playerView;
    UIButton *playPlayerButton;
    UILabel *playerTitleLabel;
    UILabel *playerAuthorLabel;
    UIBarButtonItem *openMenuButton;
    AnyCounter *labelCounter;
    UIView *playerPresentationView;
    UIView *menuCloseView;
    DirectionPanGestureRecognizer *panGesture;
    DirectionPanGestureRecognizer *interactiveHide;
    NSMutableArray *viewControllersStack;
    NSMutableArray *viewControllersWindows;
    long long messagesViewNum;
    long long audioViewNum;
    _Bool restoreWindowScale;
    _Bool navigationControllerPopPrepared;
    float currentWindowScale;
    _Bool hidingWindowsNow;
    _Bool messageViewAnimationPlanned;
    _Bool preventDismissPopover;
    _Bool isCurrentMessages;
    _Bool isCurrentAudio;
    UIPopoverController *popover;
    BufferedNavigationController *internalNavigationController;
    iPadAudioViewController *audioView;
    MessagesContainerViewController *messagesView;
    iPadContactsView *contactsView;
    iPadWallViewController *wallView;
    iPadFeedbackViewController *feedbackView;
    iPadGroupsViewController *groupsView;
    VideoViewController *videoView;
    PhotofeedViewController *albumsView;
    UIBarButtonItem *popoverBarButton;
    unsigned long long popoverDirection;
    UIView *popoverView;
    iPadNewsViewController *newsViewController;
    UIView *popoverInView;
    id popoverOwner;
    long long _openChat;
    long long _selectedRow;
    long long _prevSelectedRow;
    VKEventsTracker *_statsTracker;
    VKAdsTracker *_adsTracker;
    iPadFavoritesViewController *_favoritesController;
    SidebarMenuController *_sidebarMenu;
    struct CGSize popoverSize;
    struct CGRect popoverInset;
}

+ (struct CGRect)defaultClosedModalFrame:(_Bool)arg1 fromRight:(_Bool)arg2;
+ (struct CGRect)defaultClosedModalFrame:(_Bool)arg1;
+ (struct CGRect)defaultClosedModalFrame;
+ (struct CGRect)defaultOpenedModalFrame:(long long)arg1;
+ (void)presentModalViewControllerWithoutNav:(id)arg1 animated:(_Bool)arg2;
+ (void)presentModalViewControllerInNav:(id)arg1 animated:(_Bool)arg2;
+ (void)showControllerWithNavigation:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 fromBarButton:(id)arg3 withDir:(unsigned long long)arg4 popoverOwner:(id)arg5;
+ (_Bool)isPopoverVisible;
+ (id)showController:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 fromBarButton:(id)arg3 withDir:(unsigned long long)arg4 popoverOwner:(id)arg5;
+ (id)showControllerWithNavigation:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 fromView:(id)arg3 inView:(id)arg4 withDir:(unsigned long long)arg5 withInset:(struct CGRect)arg6 popoverOwner:(id)arg7;
+ (void)showControllerWithNavigation:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 fromView:(id)arg3 inView:(id)arg4 withDir:(unsigned long long)arg5 popoverOwner:(id)arg6;
+ (void)showController:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 fromView:(id)arg3 inView:(id)arg4 popoverOwner:(id)arg5;
+ (void)prepareController:(id)arg1;
+ (id)showController:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 fromView:(id)arg3 inView:(id)arg4 withDir:(unsigned long long)arg5 withInset:(struct CGRect)arg6 popoverOwner:(id)arg7;
+ (id)showController:(id)arg1 inPopoverWithSize:(struct CGSize)arg2 inView:(id)arg3;
+ (void)dismissPopover:(id)arg1 animated:(_Bool)arg2;
+ (void)dismissPopover:(id)arg1;
+ (void)dismissPopover;
+ (id)sharedInstance;
+ (void)CleanInstance;
@property(retain, nonatomic) SidebarMenuController *sidebarMenu; // @synthesize sidebarMenu=_sidebarMenu;
@property(retain, nonatomic) iPadFavoritesViewController *favoritesController; // @synthesize favoritesController=_favoritesController;
@property(retain, nonatomic) VKAdsTracker *adsTracker; // @synthesize adsTracker=_adsTracker;
@property(retain, nonatomic) VKEventsTracker *statsTracker; // @synthesize statsTracker=_statsTracker;
@property(nonatomic) long long prevSelectedRow; // @synthesize prevSelectedRow=_prevSelectedRow;
@property(nonatomic) long long selectedRow; // @synthesize selectedRow=_selectedRow;
@property(nonatomic) long long openChat; // @synthesize openChat=_openChat;
@property(nonatomic) id popoverOwner; // @synthesize popoverOwner;
@property(nonatomic) _Bool isCurrentAudio; // @synthesize isCurrentAudio;
@property(retain, nonatomic) UIView *popoverInView; // @synthesize popoverInView;
@property(nonatomic) struct CGRect popoverInset; // @synthesize popoverInset;
@property(nonatomic) _Bool isCurrentMessages; // @synthesize isCurrentMessages;
@property(retain, nonatomic) iPadNewsViewController *newsViewController; // @synthesize newsViewController;
@property(retain, nonatomic) UIView *popoverView; // @synthesize popoverView;
@property(nonatomic) struct CGSize popoverSize; // @synthesize popoverSize;
@property(nonatomic) unsigned long long popoverDirection; // @synthesize popoverDirection;
@property(retain, nonatomic) UIBarButtonItem *popoverBarButton; // @synthesize popoverBarButton;
@property(retain, nonatomic) PhotofeedViewController *albumsView; // @synthesize albumsView;
@property(retain, nonatomic) VideoViewController *videoView; // @synthesize videoView;
@property(retain, nonatomic) iPadGroupsViewController *groupsView; // @synthesize groupsView;
@property(retain, nonatomic) iPadFeedbackViewController *feedbackView; // @synthesize feedbackView;
@property(retain, nonatomic) iPadWallViewController *wallView; // @synthesize wallView;
@property(retain, nonatomic) iPadContactsView *contactsView; // @synthesize contactsView;
@property(retain, nonatomic) MessagesContainerViewController *messagesView; // @synthesize messagesView;
@property(retain, nonatomic) iPadAudioViewController *audioView; // @synthesize audioView;
@property(retain, nonatomic) BufferedNavigationController *internalNavigationController; // @synthesize internalNavigationController;
@property(nonatomic) _Bool preventDismissPopover; // @synthesize preventDismissPopover;
@property(retain, nonatomic) UIPopoverController *popover; // @synthesize popover;
- (void).cxx_destruct;
- (void)checkIfRightSlideRequired;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)processAdsAction:(id)arg1;
- (void)captchaCheck:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (long long)positionForBar:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)checkControllerToBeDeleted:(id)arg1;
- (void)captureScreenshot:(id)arg1;
- (void)doLogout;
- (void)audioDidStartPlaying:(id)arg1;
- (void)audioDidStopPlaying:(id)arg1;
- (void)mediaInitialized:(id)arg1;
- (void)playButtonPressed:(id)arg1;
- (void)playerButtonPressed:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)panGestureHandle:(id)arg1;
- (void)handlePopRecognizer:(id)arg1 mayBegin:(_Bool)arg2;
- (void)closeMenuTap:(id)arg1;
- (void)willSetViewControllers:(id)arg1;
- (void)willShowViewController:(id)arg1 byPush:(_Bool)arg2;
- (void)willPushViewController:(id)arg1;
- (void)didPopViewController:(id)arg1 toRoot:(_Bool)arg2;
- (_Bool)needPopViewController:(id)arg1 toRoot:(_Bool)arg2 delayed:(_Bool)arg3;
- (_Bool)needPopViewController:(id)arg1 toRoot:(_Bool)arg2;
- (void)didShowViewController:(id)arg1;
- (_Bool)needPushViewController:(id)arg1;
- (void)unreadMessagesDidChanged:(id)arg1;
- (void)reloadData;
- (void)mySelfDidLoaded:(id)arg1;
- (void)openMenuButtonPressed:(id)arg1;
- (_Bool)slideMenuClosed;
- (void)openGroups;
- (void)openFriendsRequests;
- (void)openFeedback;
- (void)openAudioView;
- (void)closeAudioView:(_Bool)arg1;
- (void)willCloseSettingsView;
- (void)willCloseWindow:(_Bool)arg1;
- (void)willCloseWindow;
- (void)checkAndCloseWindows:(_Bool)arg1;
- (void)closeWindowWithController:(id)arg1;
- (id)stringForNumber:(int)arg1;
- (void)processSelectedRow:(long long)arg1 inCurrentVc:(_Bool)arg2;
- (id)getOrCreateMessagesView;
- (void)processSelectedRow:(long long)arg1;
- (void)pushToCurrentViewController:(id)arg1;
- (void)configLeftNavigationButton;
- (void)pushBaseViewController:(id)arg1;
- (unsigned long long)defaultTransitionAnimationOptions;
- (void)closeAudio;
- (void)openAudio;
- (void)closeMessages;
- (void)closeMessagesView:(_Bool)arg1;
- (void)openMessagesAndCloseAudio;
- (void)openMessages;
- (_Bool)prepareMessagesForOpen;
- (void)prepareMessagesAnimation:(id)arg1 cancelFlag:(id)arg2;
- (void)prepareMessagesAnimation:(id)arg1;
- (void)popRightSlide;
- (void)pushRightSlide;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)finishPopoverDismiss;
- (void)makeClean;
- (void)popoverController:(id)arg1 willRepositionPopoverToRect:(inout struct CGRect *)arg2 inView:(inout id *)arg3;
- (_Bool)popoverControllerShouldDismissPopover:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)checkPopoverPosition:(id)arg1 recreate:(_Bool)arg2;
- (void)checkPopoverPosition:(id)arg1;
- (void)checkPopoverPosition:(id)arg1 inView:(id)arg2;
- (void)setWindowScale:(float)arg1 animated:(_Bool)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)resizeMainSubviews:(long long)arg1;
- (void)finishRotation;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (struct CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(struct CGSize)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (void)checkRegisteredForRemote:(id)arg1;
- (void)registerForRemoteNotifications:(_Bool)arg1;
- (id)init:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

