//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FriendsLogicViewController.h"

#import "UIActionSheetDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIButton, UINoDataLoadingView, UISearchBar, UISearchDisplayControllerNoHide, UISegmentedControl, UITableView, UIView, UIViewController;

@interface iPadFriendsView : FriendsLogicViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UIActionSheetDelegate, UISearchDisplayDelegate>
{
    _Bool onlineOnly;
    UISearchBar *SearchBar;
    UITableView *ContactsTable;
    UIViewController *ownerViewController;
    UISegmentedControl *onlineSwitchBar;
    UIButton *backButton;
    UIView *_bottomToolbarView;
    UINoDataLoadingView *_noDataView;
}

@property(retain, nonatomic) UINoDataLoadingView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UIView *bottomToolbarView; // @synthesize bottomToolbarView=_bottomToolbarView;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton;
@property(retain, nonatomic) UISegmentedControl *onlineSwitchBar; // @synthesize onlineSwitchBar;
@property(nonatomic) _Bool onlineOnly; // @synthesize onlineOnly;
@property(nonatomic) UIViewController *ownerViewController; // @synthesize ownerViewController;
@property(retain, nonatomic) UITableView *ContactsTable; // @synthesize ContactsTable;
@property(retain, nonatomic) UISearchBar *SearchBar; // @synthesize SearchBar;
- (void).cxx_destruct;
- (long long)positionForBar:(id)arg1;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)usersDidSearch:(id)arg1;
- (void)refreshControlFiredEvent:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)onlineSwitchValue:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)didFinishLoadingData;
- (void)reloadData;
- (_Bool)resignFirstResponder;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UISearchDisplayControllerNoHide *searchController; // @dynamic searchController;
@property(readonly) Class superclass;

@end

