//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIAlertViewDelegate.h"
#import "UIFastLabelDelegate.h"
#import "UITextViewDelegate.h"

@class BackupImageView, ChatAttachView, NSString, UIActivityIndicatorView, UIButton, UIFastLabel, UIImage, UIImageView, UILabel, UITableView, UIView, VKMessage;

@interface iPadChatViewCell : UITableViewCell <UIAlertViewDelegate, UITextViewDelegate, UIFastLabelDelegate>
{
    _Bool _isChat;
    _Bool _isOut;
    _Bool _checked;
    _Bool _selectedMy;
    _Bool _isNewCell;
    id <iPadChatViewCellDelegate> _delegate;
    UITableView *_parentTable;
    VKMessage *_message;
    UIFastLabel *_messageLabel;
    UIImageView *_bubbleImage;
    UIButton *_failButton;
    ChatAttachView *_attachView;
    BackupImageView *_avatarImage;
    UIImageView *_backgroundViewUnread;
    UIImageView *_sentImage;
    UILabel *_timeLabel;
    UIView *_editingLineBottom;
    UIView *_editingLineTop;
    UIActivityIndicatorView *_sendActivity;
    UIImage *_normalBubbleImage;
    UIImage *_selectedBubbleImage;
}

+ (void)initialize;
@property(retain, nonatomic) UIImage *selectedBubbleImage; // @synthesize selectedBubbleImage=_selectedBubbleImage;
@property(retain, nonatomic) UIImage *normalBubbleImage; // @synthesize normalBubbleImage=_normalBubbleImage;
@property(retain, nonatomic) UIActivityIndicatorView *sendActivity; // @synthesize sendActivity=_sendActivity;
@property(retain, nonatomic) UIView *editingLineTop; // @synthesize editingLineTop=_editingLineTop;
@property(retain, nonatomic) UIView *editingLineBottom; // @synthesize editingLineBottom=_editingLineBottom;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *sentImage; // @synthesize sentImage=_sentImage;
@property(retain, nonatomic) UIImageView *backgroundViewUnread; // @synthesize backgroundViewUnread=_backgroundViewUnread;
@property(retain, nonatomic) BackupImageView *avatarImage; // @synthesize avatarImage=_avatarImage;
@property(nonatomic) _Bool isNewCell; // @synthesize isNewCell=_isNewCell;
@property(retain, nonatomic) ChatAttachView *attachView; // @synthesize attachView=_attachView;
@property(retain, nonatomic) UIButton *failButton; // @synthesize failButton=_failButton;
@property(retain, nonatomic) UIImageView *bubbleImage; // @synthesize bubbleImage=_bubbleImage;
@property(retain, nonatomic) UIFastLabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) VKMessage *message; // @synthesize message=_message;
@property(nonatomic) __weak UITableView *parentTable; // @synthesize parentTable=_parentTable;
@property(nonatomic) __weak id <iPadChatViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)checkNeedReloadMessage:(id)arg1;
- (void)fastLabel:(id)arg1 didSelectLink:(id)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)failButtonPressd:(id)arg1;
- (void)setSelectedMy:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1;
- (void)setCanCheck:(_Bool)arg1;
- (void)layoutSubviews;
- (void)updateSendProgress;
- (void)updateDeleteState;
- (void)updateReadState:(_Bool)arg1;
- (void)updateReadState;
- (void)tapAvatar:(id)arg1;
- (void)clear;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 isOut:(_Bool)arg3 isChat:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

