//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

@class AnyCounter, PhoneBook, SuggestFriendRequestsView, UISegmentedControl, UIView, iPadFriendRequestsSelector, iPadFriendsView;

@interface iPadContactsView : UIViewControllerStyled
{
    _Bool _forceRequests;
    UIView *BarView;
    UISegmentedControl *BarViewSegment;
    PhoneBook *phoneBook;
    iPadFriendsView *friendsView;
    UIView *CalendarButtonView;
    iPadFriendRequestsSelector *requestsView;
    AnyCounter *_labelCounter;
    SuggestFriendRequestsView *_view1;
}

@property(retain, nonatomic) SuggestFriendRequestsView *view1; // @synthesize view1=_view1;
@property(retain, nonatomic) AnyCounter *labelCounter; // @synthesize labelCounter=_labelCounter;
@property(retain, nonatomic) iPadFriendRequestsSelector *requestsView; // @synthesize requestsView;
@property(retain, nonatomic) UIView *CalendarButtonView; // @synthesize CalendarButtonView;
@property(retain, nonatomic) iPadFriendsView *friendsView; // @synthesize friendsView;
@property(retain, nonatomic) PhoneBook *phoneBook; // @synthesize phoneBook;
@property(retain, nonatomic) UISegmentedControl *BarViewSegment; // @synthesize BarViewSegment;
@property(retain, nonatomic) UIView *BarView; // @synthesize BarView;
- (void).cxx_destruct;
- (void)CalendarButtonClick:(id)arg1;
- (void)selectTab;
- (_Bool)resignFirstResponder;
- (void)viewDidLoad;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)friendsDidLoaded:(id)arg1;
- (void)updateNotifyCount;
- (void)dealloc;
- (void)openRequests:(id)arg1;
- (id)init;

@end

