//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSDictionary, NSString;

@protocol IVKRequest <NSObject>
@property(copy, nonatomic) __block didFailedBlock;
@property(copy, nonatomic) __block didFinishBlock;
@property(copy, nonatomic) __block processingBlock;
@property(copy, nonatomic) NSString *senderGUID;
@property(retain, nonatomic) id <VKResponse> response;
- (void)cancel;
- (void)repeatAfter:(int)arg1;
- (void)repeat;
- (void)load;
- (void)bindToGuid:(NSString *)arg1;
- (id)buildresponse:(NSDictionary *)arg1;
@end

