//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber;

@interface likes_isLiked_res : VKResponse
{
    NSNumber *_liked;
    NSNumber *_copied;
}

@property(retain, nonatomic) NSNumber *copied; // @synthesize copied=_copied;
@property(retain, nonatomic) NSNumber *liked; // @synthesize liked=_liked;
- (void).cxx_destruct;

@end

