//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, UIImage;

@interface LRUCacheObject : NSObject
{
    UIImage *_image;
    NSDate *_time;
    id <NSCopying> _key;
}

@property(copy) id <NSCopying> key; // @synthesize key=_key;
@property(retain) NSDate *time; // @synthesize time=_time;
@property(retain) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;

@end

