//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIViewReleasable.h"

@class CrossDissolveImageView, KAProgressLabel, NSString, UIHoledView, UIImageView, UILabel;

@interface MediaView : UIView <UIViewReleasable>
{
    _Bool _preparedToRelease;
    CrossDissolveImageView *_image;
    UIImageView *_imageLabel;
    UILabel *_label;
    KAProgressLabel *_roundProgress;
    long long _cornerRadius;
    UIHoledView *_darkenView;
    CDUnknownBlockType _attachPressBlock;
}

@property _Bool preparedToRelease; // @synthesize preparedToRelease=_preparedToRelease;
@property(copy, nonatomic) CDUnknownBlockType attachPressBlock; // @synthesize attachPressBlock=_attachPressBlock;
@property(retain, nonatomic) UIHoledView *darkenView; // @synthesize darkenView=_darkenView;
@property(nonatomic) long long cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(retain, nonatomic) KAProgressLabel *roundProgress; // @synthesize roundProgress=_roundProgress;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *imageLabel; // @synthesize imageLabel=_imageLabel;
@property(retain, nonatomic) CrossDissolveImageView *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)setProgressLabelSize:(double)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)setHighlightedTable:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)performTap:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

