//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSOperation, NSString;

@interface MediaController : NSObject
{
    double lastSearchTime;
    NSMutableDictionary *searchAudioUids;
    double lastSearchTimeVideo;
    NSMutableDictionary *searchVideoUids;
    NSString *uploadingAudio;
    NSString *uploadingVideo;
    NSString *uploadingPhoto;
    NSOperation *wallUploadOperation;
    CDUnknownBlockType audioSearch;
    CDUnknownBlockType videoSearch;
    _Bool _searchingAudio;
    _Bool _audioSearchEndReached;
    _Bool _searchingVideo;
    _Bool _videoSearchEndReached;
    NSMutableArray *_searchAudiosArray;
    unsigned long long _totalAudioSearchCount;
    NSMutableArray *_searchVideosArray;
    long long _totalVideoSearchCount;
}

+ (id)thumbnailURLForVideo:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) long long totalVideoSearchCount; // @synthesize totalVideoSearchCount=_totalVideoSearchCount;
@property(nonatomic) _Bool videoSearchEndReached; // @synthesize videoSearchEndReached=_videoSearchEndReached;
@property(nonatomic) _Bool searchingVideo; // @synthesize searchingVideo=_searchingVideo;
@property(retain, nonatomic) NSMutableArray *searchVideosArray; // @synthesize searchVideosArray=_searchVideosArray;
@property(nonatomic) unsigned long long totalAudioSearchCount; // @synthesize totalAudioSearchCount=_totalAudioSearchCount;
@property(nonatomic) _Bool audioSearchEndReached; // @synthesize audioSearchEndReached=_audioSearchEndReached;
@property(nonatomic) _Bool searchingAudio; // @synthesize searchingAudio=_searchingAudio;
@property(retain, nonatomic) NSMutableArray *searchAudiosArray; // @synthesize searchAudiosArray=_searchAudiosArray;
- (void).cxx_destruct;
- (id)removeVideo:(id)arg1 fromAlbum:(id)arg2 withTargetId:(id)arg3;
- (id)loadAlbumsForVideo:(id)arg1 target:(id)arg2;
- (void)checkCellToHideAttaches:(id)arg1;
- (void)finishRepostWith:(id)arg1 request:(id)arg2;
- (void)makeRepost:(id)arg1 message:(id)arg2 fromGroup:(id)arg3 completeBlock:(CDUnknownBlockType)arg4;
- (void)likePressForPost:(id)arg1;
- (id)loadLikesForId:(id)arg1 andOwner:(id)arg2 andType:(id)arg3 withOffset:(id)arg4 andCount:(id)arg5 friendsOnly:(_Bool)arg6 repostsOnly:(_Bool)arg7;
- (id)deletePhotoAlbumWithAid:(id)arg1 ownerId:(id)arg2;
- (void)addPhotoCommentForPid:(id)arg1 andOwner:(id)arg2 withComment:(id)arg3 attachments:(id)arg4 fromGroup:(_Bool)arg5;
- (id)loadPhotoCommentsForPid:(id)arg1 andOwner:(id)arg2 withOffset:(long long)arg3 andCount:(long long)arg4 sender:(id)arg5;
- (void)deletePhotoCommentForCid:(id)arg1 andOwner:(id)arg2 andPid:(id)arg3;
- (void)notifyPostChanged:(id)arg1 likes:(id)arg2 reposts:(id)arg3;
- (id)deleteObjectLikeForId:(id)arg1 andOwner:(id)arg2 andType:(id)arg3 andAccessKey:(id)arg4;
- (id)addObjectLikeForId:(id)arg1 andOwner:(id)arg2 andType:(id)arg3 andAccessKey:(id)arg4;
- (void)makePhotoWithPid:(id)arg1 andOid:(id)arg2 coverToAlbum:(id)arg3;
- (void)movePhotoWithPid:(id)arg1 andOid:(id)arg2 toAlbum:(id)arg3;
- (void)placePhotoAlbumWithAid:(id)arg1 andOid:(id)arg2 afterAid:(id)arg3 orBefore:(id)arg4;
- (void)placePhotoWithPid:(id)arg1 andOid:(id)arg2 afterPid:(id)arg3 orBefore:(id)arg4;
- (id)loadMorePhotoAlbumsForUid:(id)arg1 withOffset:(id)arg2 andCount:(id)arg3;
- (void)cancelWallUpload;
- (void)uploadPhotoToWall:(id)arg1 toUid:(id)arg2;
- (void)uploadPhoto:(id)arg1 toAlbum:(id)arg2 andGroup:(id)arg3;
- (void)deletePhotoWithPid:(id)arg1 andOid:(id)arg2;
- (id)loadVideosProfileForUid:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3;
- (id)loadPhotosUserForUid:(id)arg1 withOffset:(unsigned long long)arg2 andCount:(unsigned long long)arg3;
- (id)loadPhotosProfileForUid:(id)arg1 withOffset:(id)arg2 andCount:(id)arg3;
- (id)loadPhotoForPid:(id)arg1 andOwner:(id)arg2 andAccessKey:(id)arg3;
- (id)loadPhotosForUid:(id)arg1 inAlbum:(id)arg2 withOffset:(unsigned long long)arg3 andCount:(unsigned long long)arg4;
- (id)loadPhotosForUid:(id)arg1 withFeed:(id)arg2 andFeedType:(id)arg3 withOffset:(unsigned long long)arg4 andCount:(unsigned long long)arg5;
- (id)uploadVideo:(id)arg1 isPrivate:(id)arg2 toGroup:(id)arg3 completeBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5 didFailedBlock:(CDUnknownBlockType)arg6;
- (id)loadMoreVideoAlbumsForUid:(id)arg1 withOffset:(unsigned long long)arg2 andCount:(unsigned long long)arg3;
- (id)addVideoWithVid:(id)arg1 andOid:(id)arg2;
- (id)deleteVideo:(id)arg1;
- (id)searchVideos:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3 opt1:(long long)arg4 opt2:(long long)arg5 opt3:(long long)arg6;
- (id)loadVideosForUid:(id)arg1 inAlbum:(id)arg2 withOffset:(long long)arg3 andCount:(long long)arg4;
- (id)loadMoreAlbumsForUid:(id)arg1 withOffset:(unsigned long long)arg2 andCount:(unsigned long long)arg3;
- (void)placeAudioWithAid:(id)arg1 andOid:(id)arg2 afterAid:(id)arg3 orBefore:(id)arg4;
- (void)uploadAudio:(id)arg1;
- (void)addAudioWithAid:(id)arg1 andOid:(id)arg2 toGroup:(id)arg3;
- (void)deleteAudioWithAid:(id)arg1 andOid:(id)arg2;
- (id)searchAudios:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3;
- (id)loadAudioRecommendationForUid:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3;
- (id)loadAudiosForUid:(id)arg1 inAlbum:(id)arg2 withOffset:(long long)arg3 andCount:(long long)arg4;
- (void)cleanUp;
- (id)init;
- (void)dealloc;

@end

