//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface messages_editChat_req : VKRequest
{
    NSNumber *_chat_id;
    NSString *_title;
}

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *chat_id; // @synthesize chat_id=_chat_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

