//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "messages_send_req.h"

@class NSNumber;

@interface messages_sendSticker_req : messages_send_req
{
    NSNumber *_sticker_id;
}

@property(retain, nonatomic) NSNumber *sticker_id; // @synthesize sticker_id=_sticker_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

