//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSString;

@interface messages_setChatPhoto_req : VKRequest
{
    NSString *_file;
}

@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

