//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface messages_getLongPollHistory_req : VKRequest
{
    NSNumber *_ts;
    NSNumber *_pts;
    NSNumber *_preview_length;
    NSNumber *_onlines;
    NSNumber *_events_limit;
    NSNumber *_msgs_limit;
    NSNumber *_max_msg_id;
}

@property(retain, nonatomic) NSNumber *max_msg_id; // @synthesize max_msg_id=_max_msg_id;
@property(retain, nonatomic) NSNumber *msgs_limit; // @synthesize msgs_limit=_msgs_limit;
@property(retain, nonatomic) NSNumber *events_limit; // @synthesize events_limit=_events_limit;
@property(retain, nonatomic) NSNumber *onlines; // @synthesize onlines=_onlines;
@property(retain, nonatomic) NSNumber *preview_length; // @synthesize preview_length=_preview_length;
@property(retain, nonatomic) NSNumber *pts; // @synthesize pts=_pts;
@property(retain, nonatomic) NSNumber *ts; // @synthesize ts=_ts;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

