//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NotificationViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSOperation, NSString, NSThread, NSTimer, NSURL, UploadVideoObject, VKChats, VKCounters, VKJSONRequestOperation, VKUsers, audio_getById_req, internal_getNotifications_res, messages_getLongPollServer_req, stored_getDialogs_req;

@interface MessagesController : NSObject <UIAlertViewDelegate, NotificationViewDelegate>
{
    double lastCountersUpdateTime;
    CDUnknownBlockType messagesSearch;
    NSObject<OS_dispatch_queue> *_longPollQueue;
    _Bool _allowLongPollConnection;
    NSNumber *lastKnownTs;
    NSTimer *userPrintTimer;
    long long currentLoadingDialogsStatus;
    double lastSearchTime;
    double lastOnlineTime;
    NSMutableArray *pendingMessages;
    NSMutableDictionary *myRecievedMessages;
    NSMutableDictionary *pendingRead;
    _Bool _connectingToLongPoll;
    _Bool _waitForTypingUpdates;
    messages_getLongPollServer_req *longPollRequest;
    VKJSONRequestOperation *longPollOperation;
    NSMutableDictionary *longPollParams;
    NSString *uploadingImage;
    UploadVideoObject *videoUploadObject;
    long long counter;
    NSString *callPhone;
    NSMutableDictionary *audioDictionary;
    audio_getById_req *lastAudioQuery;
    NSOperation *wallUploadOperation;
    double lastStatTime;
    internal_getNotifications_res *notificationResult;
    NSURL *openURL;
    stored_getDialogs_req *lastGetDialogsReq;
    NSThread *_messagesThread;
    _Bool _currentLoadingDialogsInProgress;
    NSArray *_dialogsArray;
    NSMutableDictionary *_dialogsByUids;
    NSNumber *_dialogsCount;
    long long _currentLoadingDialogsCount;
    NSNumber *_dialogsUpdateTime;
    VKCounters *_counters;
    NSMutableDictionary *_typingUsers;
    VKUsers *_searchResultUser;
    VKChats *_searchResultMessages;
}

+ (id)sharedInstance;
@property(retain, nonatomic) VKChats *searchResultMessages; // @synthesize searchResultMessages=_searchResultMessages;
@property(retain, nonatomic) VKUsers *searchResultUser; // @synthesize searchResultUser=_searchResultUser;
@property(retain, nonatomic) NSMutableDictionary *typingUsers; // @synthesize typingUsers=_typingUsers;
@property(retain, nonatomic) VKCounters *counters; // @synthesize counters=_counters;
@property(retain, nonatomic) NSNumber *dialogsUpdateTime; // @synthesize dialogsUpdateTime=_dialogsUpdateTime;
@property(readonly, nonatomic) long long currentLoadingDialogsCount; // @synthesize currentLoadingDialogsCount=_currentLoadingDialogsCount;
@property(readonly, nonatomic) _Bool currentLoadingDialogsInProgress; // @synthesize currentLoadingDialogsInProgress=_currentLoadingDialogsInProgress;
@property(retain, nonatomic) NSNumber *dialogsCount; // @synthesize dialogsCount=_dialogsCount;
@property(retain, nonatomic) NSMutableDictionary *dialogsByUids; // @synthesize dialogsByUids=_dialogsByUids;
@property(retain) NSArray *dialogsArray; // @synthesize dialogsArray=_dialogsArray;
- (void).cxx_destruct;
- (void)openAttach:(id)arg1;
- (void)loadLongPollHistory:(_Bool)arg1;
- (void)disconnectLongPoll;
- (_Bool)processNotification:(id)arg1;
- (void)didTapNotification:(id)arg1;
- (void)didTapNotificationDialog:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)loadForwardedUsers:(id)arg1 andGroups:(id)arg2;
- (void)updateUnreadMessages;
- (void)updateCountersWithRes:(id)arg1;
- (void)loadChatInfo:(id)arg1;
- (void)changeChatTitle:(id)arg1 toTitle:(id)arg2;
- (void)showWallPostWithPid:(id)arg1 withOwner:(id)arg2 orPostObject:(id)arg3;
- (void)showNote:(id)arg1 withOwner:(id)arg2;
- (void)showUserOrGroupWithDomain:(id)arg1;
- (void)showPage:(id)arg1 withgroup_id:(id)arg2 andTitle:(id)arg3 andBrowser:(id)arg4;
- (_Bool)insertMessageToArray:(id)arg1;
- (void)sortAndClearDialogs;
- (void)sortDialogsAndNotifyAboutFinishLoading;
- (void)notifyAboutNewMessages;
- (void)loadLastActivity:(id)arg1;
- (void)sendMessage:(id)arg1 withAttach:(id)arg2 withForwarded:(id)arg3;
- (void)sendSticker:(id)arg1 withMessage:(id)arg2;
- (void)sendMessageFailed:(id)arg1 request:(id)arg2;
- (void)sendMessageSucceed:(id)arg1 response:(id)arg2;
- (void)markMessagesAsRead:(id)arg1;
- (void)showAudio:(id)arg1 withOwner:(id)arg2 andPlayNum:(long long)arg3 andArray:(id)arg4;
- (void)showVideo:(id)arg1 accessKey:(id)arg2 source:(id)arg3 originalVideo:(id)arg4;
- (void)showWall:(id)arg1 pid:(id)arg2;
- (void)loadWall:(id)arg1 pid:(id)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (void)showAlbum:(id)arg1 aid:(id)arg2;
- (void)showAlbums:(id)arg1;
- (void)showTopic:(id)arg1;
- (void)showPhoto:(id)arg1;
- (void)cancelUpload;
- (void)uploadVideo:(id)arg1 toDialog:(id)arg2 toGroup:(id)arg3;
- (void)uploadImage:(id)arg1;
- (void)connectToLongPollServer;
- (void)performInsertingMessages:(id)arg1;
- (void)processNewMessagesFromLongPoll:(id)arg1;
- (void)loadUnknownMessages:(id)arg1;
- (void)loadUnknownUsersFromMessages:(id)arg1;
- (void)recursiveAddUnknownUsers:(id)arg1 users:(id)arg2;
- (void)checkUser:(id)arg1 forLoadingTo:(id)arg2;
- (void)processLongPollResponse;
- (void)parseLongPollHistory:(id)arg1 withMessages:(id)arg2;
- (void)parseLongPollResponse:(id)arg1;
- (void)setDialogReadState:(id)arg1 toMessage:(id)arg2 isOut:(_Bool)arg3;
- (void)getLongPollServer;
- (id)getLastPts;
- (void)showWallSearch:(id)arg1 withQuery:(id)arg2;
- (void)savePts:(id)arg1;
- (void)openChat:(long long)arg1;
- (void)searchDialogs:(id)arg1;
- (void)setActivityInChat:(id)arg1 toUser:(id)arg2;
- (id)createDialog:(id)arg1 withTitle:(id)arg2;
- (void)removeMessage:(id)arg1;
- (void)addUser:(id)arg1 toChat:(id)arg2;
- (void)removeUser:(id)arg1 fromChat:(id)arg2;
- (void)removeDialog:(id)arg1;
- (id)loadHistoryForDialog:(id)arg1 withOffset:(long long)arg2 andCount:(long long)arg3 andMid:(id)arg4 asUpdater:(_Bool)arg5;
- (id)loadChatUsers:(id)arg1;
- (void)loadMoreDialogs;
- (void)reloadAllDialogs;
- (void)networkConnectionBecomeActive:(id)arg1;
- (id)formatUserPrintUpdates;
- (void)updateTypingUsers;
- (id)typingUsersForChat:(id)arg1;
- (void)resolveDomain:(id)arg1 withTag:(id)arg2;
- (_Bool)processLink:(id)arg1 forBrowser:(_Bool)arg2;
- (_Bool)processLink:(id)arg1;
- (void)showGroup:(id)arg1;
- (void)showUser:(id)arg1;
- (void)cleanUp;
- (void)scheduleTimer:(id)arg1;
- (void)setUserPrintTimer;
- (void)background:(id)arg1;
- (void)foreground:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)messagesControllerThread;
- (void)messagesControllerThreadEntryPoint:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

