//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface messages_getHistory_req : VKRequest
{
    NSNumber *_offset;
    NSNumber *_count;
    NSNumber *_user_id;
    NSNumber *_chat_id;
    NSNumber *_start_message_id;
    NSNumber *_rev;
}

@property(retain, nonatomic) NSNumber *rev; // @synthesize rev=_rev;
@property(retain, nonatomic) NSNumber *start_message_id; // @synthesize start_message_id=_start_message_id;
@property(retain, nonatomic) NSNumber *chat_id; // @synthesize chat_id=_chat_id;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

