//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface messages_restore_req : VKRequest
{
    NSNumber *_message_id;
}

@property(retain, nonatomic) NSNumber *message_id; // @synthesize message_id=_message_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

