//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, VKMessages;

@interface messages_getHistory_res : VKResponse
{
    NSNumber *_count;
    NSNumber *_skipped;
    VKMessages *_items;
}

@property(retain, nonatomic) VKMessages *items; // @synthesize items=_items;
@property(retain, nonatomic) NSNumber *skipped; // @synthesize skipped=_skipped;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
- (void).cxx_destruct;

@end

