//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, NSString;

@interface messages_getLongPollServer_res : VKResponse
{
    NSString *_key;
    NSString *_server;
    NSNumber *_ts;
    NSNumber *_pts;
}

@property(retain, nonatomic) NSNumber *pts; // @synthesize pts=_pts;
@property(retain, nonatomic) NSNumber *ts; // @synthesize ts=_ts;
@property(copy, nonatomic) NSString *server; // @synthesize server=_server;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;

@end

