//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface messages_getById_req : VKRequest
{
    NSString *_message_ids;
    NSNumber *_preview_length;
}

@property(retain, nonatomic) NSNumber *preview_length; // @synthesize preview_length=_preview_length;
@property(copy, nonatomic) NSString *message_ids; // @synthesize message_ids=_message_ids;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

