//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MRAsyncCommandResult;

@interface MRAsyncCommand : NSOperation
{
    _Bool _isExecuting;
    _Bool _isFinished;
    id <MRAsyncCommandDelegate> _delegate;
    MRAsyncCommandResult *_result;
}

@property(nonatomic) _Bool isFinished; // @synthesize isFinished=_isFinished;
@property(nonatomic) _Bool isExecuting; // @synthesize isExecuting=_isExecuting;
@property(retain, nonatomic) MRAsyncCommandResult *result; // @synthesize result=_result;
@property(retain, nonatomic) id <MRAsyncCommandDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)description;
- (void)cancel;
- (void)start;
- (id)init;

@end

