//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MRAsyncCommandDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface MRCommandExecutor : NSObject <MRAsyncCommandDelegate>
{
    NSObject<OS_dispatch_queue> *_executorQueue;
    NSMutableArray *_commandQueue;
}

+ (id)instance;
@property(retain) NSMutableArray *commandQueue; // @synthesize commandQueue=_commandQueue;
- (void).cxx_destruct;
- (void)commandFinished:(id)arg1 withResult:(id)arg2;
- (id)executorQueue;
- (void)handleCommand:(id)arg1 result:(id)arg2;
- (void)dispatchNext;
- (void)execute:(id)arg1;
- (id)init;

@end

