//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MRCommandFactory : NSObject
{
}

+ (id)trackCustomEventCommand:(id)arg1 eventParams:(id)arg2 host:(id)arg3 trackerParams:(id)arg4;
+ (id)trackEventCommand:(id)arg1 eventParams:(id)arg2 host:(id)arg3 trackerParams:(id)arg4;
+ (id)installOrUpdateCommand:(id)arg1 host:(id)arg2;

@end

