//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MRAbstractDataProvider.h"

@interface MRCustomParamsProvider : MRAbstractDataProvider
{
}

- (void)setMRGSDeviceId:(id)arg1;
- (void)setMRGSUserId:(id)arg1;
- (void)setMRGSAppId:(id)arg1;
- (void)setOkId:(id)arg1;
- (void)setIcqId:(id)arg1;
- (void)setPhone:(id)arg1;
- (void)setEmail:(id)arg1;
- (void)setGender:(id)arg1;
- (void)setLanguage:(id)arg1;
- (void)setAge:(id)arg1;

@end

