//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MRAsyncHTTPCommand.h"

@interface MRInstallOrUpdateCommand : MRAsyncHTTPCommand
{
}

- (unsigned long long)getAppInstallTime;
- (id)getCurrentAppVersion;
- (void)trackUpdate;
- (void)trackInstall;
- (void)start;
- (id)initWithUrl:(id)arg1 trackerParams:(id)arg2;

@end

