//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MRAbstractDataProvider.h"

@class MTGCNetworkReachability;

@interface MRNetworkDataProvider : MRAbstractDataProvider
{
    MTGCNetworkReachability *_reachabilityManager;
}

@property(retain, nonatomic) MTGCNetworkReachability *reachabilityManager; // @synthesize reachabilityManager=_reachabilityManager;
- (void).cxx_destruct;
- (void)updateReachabilityValue:(unsigned char)arg1;
- (void)dealloc;
- (void)startMonitoring;
- (void)collectData;
- (id)init;

@end

