//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface newsfeed_getBanned_req : VKRequest
{
    NSNumber *_extended;
    NSString *_fields;
    NSString *_name_case;
}

@property(copy, nonatomic) NSString *name_case; // @synthesize name_case=_name_case;
@property(copy, nonatomic) NSString *fields; // @synthesize fields=_fields;
@property(retain, nonatomic) NSNumber *extended; // @synthesize extended=_extended;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

