//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSString;

@interface newsfeed_getLists_req : VKRequest
{
    NSString *_user_ids;
    NSString *_group_ids;
}

@property(copy, nonatomic) NSString *group_ids; // @synthesize group_ids=_group_ids;
@property(copy, nonatomic) NSString *user_ids; // @synthesize user_ids=_user_ids;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

