//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewControllerStyled.h"

#import "UITextViewDelegate.h"

@class NSString, UIButton, UITextView;

@interface NewStatusViewController : UIViewControllerStyled <UITextViewDelegate>
{
    NSString *currentStatus;
    id <NewStatusViewControllerDelegate> _delegate;
    UIButton *_sendButton;
    UITextView *_messageField;
}

@property(retain, nonatomic) UITextView *messageField; // @synthesize messageField=_messageField;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) id <NewStatusViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)sendButtonPressed:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (struct CGSize)preferredContentSize;
- (void)viewDidUnload;
- (void)loadView;
- (void)dealloc;
- (id)initWithCurrentStatus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

