//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface newsfeed_getMentions_req : VKRequest
{
    NSNumber *_owner_id;
    NSNumber *_start_time;
    NSNumber *_end_time;
    NSNumber *_count;
    NSNumber *_offset;
}

@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *end_time; // @synthesize end_time=_end_time;
@property(retain, nonatomic) NSNumber *start_time; // @synthesize start_time=_start_time;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

