//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (hnk_utils)
- (void)hnk_enumerateContentsOfDirectoryAtPath:(id)arg1 orderedByProperty:(id)arg2 ascending:(_Bool)arg3 usingBlock:(CDUnknownBlockType)arg4;
@end

