//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (PunycodeAdditions)
- (id)decodedURLString;
- (id)encodedURLString;
- (id)URLParts;
- (id)IDNADecodedString;
- (id)IDNAEncodedString;
- (id)punycodeDecodedString;
- (id)punycodeEncodedString;
- (const unsigned int *)longCharactersWithCount:(unsigned long long *)arg1;
@end

