//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BackupImageView.h"

@class UIImage;

@interface ParallaxImageView : BackupImageView
{
    _Bool _parallaxEnabled;
    UIImage *_lastParallaxImage;
}

@property(retain, nonatomic) UIImage *lastParallaxImage; // @synthesize lastParallaxImage=_lastParallaxImage;
@property(nonatomic) _Bool parallaxEnabled; // @synthesize parallaxEnabled=_parallaxEnabled;
- (void).cxx_destruct;
- (void)redraw;
- (void)cancelLoading;
- (void)setParallaxImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setImage:(id)arg1 fromUrl:(id)arg2;

@end

