//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface photos_getAlbums_req : VKRequest
{
    NSString *_album_ids;
    NSNumber *_owner_id;
    NSNumber *_offset;
    NSNumber *_count;
    NSNumber *_need_covers;
    NSNumber *_photo_sizes;
    NSNumber *_need_system;
}

@property(retain, nonatomic) NSNumber *need_system; // @synthesize need_system=_need_system;
@property(retain, nonatomic) NSNumber *photo_sizes; // @synthesize photo_sizes=_photo_sizes;
@property(retain, nonatomic) NSNumber *need_covers; // @synthesize need_covers=_need_covers;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(copy, nonatomic) NSString *album_ids; // @synthesize album_ids=_album_ids;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

