//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKPhotos;

@interface photos_saveMessagesPhoto_res : VKResponse
{
    VKPhotos *_response;
}

@property(retain, nonatomic) VKPhotos *response; // @synthesize response=_response;
- (void).cxx_destruct;

@end

