//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, VKPhotoSize;

@protocol Photoable
@property(readonly, nonatomic) VKPhotoSize *photo_max_size;
@property(readonly, copy, nonatomic) NSString *photo_max_orig;
@property(readonly, copy, nonatomic) NSString *photo_200;
@property(readonly, copy, nonatomic) NSString *photo_100;
@property(readonly, copy, nonatomic) NSString *photo_50;
@end

