//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface polls_getVoters_req : VKRequest
{
    NSNumber *_owner_id;
    NSNumber *_poll_id;
    NSNumber *_answer_ids;
    NSNumber *_is_board;
    NSNumber *_friends_only;
    NSNumber *_offset;
    NSNumber *_count;
    NSString *_fields;
    NSString *_name_case;
}

@property(copy, nonatomic) NSString *name_case; // @synthesize name_case=_name_case;
@property(copy, nonatomic) NSString *fields; // @synthesize fields=_fields;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSNumber *friends_only; // @synthesize friends_only=_friends_only;
@property(retain, nonatomic) NSNumber *is_board; // @synthesize is_board=_is_board;
@property(retain, nonatomic) NSNumber *answer_ids; // @synthesize answer_ids=_answer_ids;
@property(retain, nonatomic) NSNumber *poll_id; // @synthesize poll_id=_poll_id;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

