//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewControllerStyled.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSNumber, NSString, UISegmentedControl;

@interface PollAnswersViewController : UITableViewControllerStyled <UITableViewDataSource, UITableViewDelegate>
{
    NSMutableArray *getUsersArray;
    NSMutableDictionary *getUsersDict;
    _Bool loading;
    _Bool endReached;
    NSString *guid;
    long long totalUsersCount;
    NSNumber *_pollId;
    NSNumber *_ownerId;
    NSNumber *_answerId;
    UISegmentedControl *_segmentControl;
}

@property(retain, nonatomic) UISegmentedControl *segmentControl; // @synthesize segmentControl=_segmentControl;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)refreshControlFiredEvent:(id)arg1;
- (void)selectTab:(id)arg1;
- (void)loadUsersWithOffset:(id)arg1 count:(id)arg2;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithPollId:(id)arg1 ownerId:(id)arg2 answerId:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

