//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKPoll;

@interface polls_create_res : VKResponse
{
    VKPoll *_response;
}

@property(retain, nonatomic) VKPoll *response; // @synthesize response=_response;
- (void).cxx_destruct;

@end

