//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AdsBottomPanel, BackupImageView, ChatAttachView, NSArray, PostCommentsView, TitleNameButton, UIButton, UIButtonHL, UIColor, UIFastLabel, UIImage, UIImageView, UILabel, VKPost;

@interface PostView : UIView
{
    double lastViewWidth;
    _Bool isNewsfeedExpanded;
    _Bool _isCommentsViewHidden;
    _Bool _isBackgroundHidden;
    _Bool _highlighted;
    _Bool _isWallCell;
    _Bool _isFixedPost;
    _Bool _isCopy;
    _Bool _isParentHasText;
    _Bool _forceExpand;
    _Bool _isActionsButtonHidden;
    _Bool _dontTrackStats;
    _Bool _dontDrawPostContent;
    id <PostViewDelegate> _delegate;
    UIButtonHL *_shareButton;
    ChatAttachView *_attachView;
    UIImageView *_background;
    UIFastLabel *_messageLabel;
    UIColor *_timeColor;
    PostView *_copyPostView;
    PostCommentsView *_commentsView;
    unsigned long long _postLocation;
    VKPost *_currentPost;
    TitleNameButton *_titleView;
    TitleNameButton *_repostOfRepostView;
    UIImageView *_repostLine;
    UIButton *_showFullButton;
    BackupImageView *_authorImage;
    UIButton *_authorButton;
    UILabel *_debugLabel;
    UIButton *_restoreButton;
    NSArray *_hideSourceButtons;
    VKPost *_extraPost;
    AdsBottomPanel *_adsPanel;
}

@property(retain, nonatomic) AdsBottomPanel *adsPanel; // @synthesize adsPanel=_adsPanel;
@property(nonatomic) _Bool dontDrawPostContent; // @synthesize dontDrawPostContent=_dontDrawPostContent;
@property(retain, nonatomic) VKPost *extraPost; // @synthesize extraPost=_extraPost;
@property(retain, nonatomic) NSArray *hideSourceButtons; // @synthesize hideSourceButtons=_hideSourceButtons;
@property(retain, nonatomic) UIButton *restoreButton; // @synthesize restoreButton=_restoreButton;
@property(retain, nonatomic) UILabel *debugLabel; // @synthesize debugLabel=_debugLabel;
@property(retain, nonatomic) UIButton *authorButton; // @synthesize authorButton=_authorButton;
@property(retain, nonatomic) BackupImageView *authorImage; // @synthesize authorImage=_authorImage;
@property(retain, nonatomic) UIButton *showFullButton; // @synthesize showFullButton=_showFullButton;
@property(retain, nonatomic) UIImageView *repostLine; // @synthesize repostLine=_repostLine;
@property(retain, nonatomic) TitleNameButton *repostOfRepostView; // @synthesize repostOfRepostView=_repostOfRepostView;
@property(retain, nonatomic) TitleNameButton *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) VKPost *currentPost; // @synthesize currentPost=_currentPost;
@property(nonatomic) unsigned long long postLocation; // @synthesize postLocation=_postLocation;
@property(retain, nonatomic) PostCommentsView *commentsView; // @synthesize commentsView=_commentsView;
@property(retain, nonatomic, getter=getCopyPostView) PostView *copyPostView; // @synthesize copyPostView=_copyPostView;
@property(nonatomic) _Bool dontTrackStats; // @synthesize dontTrackStats=_dontTrackStats;
@property(nonatomic) _Bool isActionsButtonHidden; // @synthesize isActionsButtonHidden=_isActionsButtonHidden;
@property(nonatomic) UIColor *timeColor; // @synthesize timeColor=_timeColor;
@property(nonatomic) _Bool forceExpand; // @synthesize forceExpand=_forceExpand;
@property(nonatomic) _Bool isParentHasText; // @synthesize isParentHasText=_isParentHasText;
@property(nonatomic) _Bool isCopy; // @synthesize isCopy=_isCopy;
@property(nonatomic) _Bool isFixedPost; // @synthesize isFixedPost=_isFixedPost;
@property(nonatomic) _Bool isWallCell; // @synthesize isWallCell=_isWallCell;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) UIFastLabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIImageView *background; // @synthesize background=_background;
@property(retain, nonatomic) ChatAttachView *attachView; // @synthesize attachView=_attachView;
@property(nonatomic) __weak UIButtonHL *shareButton; // @synthesize shareButton=_shareButton;
@property(nonatomic) __weak id <PostViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)adsButtonPressed:(id)arg1;
- (void)setPostLocation:(unsigned long long)arg1 forceNewsfeed:(_Bool)arg2;
- (void)restoreRemovedPost;
@property(nonatomic) UIImage *backgroundImage;
@property(nonatomic, setter=setCommentsViewHidden:) _Bool isCommentsViewHidden; // @synthesize isCommentsViewHidden=_isCommentsViewHidden;
@property(nonatomic, setter=setBackgroundHidden:) _Bool isBackgroundHidden; // @synthesize isBackgroundHidden=_isBackgroundHidden;
- (struct CGRect)convertFrameFromCommentsView:(struct CGRect)arg1;
- (void)translateToDelegate:(id)arg1;
- (void)updateButtons:(_Bool)arg1;
- (void)updateButtons;
- (void)setTitle:(id)arg1 forAds:(id)arg2;
- (void)setTitle:(id)arg1 forPost:(id)arg2;
- (void)setPost:(id)arg1;
- (void)relayoutSubviews;
- (void)setFrameForCurrentLocation;
- (void)showEverything;
- (void)hideAnythingExceptBackground;
- (void)likesCountChanged:(id)arg1;
- (void)createTitleView:(struct CGRect)arg1;
- (void)dealloc;
- (void)createLayout:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 isCopyView:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

