//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSIndexPath, UILabel, UITableView;

@interface ProfileSectionHeader : UIControl
{
    _Bool _highlightDisabled;
    UILabel *_header;
    UILabel *_counter;
    long long _counterOffsetX;
    NSIndexPath *_currentIndexPath;
    UITableView *_table;
}

+ (id)newWithTable:(id)arg1 indexPath:(id)arg2;
@property(nonatomic) __weak UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(nonatomic) _Bool highlightDisabled; // @synthesize highlightDisabled=_highlightDisabled;
@property(nonatomic) long long counterOffsetX; // @synthesize counterOffsetX=_counterOffsetX;
@property(retain, nonatomic) UILabel *counter; // @synthesize counter=_counter;
@property(retain, nonatomic) UILabel *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (void)build;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (id)createSectionHeaderCounter;
- (id)createSectionHeader;
- (id)prepare;

@end

