//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingsSection.h"

@class NSArray;

@interface PushSection : SettingsSection
{
    NSArray *_irows;
}

- (void).cxx_destruct;
- (void)invalidate;
- (id)rows;
- (id)footer;
- (id)title;

@end

