//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewDelegate.h"

@class NSIndexPath;

@protocol RFQuiltLayoutDelegate <UICollectionViewDelegate>

@optional
- (struct UIEdgeInsets)insetsForItemAtIndexPath:(NSIndexPath *)arg1;
- (struct CGSize)blockSizeForItemAtIndexPath:(NSIndexPath *)arg1;
@end

