//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface RuleSet : NSObject
{
    _Bool _hasRuleWithIntlPrefix;
    _Bool _hasRuleWithTrunkPrefix;
    int _matchLen;
    NSMutableArray *_rules;
}

@property(nonatomic) _Bool hasRuleWithTrunkPrefix; // @synthesize hasRuleWithTrunkPrefix=_hasRuleWithTrunkPrefix;
@property(nonatomic) _Bool hasRuleWithIntlPrefix; // @synthesize hasRuleWithIntlPrefix=_hasRuleWithIntlPrefix;
@property(retain, nonatomic) NSMutableArray *rules; // @synthesize rules=_rules;
@property(nonatomic) int matchLen; // @synthesize matchLen=_matchLen;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isValid:(id)arg1 intlPrefix:(id)arg2 trunkPrefix:(id)arg3 prefixRequired:(_Bool)arg4;
- (id)format:(id)arg1 intlPrefix:(id)arg2 trunkPrefix:(id)arg3 prefixRequired:(_Bool)arg4;

@end

