//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, NSTimer, StickersShopController, UIButton, UICollectionView, UINavigationBar, UINavigationItem, UIPageControl, VKStoreBanners;

@interface ShopBannersView : UICollectionReusableView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    UIPageControl *_pageControl;
    UICollectionView *_bannersCollection;
    UIButton *_closeButton;
    VKStoreBanners *_banners;
    UINavigationItem *_navigationItem;
    UINavigationBar *_navigationBar;
    StickersShopController *_parent;
    NSTimer *_pageTimer;
}

@property(nonatomic) __weak NSTimer *pageTimer; // @synthesize pageTimer=_pageTimer;
@property(nonatomic) __weak StickersShopController *parent; // @synthesize parent=_parent;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(retain, nonatomic) UINavigationItem *navigationItem; // @synthesize navigationItem=_navigationItem;
@property(nonatomic) __weak VKStoreBanners *banners; // @synthesize banners=_banners;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UICollectionView *bannersCollection; // @synthesize bannersCollection=_bannersCollection;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
- (void).cxx_destruct;
- (void)stop;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)flipPage;
- (void)pageSelected:(id)arg1;
- (void)startNextPageTimer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

