//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VideoTableDataSource.h"

@interface SimpleVideoTableDataSource : VideoTableDataSource
{
}

- (id)initWithTaggedPhotosForUser:(id)arg1;
- (id)initWithOwnerId:(id)arg1 albumId:(id)arg2;

@end

