//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FixedCollectionViewCell.h"

@class AnyCounter, BackupImageView, GraySeparatorView, KAProgressLabel, NSNumber, UIActivityIndicatorView;

@interface SmilesBottomCell : FixedCollectionViewCell
{
    id progressObserver;
    BackupImageView *_bottomImageView;
    AnyCounter *_shopBadge;
    UIActivityIndicatorView *_activityIndicator;
    KAProgressLabel *_roundProgress;
    GraySeparatorView *_leftGray;
    GraySeparatorView *_rightGray;
    NSNumber *_productId;
}

@property(retain, nonatomic) NSNumber *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) GraySeparatorView *rightGray; // @synthesize rightGray=_rightGray;
@property(retain, nonatomic) GraySeparatorView *leftGray; // @synthesize leftGray=_leftGray;
@property(retain, nonatomic) KAProgressLabel *roundProgress; // @synthesize roundProgress=_roundProgress;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) AnyCounter *shopBadge; // @synthesize shopBadge=_shopBadge;
@property(retain, nonatomic) BackupImageView *bottomImageView; // @synthesize bottomImageView=_bottomImageView;
- (void).cxx_destruct;
- (void)setProgress:(double)arg1;
- (void)setActivityIndicatorHidden:(_Bool)arg1;
- (void)createShopBadgeIfNecessary;
- (id)initWithFrame:(struct CGRect)arg1;

@end

