//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SmilesViewController, UIView;

@protocol SmilesViewDelegate <NSObject>
- (UIView *)collectionControllerRootWindow:(SmilesViewController *)arg1;
- (void)collectionControllerShouldBecomeFirstResponder:(SmilesViewController *)arg1;
- (void)collectionControllerShouldOpenStickersShop:(SmilesViewController *)arg1;
- (void)collectionControllerBackspace:(SmilesViewController *)arg1;
- (void)collectionControllerShowSystemKeyboard:(SmilesViewController *)arg1;
- (_Bool)collectionControllerShouldHide:(SmilesViewController *)arg1;
- (void)collectionController:(SmilesViewController *)arg1 didSelectObject:(id)arg2;
@end

