//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SQDB : NSObject
{
    NSString *dbpath;
    struct sqlite3 *db;
}

- (void).cxx_destruct;
- (_Bool)bindData:(id)arg1 andData:(id)arg2;
- (long long)getLastInsertedId;
- (void)commitTransaction;
- (void)beginTransaction;
- (void)rollbackTransaction;
- (id)getBlobEntry:(id)arg1;
- (id)getStringEntry:(id)arg1;
- (double)getFloatEntry:(id)arg1;
- (long long)getIntEntry:(id)arg1;
- (id)resultsOfQuery:(id)arg1;
- (_Bool)executeQuery:(id)arg1;
- (_Bool)executeSimpleQuery:(id)arg1;
- (long long)open:(id)arg1 version:(long long)arg2;
- (id)documentsPath;
- (void)closeAndDelete;
- (void)dealloc;

@end

