//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "StatEvent.h"

@class NSString;

@interface StatEventVideoPlay : StatEvent
{
    NSString *_video_id;
    NSString *_quality;
    NSString *_position;
    NSString *_source;
}

@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *quality; // @synthesize quality=_quality;
@property(copy, nonatomic) NSString *video_id; // @synthesize video_id=_video_id;
- (void).cxx_destruct;
- (id)serialize;
- (id)init;

@end

