//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class StickersShopController;

@protocol StickersShopControllerDelegate <NSObject>

@optional
- (void)stickersShopDidHide:(StickersShopController *)arg1;
- (void)stickersShopWillHide:(StickersShopController *)arg1;
- (void)stickersShopDidAppear:(StickersShopController *)arg1;
- (void)stickersShopWillAppear:(StickersShopController *)arg1;
@end

