//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISelectiveBorderView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class ClearRectCollectionView, LRUCache, NSString, UIButton;

@interface StickersBottomPanel : UISelectiveBorderView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    _Bool _backspaceButtonVisible;
    UIButton *_normalKeyboardButton;
    UIButton *_hideKeyboarButton;
    UIButton *_backspaceButton;
    ClearRectCollectionView *_bottomCollection;
    LRUCache *_imgCache;
}

@property(retain, nonatomic) LRUCache *imgCache; // @synthesize imgCache=_imgCache;
@property(retain, nonatomic) ClearRectCollectionView *bottomCollection; // @synthesize bottomCollection=_bottomCollection;
@property(nonatomic) _Bool backspaceButtonVisible; // @synthesize backspaceButtonVisible=_backspaceButtonVisible;
@property(retain, nonatomic) UIButton *backspaceButton; // @synthesize backspaceButton=_backspaceButton;
@property(retain, nonatomic) UIButton *hideKeyboarButton; // @synthesize hideKeyboarButton=_hideKeyboarButton;
@property(retain, nonatomic) UIButton *normalKeyboardButton; // @synthesize normalKeyboardButton=_normalKeyboardButton;
- (void).cxx_destruct;
- (void)selectItem:(long long)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)reloadData;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

