//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKAlbums, VKGroups, VKUsers, video_get_res;

@interface stored_getVideos_res : VKResponse
{
    video_get_res *_videos;
    VKAlbums *_albums;
    VKUsers *_users;
    VKGroups *_groups;
}

@property(retain, nonatomic) VKGroups *groups; // @synthesize groups=_groups;
@property(retain, nonatomic) VKUsers *users; // @synthesize users=_users;
@property(retain, nonatomic) VKAlbums *albums; // @synthesize albums=_albums;
@property(retain, nonatomic) video_get_res *videos; // @synthesize videos=_videos;
- (void).cxx_destruct;

@end

