//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSArray;

@interface stored_getAlbumsForVideo_res : VKResponse
{
    NSArray *_user_albums;
    NSArray *_target_albums;
}

@property(retain, nonatomic) NSArray *target_albums; // @synthesize target_albums=_target_albums;
@property(retain, nonatomic) NSArray *user_albums; // @synthesize user_albums=_user_albums;
- (void).cxx_destruct;

@end

