//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface store_reorderProducts_req : VKRequest
{
    NSString *_type;
    NSNumber *_product_id;
    NSNumber *_before;
    NSNumber *_after;
}

@property(retain, nonatomic) NSNumber *after; // @synthesize after=_after;
@property(retain, nonatomic) NSNumber *before; // @synthesize before=_before;
@property(retain, nonatomic) NSNumber *product_id; // @synthesize product_id=_product_id;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

