//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber;

@interface store_request : VKRequest
{
    NSNumber *_no_inapp;
    NSNumber *_force_inapp;
}

@property(retain, nonatomic) NSNumber *force_inapp; // @synthesize force_inapp=_force_inapp;
@property(retain, nonatomic) NSNumber *no_inapp; // @synthesize no_inapp=_no_inapp;
- (void).cxx_destruct;

@end

