//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKObjectsArray, VKUsers, likes_isLiked_res;

@interface stored_loadLikesForPost_res : VKResponse
{
    VKUsers *_profiles;
    VKObjectsArray *_likes;
    VKObjectsArray *_reposts;
    likes_isLiked_res *_user_likes;
}

@property(retain, nonatomic) likes_isLiked_res *user_likes; // @synthesize user_likes=_user_likes;
@property(retain, nonatomic) VKObjectsArray *reposts; // @synthesize reposts=_reposts;
@property(retain, nonatomic) VKObjectsArray *likes; // @synthesize likes=_likes;
@property(retain, nonatomic) VKUsers *profiles; // @synthesize profiles=_profiles;
- (void).cxx_destruct;

@end

