//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, VKAudios, VKCities, VKCountries, VKFriendRequest, VKMixedUsersGroups, VKPhotoAlbums, VKPhotos, VKUser, VKUsers, VKVideos, wall_get_res;

@interface stored_loadUser5_0i_res : VKResponse
{
    VKUser *_full;
    NSNumber *_docs_count;
    VKUsers *_relative_users;
    VKUser *_relation_partner;
    VKCities *_cities;
    VKPhotos *_profile_photos;
    VKFriendRequest *_is_friend;
    NSNumber *_saved_photos;
    NSNumber *_tag_photos;
    NSNumber *_wall_photos;
    VKUsers *_friends;
    VKUsers *_mutual;
    VKMixedUsersGroups *_pages;
    VKPhotoAlbums *_albums;
    VKVideos *_videos;
    VKAudios *_audios;
    VKCountries *_countries;
    wall_get_res *_wall1;
    wall_get_res *_wall2;
    NSNumber *_is_adult;
}

@property(retain, nonatomic) NSNumber *is_adult; // @synthesize is_adult=_is_adult;
@property(retain, nonatomic) wall_get_res *wall2; // @synthesize wall2=_wall2;
@property(retain, nonatomic) wall_get_res *wall1; // @synthesize wall1=_wall1;
@property(retain, nonatomic) VKCountries *countries; // @synthesize countries=_countries;
@property(retain, nonatomic) VKAudios *audios; // @synthesize audios=_audios;
@property(retain, nonatomic) VKVideos *videos; // @synthesize videos=_videos;
@property(retain, nonatomic) VKPhotoAlbums *albums; // @synthesize albums=_albums;
@property(retain, nonatomic) VKMixedUsersGroups *pages; // @synthesize pages=_pages;
@property(retain, nonatomic) VKUsers *mutual; // @synthesize mutual=_mutual;
@property(retain, nonatomic) VKUsers *friends; // @synthesize friends=_friends;
@property(retain, nonatomic) NSNumber *wall_photos; // @synthesize wall_photos=_wall_photos;
@property(retain, nonatomic) NSNumber *tag_photos; // @synthesize tag_photos=_tag_photos;
@property(retain, nonatomic) NSNumber *saved_photos; // @synthesize saved_photos=_saved_photos;
@property(retain, nonatomic) VKFriendRequest *is_friend; // @synthesize is_friend=_is_friend;
@property(retain, nonatomic) VKPhotos *profile_photos; // @synthesize profile_photos=_profile_photos;
@property(retain, nonatomic) VKCities *cities; // @synthesize cities=_cities;
@property(retain, nonatomic) VKUser *relation_partner; // @synthesize relation_partner=_relation_partner;
@property(retain, nonatomic) VKUsers *relative_users; // @synthesize relative_users=_relative_users;
@property(retain, nonatomic) NSNumber *docs_count; // @synthesize docs_count=_docs_count;
@property(retain, nonatomic) VKUser *full; // @synthesize full=_full;
- (void).cxx_destruct;

@end

