//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, VKMessages, VKUsers;

@interface stored_getMessagesHistory_res : VKResponse
{
    VKUsers *_users;
    NSNumber *_time;
    VKMessages *_messages;
}

@property(retain, nonatomic) VKMessages *messages; // @synthesize messages=_messages;
@property(retain, nonatomic) NSNumber *time; // @synthesize time=_time;
@property(retain, nonatomic) VKUsers *users; // @synthesize users=_users;
- (void).cxx_destruct;

@end

