//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, VKCounters, VKDialogs, VKUsers;

@interface stored_getDialogs_res : VKResponse
{
    VKUsers *_users;
    VKUsers *_chat_users;
    NSNumber *_time;
    VKCounters *_counters;
    VKDialogs *_dialogs;
}

@property(retain, nonatomic) VKDialogs *dialogs; // @synthesize dialogs=_dialogs;
@property(retain, nonatomic) VKCounters *counters; // @synthesize counters=_counters;
@property(retain, nonatomic) NSNumber *time; // @synthesize time=_time;
@property(retain, nonatomic) VKUsers *chat_users; // @synthesize chat_users=_chat_users;
@property(retain, nonatomic) VKUsers *users; // @synthesize users=_users;
- (void).cxx_destruct;

@end

