//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKComments, VKGroups, VKUsers;

@interface stored_loadWallComments_res : VKResponse
{
    VKComments *_post_comments;
    VKComments *_comments;
    VKUsers *_users;
    VKUsers *_reply_to_users;
    VKGroups *_groups;
}

@property(retain, nonatomic) VKGroups *groups; // @synthesize groups=_groups;
@property(retain, nonatomic) VKUsers *reply_to_users; // @synthesize reply_to_users=_reply_to_users;
@property(retain, nonatomic) VKUsers *users; // @synthesize users=_users;
@property(retain, nonatomic) VKComments *comments; // @synthesize comments=_comments;
@property(retain, nonatomic) VKComments *post_comments; // @synthesize post_comments=_post_comments;
- (void).cxx_destruct;

@end

