//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKFriendRequestArray, VKUsers;

@interface stored_getFriendRequests_res : VKResponse
{
    VKUsers *_users;
    VKFriendRequestArray *_friend_requests;
}

@property(retain, nonatomic) VKFriendRequestArray *friend_requests; // @synthesize friend_requests=_friend_requests;
@property(retain, nonatomic) VKUsers *users; // @synthesize users=_users;
- (void).cxx_destruct;

@end

