//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, iPadNewsViewController;

@interface TimerListener : NSObject
{
    _Bool _paused;
    NSTimer *_updateTimer;
    iPadNewsViewController *_controller;
}

@property(nonatomic) _Bool paused; // @synthesize paused=_paused;
@property(nonatomic) __weak iPadNewsViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
- (void).cxx_destruct;
- (void)terminate;
- (void)schedule;
- (void)fireTimerEvent;

@end

