//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BackupImageView, UIButtonHL, UIImageView, UILabel;

@interface TitleNameButton : UIView
{
    UIButtonHL *_basicButton;
    BackupImageView *_avatar1Image;
    UILabel *_nameLabel;
    UILabel *_timeLabel;
    UIImageView *_forFriendsPostImage;
    UIButtonHL *_actionsButton;
    UIButtonHL *_closeButton;
    UIButtonHL *_detailsButton;
    UIImageView *_repostImage;
}

@property(retain, nonatomic) UIImageView *repostImage; // @synthesize repostImage=_repostImage;
@property(retain, nonatomic) UIButtonHL *detailsButton; // @synthesize detailsButton=_detailsButton;
@property(retain, nonatomic) UIButtonHL *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIButtonHL *actionsButton; // @synthesize actionsButton=_actionsButton;
@property(retain, nonatomic) UIImageView *forFriendsPostImage; // @synthesize forFriendsPostImage=_forFriendsPostImage;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) BackupImageView *avatar1Image; // @synthesize avatar1Image=_avatar1Image;
@property(retain, nonatomic) UIButtonHL *basicButton; // @synthesize basicButton=_basicButton;
- (void).cxx_destruct;
- (void)finish;
- (void)positionButtons;
- (void)setIsDetailed:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 isCopy:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

