//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TwitterTextEntity : NSObject
{
    int _type;
    struct _NSRange _range;
}

+ (id)entityWithType:(int)arg1 range:(struct _NSRange)arg2;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
@property(nonatomic) int type; // @synthesize type=_type;
- (id)description;
- (long long)compare:(id)arg1;
- (id)initWithType:(int)arg1 range:(struct _NSRange)arg2;

@end

