//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "UIGestureRecognizerDelegate.h"

@class FastAttributedString, FastAttributedStringCustomLink, NSString;

@interface UIFastLabel : UIControl <UIGestureRecognizerDelegate>
{
    struct __CTFramesetter *framesetter;
    FastAttributedStringCustomLink *clickResult;
    struct CGPoint startPoint;
    _Bool ignoreGestures;
    FastAttributedString *attrString;
    id <UIFastLabelDelegate> delegate;
    long long drawOrientation;
}

+ (id)buildAttributedString:(id)arg1 withFont:(id)arg2 andCustomLinks:(id)arg3 leading:(float)arg4 leading2:(float)arg5;
+ (id)buildAttributedString:(id)arg1 withFont:(id)arg2 andCustomLinks:(id)arg3 leading:(float)arg4;
+ (id)decodeFromPercentEscapeString:(id)arg1;
+ (struct FastAttributedStringSize)calculateSizeForAttributedString:(id)arg1 withMaxPortraitWidth:(float)arg2 andMaxLandscapeWidth:(float)arg3 withTruncation:(_Bool)arg4;
+ (void)createTextAttributes;
@property(nonatomic) _Bool ignoreGestures; // @synthesize ignoreGestures;
@property(nonatomic) long long drawOrientation; // @synthesize drawOrientation;
@property(nonatomic) id <UIFastLabelDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) FastAttributedString *attrString; // @synthesize attrString;
- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)endTouches:(id)arg1 canceled:(_Bool)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (long long)characterIndexAtPoint:(struct CGPoint)arg1;
- (id)linkAtPoint:(struct CGPoint)arg1;
- (id)linkAtCharacterIndex:(long long)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)invalidate;
- (void)setNeedsDisplay;
- (void)setFramesetter:(struct __CTFramesetter *)arg1;
- (void)setTextColor:(id)arg1 withLinks:(_Bool)arg2;
- (void)setHighlightedTable:(_Bool)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

