//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface UIOverlayWindow : UIWindow
{
    _Bool _willHide;
    _Bool _shouldDecrementWindowLevel;
    _Bool _didSetViewController;
}

+ (id)createNewOne;
+ (id)createNewOne:(double)arg1;
@property(nonatomic) _Bool didSetViewController; // @synthesize didSetViewController=_didSetViewController;
@property(nonatomic) _Bool shouldDecrementWindowLevel; // @synthesize shouldDecrementWindowLevel=_shouldDecrementWindowLevel;
@property(nonatomic) _Bool willHide; // @synthesize willHide=_willHide;
- (void)makeKeyAndVisible;
- (void)setHidden:(_Bool)arg1;
- (void)sendHideToVc:(id)arg1;
- (void)hideWindow;
- (void)closeWindow;
- (void)dealloc;
- (void)setRootViewController:(id)arg1;

@end

