//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSString, UIColor, UILabel, UIScrollView, UIView;

@interface UITextViewAttach : UITextView
{
    UIScrollView *_attachScrollView;
    UIView *_attachScrollViewContainer;
    NSString *_placeholder;
    UIColor *_placeholderColor;
    UILabel *_placeHolderLabel;
}

@property(retain, nonatomic) UILabel *placeHolderLabel; // @synthesize placeHolderLabel=_placeHolderLabel;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(retain, nonatomic) UIView *attachScrollViewContainer; // @synthesize attachScrollViewContainer=_attachScrollViewContainer;
@property(retain, nonatomic) UIScrollView *attachScrollView; // @synthesize attachScrollView=_attachScrollView;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setText:(id)arg1;
- (void)textChanged:(id)arg1;
- (void)tap:(id)arg1;
- (void)setContentSize:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

