//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AUISelectiveBordersLayer, UIColor;

@interface UIView (Selective)
@property(nonatomic) float selectiveBordersWidth;
@property(retain, nonatomic) UIColor *selectiveBordersColor;
@property(nonatomic) unsigned long long selectiveBorderDrawLocation;
@property(nonatomic) unsigned long long selectiveBorderFlag;
@property(readonly) AUISelectiveBordersLayer *selectiveBordersLayer;
@end

