//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (TKGeometry)
- (void)setYCenter:(double)arg1;
- (double)yCenter;
- (void)setXCenter:(double)arg1;
- (double)xCenter;
- (double)maxY;
- (void)setMaxY:(double)arg1;
- (double)maxX;
- (void)setMaxX:(double)arg1;
- (void)setYOrigin:(double)arg1;
- (double)yOrigin;
- (void)setXOrigin:(double)arg1;
- (double)xOrigin;
- (void)setWidth:(double)arg1;
- (double)width;
- (void)setHeight:(double)arg1;
- (double)height;
- (void)setSize:(struct CGSize)arg1;
- (struct CGSize)size;
- (void)setOrigin:(struct CGPoint)arg1;
- (struct CGPoint)origin;
@end

