//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSDictionary, NSOperation, VKRequest;

@interface UploadVideoObject : VKObject
{
    _Bool _isCanceled;
    VKRequest *_saveRequest;
    NSOperation *_saveOperation;
    NSDictionary *_userInfo;
    CDUnknownBlockType _completeBlock;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _failedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType failedBlock; // @synthesize failedBlock=_failedBlock;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(copy, nonatomic) CDUnknownBlockType completeBlock; // @synthesize completeBlock=_completeBlock;
@property(nonatomic) _Bool isCanceled; // @synthesize isCanceled=_isCanceled;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSOperation *saveOperation; // @synthesize saveOperation=_saveOperation;
@property(retain, nonatomic) VKRequest *saveRequest; // @synthesize saveRequest=_saveRequest;
- (void).cxx_destruct;
- (void)cancel;

@end

