//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKMixedUsersGroups;

@interface users_getSubscriptions_res : VKResponse
{
    VKMixedUsersGroups *_response;
}

@property(retain, nonatomic) VKMixedUsersGroups *response; // @synthesize response=_response;
- (void).cxx_destruct;

@end

