//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "Nameable.h"
#import "Photoable.h"

@class NSNumber, NSString;

@protocol Userable <Nameable, Photoable, NSObject>
@property(readonly, nonatomic) NSNumber *is_adult;
@property(readonly, nonatomic) NSNumber *sex;
@property(readonly, copy, nonatomic) NSString *placeholder60;
@property(readonly, copy, nonatomic) NSString *placeholder55;
@property(readonly, copy, nonatomic) NSString *placeholder50;
@property(readonly, copy, nonatomic) NSString *status;
@property(readonly, copy, nonatomic) NSString *activity;
@property(readonly, copy, nonatomic) NSString *deactivated;
@end

