//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSString;

@interface users_get_req : VKRequest
{
    NSString *_user_ids;
    NSString *_fields;
    NSString *_name_case;
}

@property(copy, nonatomic) NSString *name_case; // @synthesize name_case=_name_case;
@property(copy, nonatomic) NSString *fields; // @synthesize fields=_fields;
@property(copy, nonatomic) NSString *user_ids; // @synthesize user_ids=_user_ids;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;
- (id)serialize;

@end

