//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PostMenuController.h"

@class VKVideo;

@interface VideoMenuController : PostMenuController
{
    VKVideo *_currentVideo;
}

@property(retain, nonatomic) VKVideo *currentVideo; // @synthesize currentVideo=_currentVideo;
- (void).cxx_destruct;
- (id)copy;
- (id)currentAttachable;
- (void)makeMenuSelectionProcessWithAction:(id)arg1;
- (id)initWithVideo:(id)arg1;
- (void)performReportActionWithReason:(unsigned long long)arg1;
- (void)performDeleteAction;

@end

