//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, NSString;

@interface video_save_res : VKResponse
{
    NSString *_upload_url;
    NSNumber *_video_id;
    NSString *_title;
    NSString *_Mdescription;
    NSNumber *_owner_id;
    NSString *_access_key;
}

@property(copy, nonatomic) NSString *access_key; // @synthesize access_key=_access_key;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(copy, nonatomic) NSString *Mdescription; // @synthesize Mdescription=_Mdescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *video_id; // @synthesize video_id=_video_id;
@property(copy, nonatomic) NSString *upload_url; // @synthesize upload_url=_upload_url;
- (void).cxx_destruct;

@end

