//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AbstractTableDataSource.h"

#import "AbstractSectionDataSourceDelegate.h"

@class GlobalVideoSearchContentSection, NSArray, NSNumber, NSString, VideoAlbumsSection, VideoContentSection;

@interface VideoTableDataSource : AbstractTableDataSource <AbstractSectionDataSourceDelegate>
{
    _Bool onlyUploadedSelected;
    _Bool _isAdmin;
    _Bool _searchGlobal;
    _Bool _shouldLoadTaggedPhotos;
    NSArray *_currentSectionsRw;
    NSArray *_searchSectionsRw;
    VideoContentSection *_videoDataSource;
    VideoAlbumsSection *_videoAlbumsSource;
    VideoContentSection *_localSearchSection;
    GlobalVideoSearchContentSection *_globalSearchSection;
    long long *_searchFilters;
    NSNumber *_albumId;
    NSNumber *_ownerId;
    long long _pagesLoaded;
    long long _searchPagesLoaded;
}

@property(nonatomic) long long searchPagesLoaded; // @synthesize searchPagesLoaded=_searchPagesLoaded;
@property(nonatomic) long long pagesLoaded; // @synthesize pagesLoaded=_pagesLoaded;
@property(nonatomic) _Bool shouldLoadTaggedPhotos; // @synthesize shouldLoadTaggedPhotos=_shouldLoadTaggedPhotos;
@property(retain, nonatomic) NSNumber *ownerId; // @synthesize ownerId=_ownerId;
@property(retain, nonatomic) NSNumber *albumId; // @synthesize albumId=_albumId;
@property(nonatomic) long long *searchFilters; // @synthesize searchFilters=_searchFilters;
@property(retain, nonatomic) GlobalVideoSearchContentSection *globalSearchSection; // @synthesize globalSearchSection=_globalSearchSection;
@property(retain, nonatomic) VideoContentSection *localSearchSection; // @synthesize localSearchSection=_localSearchSection;
@property(retain, nonatomic) VideoAlbumsSection *videoAlbumsSource; // @synthesize videoAlbumsSource=_videoAlbumsSource;
@property(retain, nonatomic) VideoContentSection *videoDataSource; // @synthesize videoDataSource=_videoDataSource;
@property(nonatomic) _Bool searchGlobal; // @synthesize searchGlobal=_searchGlobal;
@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
@property(retain, nonatomic) NSArray *searchSections; // @synthesize searchSections=_searchSectionsRw;
@property(retain, nonatomic) NSArray *currentSections; // @synthesize currentSections=_currentSectionsRw;
- (void).cxx_destruct;
- (void)updateVideoAlbum:(id)arg1;
- (void)albumRemoved:(id)arg1;
- (void)albumCreated:(id)arg1;
- (void)checkForEmptiness;
- (void)removeVideoByAttachmentString:(id)arg1;
- (_Bool)removeVideo:(id)arg1;
- (_Bool)addVideo:(id)arg1;
- (_Bool)hasVideo:(id)arg1;
- (id)objectForIndexPath:(id)arg1;
- (_Bool)canSearch;
- (void)endSearch;
- (void)searchGlobal:(long long)arg1;
- (void)setSearchString:(id)arg1;
- (void)startSearch;
- (void)finishLoadingAlbums;
- (void)finishLoading;
- (void)tableSection:(id)arg1 selectorClicked:(id)arg2;
- (void)tableSectionActivityIndicatorReached:(id)arg1;
- (void)reloadAll;
- (void)loadNextAlbums;
- (void)loadNextDataBlock;
- (void)checkOwnerHasUploadedVideos;
@property(readonly, nonatomic) _Bool isLoading;
- (void)dealloc;
- (id)initWithTaggedPhotosForUser:(id)arg1;
- (id)initWithOwnerId:(id)arg1 albumId:(id)arg2;
- (void)setSimplify:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

