//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface video_report_req : VKRequest
{
    NSNumber *_owner_id;
    NSNumber *_video_id;
    NSNumber *_reason;
    NSString *_comment;
    NSString *_search_query;
}

@property(copy, nonatomic) NSString *search_query; // @synthesize search_query=_search_query;
@property(copy, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) NSNumber *reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSNumber *video_id; // @synthesize video_id=_video_id;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

