//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSString;

@interface VKAdsIosApp : VKObject
{
    NSString *_app_id;
    NSString *_open_url;
}

@property(copy, nonatomic) NSString *open_url; // @synthesize open_url=_open_url;
@property(copy, nonatomic) NSString *app_id; // @synthesize app_id=_app_id;
- (void).cxx_destruct;

@end

