//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKEventsTracker.h"

@class NSMutableArray, NSOperationQueue;

@interface VKAdsTracker : VKEventsTracker
{
    NSOperationQueue *_statsOperationQueue;
    NSMutableArray *_untrackedStats;
}

+ (void)identifierForAdvertising:(CDUnknownBlockType)arg1;
@property(retain) NSMutableArray *untrackedStats; // @synthesize untrackedStats=_untrackedStats;
@property(retain, nonatomic) NSOperationQueue *statsOperationQueue; // @synthesize statsOperationQueue=_statsOperationQueue;
- (void).cxx_destruct;
- (void)trackStats:(id)arg1 withType:(id)arg2;
- (void)flush;
- (void)sendEventsString:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)trackOpenApp:(id)arg1;
- (void)trackOpenUrl:(id)arg1;
- (void)trackOpenInstall:(id)arg1;
- (void)trackImpression:(id)arg1;
- (void)finishAdEvent:(id)arg1;
- (id)init;

@end

