//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber, NSString;

@interface VKAlbum : VKObject
{
    NSNumber *_id;
    NSNumber *_owner_id;
    NSNumber *_count;
    NSNumber *_privacy;
    NSNumber *_updated_time;
    NSString *_title;
    NSString *_photo_160;
    NSString *_photo_320;
}

@property(copy, nonatomic) NSString *photo_320; // @synthesize photo_320=_photo_320;
@property(copy, nonatomic) NSString *photo_160; // @synthesize photo_160=_photo_160;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *updated_time; // @synthesize updated_time=_updated_time;
@property(retain, nonatomic) NSNumber *privacy; // @synthesize privacy=_privacy;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

