//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObjectsArray.h"

@interface VKAttachmentsArray : VKObjectsArray
{
}

- (long long)countAttachmentsOfType:(id)arg1;
- (id)getAttachmentOfType:(id)arg1;
- (int)valueOfAttachment:(id)arg1;
- (void)sort;
- (Class)objectClass;

@end

