//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObjectsArray.h"

@class NSNumber;

@interface VKComments : VKObjectsArray
{
    NSNumber *_can_post;
}

@property(retain, nonatomic) NSNumber *can_post; // @synthesize can_post=_can_post;
- (void).cxx_destruct;
- (id)serialize;
- (Class)objectClass;

@end

