//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "VKSizeable.h"

@class FastAttributedString, NSNumber, NSString, VKAttachmentsArray, VKLikes, VKPhoto, VKPost, VKTopic, VKVideo;

@interface VKComment : VKObject <VKSizeable>
{
    int _type;
    float _heightPost;
    float _heightRepost;
    float _attachHeight;
    NSNumber *_id;
    NSNumber *_from_id;
    NSNumber *_date;
    NSString *_text;
    NSString *_send_text;
    NSNumber *_user_id;
    NSNumber *_reply_to_user;
    NSNumber *_reply_to_comment;
    VKAttachmentsArray *_attachments;
    NSNumber *_can_edit;
    NSString *_message;
    NSNumber *_post_id;
    NSNumber *_owner_id;
    VKLikes *_likes;
    VKPost *_post;
    VKPhoto *_photo;
    VKVideo *_video;
    VKTopic *_topic;
    NSNumber *_prevent_calculate;
    FastAttributedString *_fullCommentString;
    NSNumber *_sentStickerId;
    struct FastAttributedStringSize _fullCommentSize;
}

@property(retain, nonatomic) NSNumber *sentStickerId; // @synthesize sentStickerId=_sentStickerId;
@property(retain, nonatomic) FastAttributedString *fullCommentString; // @synthesize fullCommentString=_fullCommentString;
@property(nonatomic) struct FastAttributedStringSize fullCommentSize; // @synthesize fullCommentSize=_fullCommentSize;
@property(nonatomic) float attachHeight; // @synthesize attachHeight=_attachHeight;
@property(nonatomic) float heightRepost; // @synthesize heightRepost=_heightRepost;
@property(nonatomic) float heightPost; // @synthesize heightPost=_heightPost;
@property(retain, nonatomic) NSNumber *prevent_calculate; // @synthesize prevent_calculate=_prevent_calculate;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) VKTopic *topic; // @synthesize topic=_topic;
@property(retain, nonatomic) VKVideo *video; // @synthesize video=_video;
@property(retain, nonatomic) VKPhoto *photo; // @synthesize photo=_photo;
@property(retain, nonatomic) VKPost *post; // @synthesize post=_post;
@property(retain, nonatomic) VKLikes *likes; // @synthesize likes=_likes;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *post_id; // @synthesize post_id=_post_id;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSNumber *can_edit; // @synthesize can_edit=_can_edit;
@property(retain, nonatomic) VKAttachmentsArray *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) NSNumber *reply_to_comment; // @synthesize reply_to_comment=_reply_to_comment;
@property(retain, nonatomic) NSNumber *reply_to_user; // @synthesize reply_to_user=_reply_to_user;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
@property(copy, nonatomic) NSString *send_text; // @synthesize send_text=_send_text;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSNumber *date; // @synthesize date=_date;
@property(retain, nonatomic) NSNumber *from_id; // @synthesize from_id=_from_id;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (void)calculateSize;
- (id)initWithDictionary:(id)arg1 type:(int)arg2;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

