//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKPosts.h"

@interface VKCopyPosts : VKPosts
{
}

- (id)parseItems:(id)arg1 asClass:(Class)arg2;

@end

