//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber;

@interface VKCounters : VKObject
{
    NSNumber *_friends;
    NSNumber *_messages;
    NSNumber *_photos;
    NSNumber *_videos;
    NSNumber *_notifications;
    NSNumber *_groups;
    NSNumber *_gifts;
    NSNumber *_events;
    NSNumber *_albums;
    NSNumber *_audios;
    NSNumber *_online_friends;
    NSNumber *_mutual_friends;
    NSNumber *_user_videos;
    NSNumber *_followers;
    NSNumber *_user_photos;
    NSNumber *_subscriptions;
    NSNumber *_docs;
    NSNumber *_topics;
    NSNumber *_pages;
}

@property(retain, nonatomic) NSNumber *pages; // @synthesize pages=_pages;
@property(retain, nonatomic) NSNumber *topics; // @synthesize topics=_topics;
@property(retain, nonatomic) NSNumber *docs; // @synthesize docs=_docs;
@property(retain, nonatomic) NSNumber *subscriptions; // @synthesize subscriptions=_subscriptions;
@property(retain, nonatomic) NSNumber *user_photos; // @synthesize user_photos=_user_photos;
@property(retain, nonatomic) NSNumber *followers; // @synthesize followers=_followers;
@property(retain, nonatomic) NSNumber *user_videos; // @synthesize user_videos=_user_videos;
@property(retain, nonatomic) NSNumber *mutual_friends; // @synthesize mutual_friends=_mutual_friends;
@property(retain, nonatomic) NSNumber *online_friends; // @synthesize online_friends=_online_friends;
@property(retain, nonatomic) NSNumber *audios; // @synthesize audios=_audios;
@property(retain, nonatomic) NSNumber *albums; // @synthesize albums=_albums;
@property(retain, nonatomic) NSNumber *events; // @synthesize events=_events;
@property(retain, nonatomic) NSNumber *gifts; // @synthesize gifts=_gifts;
@property(retain, nonatomic) NSNumber *groups; // @synthesize groups=_groups;
@property(retain, nonatomic) NSNumber *notifications; // @synthesize notifications=_notifications;
@property(retain, nonatomic) NSNumber *videos; // @synthesize videos=_videos;
@property(retain, nonatomic) NSNumber *photos; // @synthesize photos=_photos;
@property(retain, nonatomic) NSNumber *messages; // @synthesize messages=_messages;
@property(retain, nonatomic) NSNumber *friends; // @synthesize friends=_friends;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

