//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObjectsArray.h"

@interface VKDialogs : VKObjectsArray
{
    long long _unread_dialogs;
}

@property(nonatomic) long long unread_dialogs; // @synthesize unread_dialogs=_unread_dialogs;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objectAtIndex:(long long)arg1;
- (Class)objectClass;

@end

