//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber, NSString;

@interface VKError : VKObject
{
    NSNumber *_error_code;
    NSString *_error_msg;
    NSString *_error_description;
    NSString *_captcha_img;
    NSString *_captcha_response;
    NSString *_captcha_sid;
    NSString *_redirect_uri;
    NSString *_validation_type;
    NSString *_validation_sid;
    NSString *_phone_mask;
    NSString *_confirmation_text;
}

@property(copy, nonatomic) NSString *confirmation_text; // @synthesize confirmation_text=_confirmation_text;
@property(copy, nonatomic) NSString *phone_mask; // @synthesize phone_mask=_phone_mask;
@property(copy, nonatomic) NSString *validation_sid; // @synthesize validation_sid=_validation_sid;
@property(copy, nonatomic) NSString *validation_type; // @synthesize validation_type=_validation_type;
@property(copy, nonatomic) NSString *redirect_uri; // @synthesize redirect_uri=_redirect_uri;
@property(copy, nonatomic) NSString *captcha_sid; // @synthesize captcha_sid=_captcha_sid;
@property(copy, nonatomic) NSString *captcha_response; // @synthesize captcha_response=_captcha_response;
@property(copy, nonatomic) NSString *captcha_img; // @synthesize captcha_img=_captcha_img;
@property(copy, nonatomic) NSString *error_description; // @synthesize error_description=_error_description;
@property(copy, nonatomic) NSString *error_msg; // @synthesize error_msg=_error_msg;
@property(retain, nonatomic) NSNumber *error_code; // @synthesize error_code=_error_code;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

