//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface VKEventsTracker : NSObject
{
    NSObject<OS_dispatch_queue> *_trackerQueue;
    NSMutableDictionary *_eventsMap;
    NSMutableArray *_eventsArray;
}

@property(retain) NSMutableArray *eventsArray; // @synthesize eventsArray=_eventsArray;
@property(retain) NSMutableDictionary *eventsMap; // @synthesize eventsMap=_eventsMap;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *trackerQueue; // @synthesize trackerQueue=_trackerQueue;
- (void).cxx_destruct;
- (void)trackVideo:(unsigned long long)arg1 videoId:(id)arg2 source:(id)arg3;
- (void)trackStorePurchase:(id)arg1 merchantProductId:(id)arg2 result:(unsigned long long)arg3 storeError:(id)arg4 apiError:(id)arg5;
- (void)trackVideoId:(id)arg1 position:(unsigned long long)arg2 source:(id)arg3 quality:(id)arg4;
- (void)trackAudio:(unsigned long long)arg1 audioId:(id)arg2 source:(id)arg3;
- (void)trackPost:(unsigned long long)arg1 postId:(id)arg2 repostId:(id)arg3;
- (void)trackEvent:(unsigned long long)arg1 objectId:(id)arg2;
- (void)sendEventsString:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)flush;
- (id)getEventOfType:(unsigned long long)arg1;
- (id)createEventOfType:(unsigned long long)arg1;
- (void)scheduleFlush;
- (id)init;
- (void)dealloc;

@end

