//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber, NSString, VKGeoPlace;

@interface VKGeo : VKObject
{
    NSString *_type;
    NSString *_coordinates;
    NSNumber *_latitude;
    NSNumber *_longitude;
    VKGeoPlace *_place;
}

@property(retain, nonatomic) VKGeoPlace *place; // @synthesize place=_place;
@property(retain, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSString *coordinates; // @synthesize coordinates=_coordinates;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithLatitude:(id)arg1 longitude:(id)arg2;
- (id)initWithDictionary:(id)arg1;

@end

