//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "Userable.h"

@class FastAttributedString, NSNumber, NSString, VKAudio, VKBanInfo, VKCity, VKCounters, VKCountry, VKGeoPlace, VKGroupContacts, VKGroupLinks, VKPhoto, VKPhotoAlbum, VKPhotoSize, VKPhotos, VKPosts;

@interface VKGroup : VKObject <Userable>
{
    _Bool _wallIsClosed;
    NSNumber *_id;
    NSString *_name;
    NSString *_screen_name;
    NSNumber *_is_closed;
    NSString *_type;
    NSNumber *_is_admin;
    NSNumber *_admin_level;
    NSNumber *_is_member;
    VKCity *_city;
    VKCountry *_country;
    VKGeoPlace *_place;
    FastAttributedString *_Mdescription;
    NSString *_wiki_page;
    NSNumber *_members_count;
    VKCounters *_counters;
    NSNumber *_start_date;
    NSNumber *_end_date;
    NSNumber *_finish_date;
    NSNumber *_can_post;
    NSNumber *_can_see_all_posts;
    NSNumber *_can_create_topic;
    NSNumber *_can_upload_doc;
    NSNumber *_can_upload_video;
    NSString *_activity;
    NSString *_status;
    VKAudio *_status_audio;
    VKGroupContacts *_contacts;
    VKGroupLinks *_links;
    NSNumber *_fixed_post;
    NSNumber *_verified;
    NSString *_site;
    NSString *_photo_50;
    NSString *_photo_100;
    NSString *_photo_200;
    NSString *_photo_max_orig;
    VKPhoto *_photo;
    NSNumber *_is_adult;
    NSNumber *_is_request;
    NSNumber *_is_invite;
    VKPhotos *_photos;
    NSNumber *_photos_count;
    NSNumber *_invited_by;
    long long _invite_state;
    VKPhotoSize *_photo_max_size;
    NSString *_deactivated;
    NSNumber *_blacklisted;
    NSNumber *_main_album_id;
    VKPosts *_suggestedPosts;
    VKPhotoAlbum *_main_album;
    VKBanInfo *_ban_info;
}

@property(nonatomic) _Bool wallIsClosed; // @synthesize wallIsClosed=_wallIsClosed;
@property(retain, nonatomic) VKBanInfo *ban_info; // @synthesize ban_info=_ban_info;
@property(retain, nonatomic) VKPhotoAlbum *main_album; // @synthesize main_album=_main_album;
@property(retain, nonatomic) VKPosts *suggestedPosts; // @synthesize suggestedPosts=_suggestedPosts;
@property(retain, nonatomic) NSNumber *main_album_id; // @synthesize main_album_id=_main_album_id;
@property(retain, nonatomic) NSNumber *blacklisted; // @synthesize blacklisted=_blacklisted;
@property(copy, nonatomic) NSString *deactivated; // @synthesize deactivated=_deactivated;
@property(retain, nonatomic) VKPhotoSize *photo_max_size; // @synthesize photo_max_size=_photo_max_size;
@property(nonatomic) long long invite_state; // @synthesize invite_state=_invite_state;
@property(retain, nonatomic) NSNumber *invited_by; // @synthesize invited_by=_invited_by;
@property(retain, nonatomic) NSNumber *photos_count; // @synthesize photos_count=_photos_count;
@property(retain, nonatomic) VKPhotos *photos; // @synthesize photos=_photos;
@property(retain, nonatomic) NSNumber *is_invite; // @synthesize is_invite=_is_invite;
@property(retain, nonatomic) NSNumber *is_request; // @synthesize is_request=_is_request;
@property(retain, nonatomic) NSNumber *is_adult; // @synthesize is_adult=_is_adult;
@property(retain, nonatomic) VKPhoto *photo; // @synthesize photo=_photo;
@property(copy, nonatomic) NSString *photo_max_orig; // @synthesize photo_max_orig=_photo_max_orig;
@property(copy, nonatomic) NSString *photo_200; // @synthesize photo_200=_photo_200;
@property(copy, nonatomic) NSString *photo_100; // @synthesize photo_100=_photo_100;
@property(copy, nonatomic) NSString *photo_50; // @synthesize photo_50=_photo_50;
@property(copy, nonatomic) NSString *site; // @synthesize site=_site;
@property(retain, nonatomic) NSNumber *verified; // @synthesize verified=_verified;
@property(retain, nonatomic) NSNumber *fixed_post; // @synthesize fixed_post=_fixed_post;
@property(retain, nonatomic) VKGroupLinks *links; // @synthesize links=_links;
@property(retain, nonatomic) VKGroupContacts *contacts; // @synthesize contacts=_contacts;
@property(retain, nonatomic) VKAudio *status_audio; // @synthesize status_audio=_status_audio;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) NSNumber *can_upload_video; // @synthesize can_upload_video=_can_upload_video;
@property(retain, nonatomic) NSNumber *can_upload_doc; // @synthesize can_upload_doc=_can_upload_doc;
@property(retain, nonatomic) NSNumber *can_create_topic; // @synthesize can_create_topic=_can_create_topic;
@property(retain, nonatomic) NSNumber *can_see_all_posts; // @synthesize can_see_all_posts=_can_see_all_posts;
@property(retain, nonatomic) NSNumber *can_post; // @synthesize can_post=_can_post;
@property(retain, nonatomic) NSNumber *finish_date; // @synthesize finish_date=_finish_date;
@property(retain, nonatomic) NSNumber *end_date; // @synthesize end_date=_end_date;
@property(retain, nonatomic) NSNumber *start_date; // @synthesize start_date=_start_date;
@property(retain, nonatomic) VKCounters *counters; // @synthesize counters=_counters;
@property(retain, nonatomic) NSNumber *members_count; // @synthesize members_count=_members_count;
@property(copy, nonatomic) NSString *wiki_page; // @synthesize wiki_page=_wiki_page;
@property(retain, nonatomic) FastAttributedString *Mdescription; // @synthesize Mdescription=_Mdescription;
@property(retain, nonatomic) VKGeoPlace *place; // @synthesize place=_place;
@property(retain, nonatomic) VKCountry *country; // @synthesize country=_country;
@property(retain, nonatomic) VKCity *city; // @synthesize city=_city;
@property(retain, nonatomic) NSNumber *is_member; // @synthesize is_member=_is_member;
@property(retain, nonatomic) NSNumber *admin_level; // @synthesize admin_level=_admin_level;
@property(retain, nonatomic) NSNumber *is_admin; // @synthesize is_admin=_is_admin;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSNumber *is_closed; // @synthesize is_closed=_is_closed;
@property(copy, nonatomic) NSString *screen_name; // @synthesize screen_name=_screen_name;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *sex;
@property(readonly, copy, nonatomic) NSString *placeholder60;
@property(readonly, copy, nonatomic) NSString *placeholder55;
@property(readonly, copy, nonatomic) NSString *placeholder50;
- (void)updateGroupWithGroup:(id)arg1 all:(_Bool)arg2;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

