//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSString;

@interface VKLink : VKObject
{
    NSString *_url;
    NSString *_title;
    NSString *_Mdescription;
    NSString *_photo_50;
    NSString *_photo_100;
    NSString *_preview_url;
    NSString *_preview_page;
}

@property(copy, nonatomic) NSString *preview_page; // @synthesize preview_page=_preview_page;
@property(copy, nonatomic) NSString *preview_url; // @synthesize preview_url=_preview_url;
@property(copy, nonatomic) NSString *photo_100; // @synthesize photo_100=_photo_100;
@property(copy, nonatomic) NSString *photo_50; // @synthesize photo_50=_photo_50;
@property(copy, nonatomic) NSString *Mdescription; // @synthesize Mdescription=_Mdescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

