//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "VKSizeable.h"

@class FastAttributedString, NSArray, NSAttributedString, NSMutableDictionary, NSNumber, NSString, VKAttachmentsArray, VKGeo, VKMessages, VKPushSettings;

@interface VKMessage : VKObject <VKSizeable>
{
    _Bool _forwarded;
    _Bool _isSending;
    _Bool _ignoreMidSort;
    _Bool _loadedAfterLongpoll;
    _Bool _isServiceMessage;
    float _attachHeight;
    float _attachWidth;
    NSNumber *_id;
    NSNumber *_user_id;
    NSNumber *_chat_id;
    NSNumber *_date;
    NSNumber *_read_state;
    NSNumber *_delete_state;
    NSNumber *_deleted;
    NSNumber *_out;
    NSString *_title;
    VKAttachmentsArray *_attachments;
    VKMessages *_fwd_messages;
    NSArray *_chat_active;
    NSNumber *_users_count;
    NSNumber *_admin_id;
    VKGeo *_geo;
    NSString *_attachString;
    NSString *_fwdString;
    NSNumber *_sentStickerId;
    long long _level;
    long long _send_state;
    NSString *_photo_50;
    NSString *_photo_100;
    NSString *_photo_200;
    VKPushSettings *_push_settings;
    NSString *_body;
    NSString *_action;
    NSNumber *_action_mid;
    NSString *_action_email;
    NSString *_action_text;
    NSAttributedString *_action_text_attributed;
    NSString *_action_text_short;
    NSMutableDictionary *_cachedActionSize;
    NSNumber *_guid;
    NSArray *_links;
    FastAttributedString *_attrStr;
    struct CGSize _sizePortrait;
    struct CGSize _sizeLandscape;
    struct FastAttributedStringSize _sizeText;
}

@property(nonatomic) struct CGSize sizeLandscape; // @synthesize sizeLandscape=_sizeLandscape;
@property(nonatomic) struct CGSize sizePortrait; // @synthesize sizePortrait=_sizePortrait;
@property(retain, nonatomic) FastAttributedString *attrStr; // @synthesize attrStr=_attrStr;
@property(nonatomic) struct FastAttributedStringSize sizeText; // @synthesize sizeText=_sizeText;
@property(retain, nonatomic) NSArray *links; // @synthesize links=_links;
@property(retain, nonatomic) NSNumber *guid; // @synthesize guid=_guid;
@property(retain, nonatomic) NSMutableDictionary *cachedActionSize; // @synthesize cachedActionSize=_cachedActionSize;
@property(copy, nonatomic) NSString *action_text_short; // @synthesize action_text_short=_action_text_short;
@property(retain, nonatomic) NSAttributedString *action_text_attributed; // @synthesize action_text_attributed=_action_text_attributed;
@property(copy, nonatomic) NSString *action_text; // @synthesize action_text=_action_text;
@property(copy, nonatomic) NSString *action_email; // @synthesize action_email=_action_email;
@property(retain, nonatomic) NSNumber *action_mid; // @synthesize action_mid=_action_mid;
@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(nonatomic) _Bool isServiceMessage; // @synthesize isServiceMessage=_isServiceMessage;
@property(nonatomic) _Bool loadedAfterLongpoll; // @synthesize loadedAfterLongpoll=_loadedAfterLongpoll;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(retain, nonatomic) VKPushSettings *push_settings; // @synthesize push_settings=_push_settings;
@property(copy, nonatomic) NSString *photo_200; // @synthesize photo_200=_photo_200;
@property(copy, nonatomic) NSString *photo_100; // @synthesize photo_100=_photo_100;
@property(copy, nonatomic) NSString *photo_50; // @synthesize photo_50=_photo_50;
@property(nonatomic) float attachWidth; // @synthesize attachWidth=_attachWidth;
@property(nonatomic) float attachHeight; // @synthesize attachHeight=_attachHeight;
@property(nonatomic) long long send_state; // @synthesize send_state=_send_state;
@property(nonatomic) _Bool ignoreMidSort; // @synthesize ignoreMidSort=_ignoreMidSort;
@property(nonatomic) _Bool isSending; // @synthesize isSending=_isSending;
@property(nonatomic) _Bool forwarded; // @synthesize forwarded=_forwarded;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(retain, nonatomic) NSNumber *sentStickerId; // @synthesize sentStickerId=_sentStickerId;
@property(copy, nonatomic) NSString *fwdString; // @synthesize fwdString=_fwdString;
@property(copy, nonatomic) NSString *attachString; // @synthesize attachString=_attachString;
@property(retain, nonatomic) VKGeo *geo; // @synthesize geo=_geo;
@property(retain, nonatomic) NSNumber *admin_id; // @synthesize admin_id=_admin_id;
@property(retain, nonatomic) NSNumber *users_count; // @synthesize users_count=_users_count;
@property(retain, nonatomic) NSArray *chat_active; // @synthesize chat_active=_chat_active;
@property(retain, nonatomic) VKMessages *fwd_messages; // @synthesize fwd_messages=_fwd_messages;
@property(retain, nonatomic) VKAttachmentsArray *attachments; // @synthesize attachments=_attachments;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *out; // @synthesize out=_out;
@property(retain, nonatomic) NSNumber *deleted; // @synthesize deleted=_deleted;
@property(retain, nonatomic) NSNumber *delete_state; // @synthesize delete_state=_delete_state;
@property(retain, nonatomic) NSNumber *read_state; // @synthesize read_state=_read_state;
@property(retain, nonatomic) NSNumber *date; // @synthesize date=_date;
@property(retain, nonatomic) NSNumber *chat_id; // @synthesize chat_id=_chat_id;
@property(retain, nonatomic) NSNumber *user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *peer_id;
- (_Bool)outOfConversation;
@property(readonly, copy) NSString *description;
- (id)serialize;
- (void)formatAction;
- (void)calculateSize;
- (void)rebuild;
- (void)updateMessageWithMessage:(id)arg1;
- (void)increaseLevelRecursively:(int)arg1;
- (void)buildMessage;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

