//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSArray;

@interface VKMutual : VKObject
{
    long long _count;
    NSArray *_users;
}

@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
@property(nonatomic) long long count; // @synthesize count=_count;
- (void).cxx_destruct;

@end

