//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "VKMultipartBodyStreamElementProtocol.h"

@class NSString;

@interface VKMultipartBodyStreamElement : NSObject <VKMultipartBodyStreamElementProtocol>
{
    unsigned long long stringEncoding;
    unsigned long long cursor;
    NSString *_name;
}

@property(copy) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)headerElement;
- (unsigned long long)contentLength;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (id)initWithStringEncoding:(unsigned long long)arg1;
- (id)initWithName:(id)arg1 stringEncoding:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

