//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@class NSMutableArray;

@interface VKMultipartBodyStreamElements : NSEnumerator
{
    unsigned long long elementCursor;
    NSMutableArray *elements;
    unsigned long long _stringEncoding;
}

@property(nonatomic) unsigned long long stringEncoding; // @synthesize stringEncoding=_stringEncoding;
- (void).cxx_destruct;
- (void)insertElementBeforeFinalBoundary:(id)arg1;
- (void)appendPartWithElement:(id)arg1;
- (_Bool)appendPartWithFileURL:(id)arg1 name:(id)arg2 error:(id *)arg3;
- (void)appendPartWithFormData:(id)arg1 name:(id)arg2;
- (unsigned long long)contentLength;
- (id)allObjects;
- (id)nextObject;
- (id)initWithStringEncoding:(unsigned long long)arg1;

@end

