//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "VKSizeable.h"

@class FastAttributedString, NSNumber, NSString, VKReply;

@interface VKNotification : VKObject <VKSizeable>
{
    float _heightPost;
    float _heightRepost;
    NSString *_type;
    NSNumber *_date;
    id _parent;
    id _feedback;
    VKReply *_reply;
    FastAttributedString *_attrStr;
    FastAttributedString *_titleString;
    struct FastAttributedStringSize _textSize;
    struct FastAttributedStringSize _titleSize;
}

@property(retain, nonatomic) FastAttributedString *titleString; // @synthesize titleString=_titleString;
@property(nonatomic) struct FastAttributedStringSize titleSize; // @synthesize titleSize=_titleSize;
@property(retain, nonatomic) FastAttributedString *attrStr; // @synthesize attrStr=_attrStr;
@property(nonatomic) struct FastAttributedStringSize textSize; // @synthesize textSize=_textSize;
@property(nonatomic) float heightRepost; // @synthesize heightRepost=_heightRepost;
@property(nonatomic) float heightPost; // @synthesize heightPost=_heightPost;
@property(retain, nonatomic) VKReply *reply; // @synthesize reply=_reply;
@property(retain, nonatomic) id feedback; // @synthesize feedback=_feedback;
@property(retain, nonatomic) id parent; // @synthesize parent=_parent;
@property(retain, nonatomic) NSNumber *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (void)buildTitle;
- (void)calculateSize;
- (int)feedbackCommentType;
- (id)frontPhoto;
- (id)arrayOfUserIds:(id)arg1;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

