//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "NSFastEnumeration.h"

@class NSMutableArray;

@interface VKObjectsArray : VKObject <NSFastEnumeration>
{
    unsigned long long _count;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
- (void).cxx_destruct;
@property(readonly, nonatomic) Class objectClass;
- (_Bool)containsObject:(id)arg1;
- (void)serializeTo:(id)arg1 withName:(id)arg2;
- (id)serialize;
- (void)filterUsingPredicate:(id)arg1;
- (void)removeAllObjects;
- (id)lastObject;
- (id)firstObject;
- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)removeObject:(id)arg1;
- (void)addObjectsFromArray:(id)arg1;
- (void)addObject:(id)arg1;
- (id)reverseObjectEnumerator;
- (id)objectEnumerator;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objectAtIndex:(long long)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)parseItems:(id)arg1 asClass:(Class)arg2;
- (id)initWithDictionary:(id)arg1;
- (id)initWithArray:(id)arg1;
- (id)initWithArray:(id)arg1 objectClass:(Class)arg2;
- (id)initWithDictionary:(id)arg1 objectClass:(Class)arg2;
- (id)initWith:(id)arg1;
- (id)init;

@end

