//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "Attachable.h"

@class NSNumber, NSString, VKPollAnswersArray;

@interface VKPoll : VKObject <Attachable>
{
    NSNumber *_id;
    NSNumber *_owner_id;
    NSNumber *_created;
    NSNumber *_is_closed;
    NSString *_question;
    NSNumber *_votes;
    NSNumber *_answer_id;
    NSNumber *_anonymous;
    VKPollAnswersArray *_answers;
    NSNumber *_is_board;
}

@property(retain, nonatomic) NSNumber *is_board; // @synthesize is_board=_is_board;
@property(retain, nonatomic) VKPollAnswersArray *answers; // @synthesize answers=_answers;
@property(retain, nonatomic) NSNumber *anonymous; // @synthesize anonymous=_anonymous;
@property(retain, nonatomic) NSNumber *answer_id; // @synthesize answer_id=_answer_id;
@property(retain, nonatomic) NSNumber *votes; // @synthesize votes=_votes;
@property(copy, nonatomic) NSString *question; // @synthesize question=_question;
@property(retain, nonatomic) NSNumber *is_closed; // @synthesize is_closed=_is_closed;
@property(retain, nonatomic) NSNumber *created; // @synthesize created=_created;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)attachmentStringLight;
- (id)attachmentString;
- (id)objectString;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

