//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber, VKUsers;

@interface VKPollAnswerInfo : VKObject
{
    VKUsers *_users;
    NSNumber *_answer_id;
}

@property(retain, nonatomic) NSNumber *answer_id; // @synthesize answer_id=_answer_id;
@property(retain, nonatomic) VKUsers *users; // @synthesize users=_users;
- (void).cxx_destruct;

@end

