//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKProduct.h"

@interface VKProduct (Loading)
@property(nonatomic, setter=setContentLoaded:) _Bool contentLoaded;
@property(nonatomic, setter=setDownloadProgress:) double downloadProgress;
@property(nonatomic, setter=setIsLoading:) _Bool isLoading;
@end

