//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSArray, NSNumber, NSString, VKProduct;

@interface VKStockItem : VKObject
{
    VKProduct *_product;
    NSString *_author;
    NSString *_Mdescription;
    NSNumber *_can_purchase;
    NSString *_merchant_product_id;
    NSNumber *_free;
    NSNumber *_Mnew;
    NSString *_photo_35;
    NSString *_photo_70;
    NSString *_photo_140;
    NSString *_photo_296;
    NSString *_photo_592;
    NSString *_background;
    NSArray *_demo_photos_560;
    NSString *_payment_type;
    NSNumber *_price;
    NSString *_price_str;
    NSString *_referrer;
}

@property(retain, nonatomic) NSString *referrer; // @synthesize referrer=_referrer;
@property(copy, nonatomic) NSString *price_str; // @synthesize price_str=_price_str;
@property(retain, nonatomic) NSNumber *price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *payment_type; // @synthesize payment_type=_payment_type;
@property(retain, nonatomic) NSArray *demo_photos_560; // @synthesize demo_photos_560=_demo_photos_560;
@property(copy, nonatomic) NSString *background; // @synthesize background=_background;
@property(copy, nonatomic) NSString *photo_592; // @synthesize photo_592=_photo_592;
@property(copy, nonatomic) NSString *photo_296; // @synthesize photo_296=_photo_296;
@property(copy, nonatomic) NSString *photo_140; // @synthesize photo_140=_photo_140;
@property(copy, nonatomic) NSString *photo_70; // @synthesize photo_70=_photo_70;
@property(copy, nonatomic) NSString *photo_35; // @synthesize photo_35=_photo_35;
@property(retain, nonatomic) NSNumber *Mnew; // @synthesize Mnew=_Mnew;
@property(retain, nonatomic) NSNumber *free; // @synthesize free=_free;
@property(copy, nonatomic) NSString *merchant_product_id; // @synthesize merchant_product_id=_merchant_product_id;
@property(retain, nonatomic) NSNumber *can_purchase; // @synthesize can_purchase=_can_purchase;
@property(copy, nonatomic) NSString *Mdescription; // @synthesize Mdescription=_Mdescription;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) VKProduct *product; // @synthesize product=_product;
- (void).cxx_destruct;
- (id)description;

@end

