//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

@class NSNumber, VKPosts;

@interface VKSuggestion : VKObject
{
    NSNumber *_id;
    VKPosts *_suggestions;
}

@property(retain, nonatomic) VKPosts *suggestions; // @synthesize suggestions=_suggestions;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

