//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKObject.h"

#import "Attachable.h"

@class NSMutableString, NSNumber, NSString;

@interface VKTopic : VKObject <Attachable>
{
    NSNumber *_id;
    NSString *_title;
    NSNumber *_created;
    NSNumber *_created_by;
    NSNumber *_updated;
    NSNumber *_updated_by;
    NSNumber *_is_closed;
    NSNumber *_is_fixed;
    NSNumber *_comments;
    NSNumber *_group_id;
    NSNumber *_owner_id;
    NSMutableString *_first_comment;
    NSMutableString *_last_comment;
}

@property(retain, nonatomic) NSMutableString *last_comment; // @synthesize last_comment=_last_comment;
@property(retain, nonatomic) NSMutableString *first_comment; // @synthesize first_comment=_first_comment;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *group_id; // @synthesize group_id=_group_id;
@property(retain, nonatomic) NSNumber *comments; // @synthesize comments=_comments;
@property(retain, nonatomic) NSNumber *is_fixed; // @synthesize is_fixed=_is_fixed;
@property(retain, nonatomic) NSNumber *is_closed; // @synthesize is_closed=_is_closed;
@property(retain, nonatomic) NSNumber *updated_by; // @synthesize updated_by=_updated_by;
@property(retain, nonatomic) NSNumber *updated; // @synthesize updated=_updated;
@property(retain, nonatomic) NSNumber *created_by; // @synthesize created_by=_created_by;
@property(retain, nonatomic) NSNumber *created; // @synthesize created=_created;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)attachmentString;
- (id)attachmentStringLight;
- (id)objectString;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

