//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSArray, NSString;

@interface voip_init_res : VKResponse
{
    NSArray *_params;
    NSString *_server;
}

@property(copy, nonatomic) NSString *server; // @synthesize server=_server;
@property(retain, nonatomic) NSArray *params; // @synthesize params=_params;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

