//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, NSString;

@interface voip_start_res : VKResponse
{
    NSNumber *_id;
    NSString *_near_stream;
}

@property(copy, nonatomic) NSString *near_stream; // @synthesize near_stream=_near_stream;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

