//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber, NSString;

@interface voip_received_res : VKResponse
{
    NSString *_far_stream;
    NSNumber *_from_id;
    NSString *_Mhash;
    NSNumber *_id;
    NSString *_rtmp_server;
    NSNumber *_to_id;
}

@property(retain, nonatomic) NSNumber *to_id; // @synthesize to_id=_to_id;
@property(copy, nonatomic) NSString *rtmp_server; // @synthesize rtmp_server=_rtmp_server;
@property(retain, nonatomic) NSNumber *id; // @synthesize id=_id;
@property(copy, nonatomic) NSString *Mhash; // @synthesize Mhash=_Mhash;
@property(retain, nonatomic) NSNumber *from_id; // @synthesize from_id=_from_id;
@property(copy, nonatomic) NSString *far_stream; // @synthesize far_stream=_far_stream;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

