//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber;

@interface wall_repost_res : VKResponse
{
    NSNumber *_post_id;
    NSNumber *_likes_count;
    NSNumber *_reposts_count;
    NSNumber *_success;
}

@property(retain, nonatomic) NSNumber *success; // @synthesize success=_success;
@property(retain, nonatomic) NSNumber *reposts_count; // @synthesize reposts_count=_reposts_count;
@property(retain, nonatomic) NSNumber *likes_count; // @synthesize likes_count=_likes_count;
@property(retain, nonatomic) NSNumber *post_id; // @synthesize post_id=_post_id;
- (void).cxx_destruct;

@end

