//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface wall_search_req : VKRequest
{
    NSNumber *_owner_id;
    NSString *_domain;
    NSString *_query;
    NSNumber *_owners_only;
    NSNumber *_count;
    NSNumber *_offset;
    NSNumber *_extended;
    NSString *_fields;
}

@property(copy, nonatomic) NSString *fields; // @synthesize fields=_fields;
@property(retain, nonatomic) NSNumber *extended; // @synthesize extended=_extended;
@property(retain, nonatomic) NSNumber *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *owners_only; // @synthesize owners_only=_owners_only;
@property(copy, nonatomic) NSString *query; // @synthesize query=_query;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

