//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface wall_getById_req : VKRequest
{
    NSString *_posts;
    NSNumber *_extended;
}

@property(retain, nonatomic) NSNumber *extended; // @synthesize extended=_extended;
@property(copy, nonatomic) NSString *posts; // @synthesize posts=_posts;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

