//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber;

@interface wall_post_res : VKResponse
{
    NSNumber *_post_id;
}

@property(retain, nonatomic) NSNumber *post_id; // @synthesize post_id=_post_id;
- (void).cxx_destruct;

@end

