//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class VKComments;

@interface wall_getComments_res : VKResponse
{
    VKComments *_comments;
}

@property(retain, nonatomic) VKComments *comments; // @synthesize comments=_comments;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

