//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

#import "ReportCommentMethod.h"

@class NSNumber, NSString;

@interface wall_reportComment_req : VKRequest <ReportCommentMethod>
{
    NSNumber *_owner_id;
    NSNumber *_comment_id;
    NSNumber *_reason;
}

@property(retain, nonatomic) NSNumber *reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSNumber *comment_id; // @synthesize comment_id=_comment_id;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(copy, nonatomic) CDUnknownBlockType didFailedBlock;
@property(copy, nonatomic) CDUnknownBlockType didFinishBlock;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) CDUnknownBlockType processingBlock;
@property(retain, nonatomic) id <VKResponse> response;
@property(copy, nonatomic) NSString *senderGUID;
@property(readonly) Class superclass;

@end

