//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKResponse.h"

@class NSNumber;

@interface wall_addComment_res : VKResponse
{
    NSNumber *_comment_id;
}

@property(retain, nonatomic) NSNumber *comment_id; // @synthesize comment_id=_comment_id;
- (void).cxx_destruct;

@end

