//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKRequest.h"

@class NSNumber, NSString;

@interface wall_addComment_req : VKRequest
{
    NSNumber *_post_id;
    NSNumber *_owner_id;
    NSString *_text;
    NSNumber *_reply_to_comment;
    NSString *_attachments;
    NSNumber *_from_group;
    NSNumber *_sticker_id;
}

@property(retain, nonatomic) NSNumber *sticker_id; // @synthesize sticker_id=_sticker_id;
@property(retain, nonatomic) NSNumber *from_group; // @synthesize from_group=_from_group;
@property(copy, nonatomic) NSString *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) NSNumber *reply_to_comment; // @synthesize reply_to_comment=_reply_to_comment;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSNumber *owner_id; // @synthesize owner_id=_owner_id;
@property(retain, nonatomic) NSNumber *post_id; // @synthesize post_id=_post_id;
- (void).cxx_destruct;
- (Class)responseClass;
- (id)getMethodName;

@end

