//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface AnyCounter : UIView
{
    double _offsetY;
    double _edge;
    UIImageView *_bgImage;
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *bgImage; // @synthesize bgImage=_bgImage;
@property(nonatomic) double edge; // @synthesize edge=_edge;
@property(nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
- (void)setFont:(id)arg1;
- (void)setBackground:(id)arg1;
- (void)setTextColor:(id)arg1;
- (void)setText:(id)arg1;
- (void)setCount:(long long)arg1;
- (id)formatStringForNumber:(long long)arg1;
- (id)initWithCounterBackground:(id)arg1 font:(id)arg2 textColor:(id)arg3 edge:(double)arg4;

@end

